Update to manually parse options from piranha
In several scripts, I have updated code for identifying and parsing options from arguments "$@" passed from piranha. Tested updated code; working. Added additional output to screen describing run settings based on parsed options. Original code working for functions with one main option (not counting -h|-H or -V); however, need to continue implementing similar updates for all piranha functions with multiple options.

diff --git a/bin/BEASTRunner b/bin/BEASTRunner
--- a/bin/BEASTRunner
+++ b/bin/BEASTRunner
@@ -6,10 +6,10 @@
 # |                                                                                      #
 #                                                                                        #
 # File: BEASTRunner.sh                                                                   #
-  VERSION="v1.4.1"                                                                       #
+  VERSION="v1.5.0"                                                                       #
 # Author: Justin C. Bagley                                                               #
 # Date: Created by Justin Bagley on Fri, 11 Nov 2016 14:33:51 -0600.                     #
-# Last update: March 20, 2019                                                            #
+# Last update: April 10, 2019                                                            #
 # Copyright (c) 2016-2019 Justin C. Bagley. All rights reserved.                         #
 # Please report bugs to <bagleyj@umsl.edu>.                                              #
 #                                                                                        #
@@ -136,12 +136,17 @@ BEASTRunner () {
 ##########################################################################################
 
 echo "INFO      | $(date) |----------------------------------------------------------------"
-echo "INFO      | $(date) | BEASTRunner, v1.4.1 March 2019  (in PIrANHA v0.2-alpha.2)     "
+echo "INFO      | $(date) | BEASTRunner, v1.5.0 April 2019  (in PIrANHA v0.2-alpha.2)     "
 echo "INFO      | $(date) | Copyright (c) 2016-2019 Justin C. Bagley. All rights reserved. "
 echo "INFO      | $(date) |----------------------------------------------------------------"
 
 ######################################## START ###########################################
 echo "INFO      | $(date) | Starting BEASTRunner pipeline... "
+echo "INFO      | $(date) |          Running with the following options: "
+echo "INFO      | $(date) |          - Number of runs, <nRuns> = ${MY_NUM_INDEP_RUNS} "
+echo "INFO      | $(date) |          - Supercomputer run <walltime> = ${MY_SC_WALLTIME} "
+echo "INFO      | $(date) |          - Java memory allocation, <javaMem> = ${JAVA_MEM_ALLOC} "
+
 echo "INFO      | $(date) | Step #1: Set up workspace and check machine type. "
 ############ SET WORKING DIRECTORY AND CHECK MACHINE TYPE
 USER_SPEC_PATH="$(printf '%q\n' "$(pwd)")";
@@ -169,23 +174,23 @@ for a total of five runs of "
 echo "INFO      | $(date) |          each model/XML using different random number seeds. "
 echo "INFO      | $(date) |          Setting up variables, including those specified in the cfg file, and reading XML files into environmental variable..."
 
-	MY_XML_FILES=./*.xml
-	MY_NUM_XML="$(ls . | grep "\.xml$" | wc -l)"
+	MY_XML_FILES=./*.xml ;
+	MY_NUM_XML="$(ls . | grep "\.xml$" | wc -l)";
 echo "INFO      | $(date) |          Number of XML files read: $MY_NUM_XML"		## Check number of input files read into program.
 
 	MY_SSH_ACCOUNT="$(grep -n "ssh_account" ./beast_runner.cfg | \
-	awk -F"=" '{print $NF}')"
+	awk -F"=" '{print $NF}')";
 	MY_SC_DESTINATION="$(grep -n "destination_path" ./beast_runner.cfg | \
-	awk -F"=" '{print $NF}' | sed 's/\ //g')"					## This pulls out the correct destination path on the supercomputer from the "beast_runner.cfg" configuration file in the working directory (generated/modified by user prior to running BEASTRunner).
+	awk -F"=" '{print $NF}' | sed 's/\ //g')"	;				## This pulls out the correct destination path on the supercomputer from the "beast_runner.cfg" configuration file in the working directory (generated/modified by user prior to running BEASTRunner).
 	MY_SC_BIN="$(grep -n "bin_path" ./beast_runner.cfg | \
-	awk -F"=" '{print $NF}' | sed 's/\ //g')"
+	awk -F"=" '{print $NF}' | sed 's/\ //g')";
 	MY_EMAIL_ACCOUNT="$(grep -n "email_account" ./beast_runner.cfg | \
-	awk -F"=" '{print $NF}')"
+	awk -F"=" '{print $NF}')";
 	MY_SC_PBS_WKDIR_CODE="$(grep -n "pbs_wkdir_code" ./beast_runner.cfg | \
-	awk -F"=" '{print $NF}')"
+	awk -F"=" '{print $NF}')";
 ##	MY_NUM_INDEP_RUNS="$(grep -n "n_runs" ./beast_runner.cfg | awk -F"=" '{print $NF}')"
 	MY_BEAST_PATH="$(grep -n "beast_path" ./beast_runner.cfg | \
-	awk -F"=" '{print $NF}')"
+	awk -F"=" '{print $NF}')";
 
 
 echo "INFO      | $(date) | STEP #2: MAKE $(calc $MY_NUM_INDEP_RUNS - 1) COPIES PER INPUT .XML FILE FOR A TOTAL OF $MY_NUM_INDEP_RUNS RUNS OF EACH MODEL or "
@@ -293,7 +298,7 @@ echo "#!/bin/bash
 
 echo "cd $MY_SC_DESTINATION$FOLDERNAME
 qsub beast_pbs.sh
-#" >> cd_and_qsub_commands.txt
+#" >> cd_and_qsub_commands.txt ;
 
 	done
 )
@@ -363,12 +368,6 @@ echo ""
 
 
 
-############ SCRIPT OPTIONS
-## OPTION DEFAULTS ##
-MY_NUM_INDEP_RUNS=5
-MY_SC_WALLTIME=48:00:00
-JAVA_MEM_ALLOC=5120M
-
 ############ CREATE USAGE & HELP TEXTS
 USAGE="Usage: $(basename $0) [OPTION]...
 
@@ -413,10 +412,10 @@ USAGE="Usage: $(basename $0) [OPTION]...
 
  ${bold}Usage examples:${reset}
  Call the program using PIrANHA, as follows:
-    piranha -f BEASTRunner                                 Run with default settings
-    piranha -f BEASTRunner --args='-n 10'                  Change the number of runs to 10
-    piranha -f BEASTRunner --args='-n 10 -w 24:00:00'            Also edit run walltime
-    piranha -f BEASTRunner --args='-n 10 -w 24:00:00 -m 2048M'        Change memory (RAM) allocation to 2GB
+    piranha -f BEASTRunner                                      Run with default settings
+    piranha -f BEASTRunner --args='-n 10'                       Change the number of runs to 10
+    piranha -f BEASTRunner --args='-n 10 -w 24:00:00'           Also edit run walltime
+    piranha -f BEASTRunner --args='-n 10 -w 24:00:00 -m 2048M'  Change memory (RAM) allocation to 2GB
 	
  ${bold}CITATION${reset}
  Bagley, J.C. 2019. PIrANHA v0.2-alpha.2. GitHub repository, Available at:
@@ -491,10 +490,10 @@ VERBOSE_USAGE="Usage: $(basename $0) [OPTION]...
  
  ${bold}Usage examples:${reset}
  Call the program using PIrANHA, as follows:
-    piranha -f BEASTRunner                                 Run with default settings
-    piranha -f BEASTRunner --args='-n 10'                  Change the number of runs to 10
-    piranha -f BEASTRunner --args='-n 10 -w 24:00:00'            Also edit run walltime
-    piranha -f BEASTRunner --args='-n 10 -w 24:00:00 -m 2048M'        Change memory (RAM) allocation to 2GB
+    piranha -f BEASTRunner                                      Run with default settings
+    piranha -f BEASTRunner --args='-n 10'                       Change the number of runs to 10
+    piranha -f BEASTRunner --args='-n 10 -w 24:00:00'           Also edit run walltime
+    piranha -f BEASTRunner --args='-n 10 -w 24:00:00 -m 2048M'  Change memory (RAM) allocation to 2GB
 	
  ${bold}CITATION${reset}
  Bagley, J.C. 2019. PIrANHA v0.2-alpha.2. GitHub repository, Available at:
@@ -526,22 +525,66 @@ if [[ "$1" == "-V" ]] || [[ "$1" == "--version" ]]; then
 	exit
 fi
 
-############ PARSE THE OPTIONS
-while getopts 'n:w:m:' opt ; do
-  case $opt in
-## BEASTRunner options:
-    n) MY_NUM_INDEP_RUNS=$OPTARG ;;
-    w) MY_SC_WALLTIME=$OPTARG ;;
-    m) JAVA_MEM_ALLOC=$OPTARG ;;
-## Missing and illegal options:
-    :) printf "Missing argument for -%s\n" "$OPTARG" >&2
-       echo "$USAGE" >&2
-       exit 1 ;;
-   \?) printf "Illegal option: -%s\n" "$OPTARG" >&2
-       echo "$USAGE" >&2
-       exit 1 ;;
-  esac
-done
+############ CHECK ARGUMENTS
+	# echo "$@"; echo "$#"; echo "$1" 
+	# for i in "$@"; do
+	# 	echo "$i";
+	# done
+	# MY_ARGS="$(echo "$@" | perl -pe $'s/\ /\n/')"
+	# echo "$MY_ARGS"
+
+
+############ CAPTURE ARGUMENTS, SEND TO FILE FOR PARSING
+	if [[ -s ./args.tmp ]]; then rm ./args.tmp ; fi ;
+	if [[ -s ./args.txt ]]; then rm ./args.txt ; fi ;
+
+	ALL_MY_ARGUMENTS="$(echo "$@")"
+	echo "$ALL_MY_ARGUMENTS" > ./args.txt
+	perl -p -i -e $'s/\ /\n/g' ./args.txt
+	#wc -l ./args.txt | perl -pe 's/\.\/args\.txt.*//g' | perl -pe 's/\ //g'
+
+
+############ MANUALLY PARSE THE OPTIONS FROM ARGS
+
+### SET OPTIONS TO DEFAULT VALUES, EXCEPT WHERE VALUES WERE READ IN FROM USER ARGS
+	if [[  "$(grep -h '\-n' ./args.txt | wc -l | perl -pe 's/\ //g')" = "0" ]]; then
+		MY_NUM_INDEP_RUNS=5 ;
+	else 
+		MY_ARG="$(grep -h '\-n' ./args.txt | perl -pe 's/\-n//g')";
+		MY_NUM_INDEP_RUNS="$MY_ARG" ;
+	fi
+#
+	if [[  "$(grep -h '\-w' ./args.txt | wc -l | perl -pe 's/\ //g')" = "0" ]]; then
+		MY_SC_WALLTIME=48:00:00 ;
+	else 
+		MY_ARG="$(grep -h '\-w' ./args.txt | perl -pe 's/\-w//g')";
+		MY_SC_WALLTIME="$MY_ARG" ;
+	fi
+#
+	if [[  "$(grep -h '\-m' ./args.txt | wc -l | perl -pe 's/\ //g')" = "0" ]]; then
+		JAVA_MEM_ALLOC=5120M ;
+	else 
+		MY_ARG="$(grep -h '\-m' ./args.txt | perl -pe 's/\-m//g')";
+		JAVA_MEM_ALLOC="$MY_ARG" ;
+	fi
+
+
+# ############ PARSE THE OPTIONS
+# while getopts 'n:w:m:' opt ; do
+#   case $opt in
+# ## BEASTRunner options:
+#     n) MY_NUM_INDEP_RUNS=$OPTARG ;;
+#     w) MY_SC_WALLTIME=$OPTARG ;;
+#     m) JAVA_MEM_ALLOC=$OPTARG ;;
+# ## Missing and illegal options:
+#     :) printf "Missing argument for -%s\n" "$OPTARG" >&2
+#        echo "$USAGE" >&2
+#        exit 1 ;;
+#    \?) printf "Illegal option: -%s\n" "$OPTARG" >&2
+#        echo "$USAGE" >&2
+#        exit 1 ;;
+#   esac
+# done
 
 
 # ############# ############# #############
diff --git a/bin/FASTA2VCF b/bin/FASTA2VCF
--- a/bin/FASTA2VCF
+++ b/bin/FASTA2VCF
@@ -6,10 +6,10 @@
 # |                                                                                      #
 #                                                                                        #
 # File: FASTA2VCF.sh                                                                     #
-  VERSION="v1.0.0"                                                                       #
+  VERSION="v1.1.0"                                                                       #
 # Author: Justin C. Bagley                                                               #
 # Date: Created by Justin Bagley on Fri, Mar 29 12:49:36 CDT 2019.                       #
-# Last update: March 29, 2019                                                            #
+# Last update: April 10, 2019                                                            #
 # Copyright (c) 2019 Justin C. Bagley. All rights reserved.                              #
 # Please report bugs to <bagleyj@umsl.edu>.                                              #
 #                                                                                        #
@@ -141,12 +141,20 @@ FASTA2VCF () {
 ##########################################################################################
 
 echo "INFO      | $(date) |----------------------------------------------------------------"
-echo "INFO      | $(date) | FASTA2VCF, v1.0.0 March 2019  (in PIrANHA v0.2-alpha.2)    "
+echo "INFO      | $(date) | FASTA2VCF, v1.1.0 April 2019  (in PIrANHA v0.2-alpha.2)        "
 echo "INFO      | $(date) | Copyright (c) 2019 Justin C. Bagley. All rights reserved.      "
 echo "INFO      | $(date) |----------------------------------------------------------------"
 
 ######################################## START ###########################################
 echo "INFO      | $(date) | Starting FASTA2VCF analysis... "
+echo "INFO      | $(date) |          Running with the following options: "
+echo "INFO      | $(date) |          - FASTA file, <inputFASTA> = ${MY_INPUT_FASTA} "
+echo "INFO      | $(date) |          - <partitionRanges> option = ${MY_PART_RANGES_FILE} "
+echo "INFO      | $(date) |          - Output file basename, <output> = ${MY_OUTPUT_FILENAME} (yields '${MY_OUTPUT_FILENAME}.vcf')"
+echo "INFO      | $(date) |          - Subsample SNPs switch, <subsampleSNPs> = ${MY_SUBSAMPLE_SNPS_SWITCH} "
+echo "INFO      | $(date) |          - Log file option, <logfile> = ${MY_LOGFILE_SWITCH} "
+echo "INFO      | $(date) |          - <outputPHYLIP> option = ${MY_OUTPUT_PHYLIP_SWITCH} "
+
 echo "INFO      | $(date) | Step #1: Set up workspace and check machine type. "
 ############ SET WORKING DIRECTORY AND CHECK MACHINE TYPE
 USER_SPEC_PATH="$(printf '%q\n' "$(pwd)")";
@@ -278,19 +286,22 @@ count=1
 		echo "INFO      | $(date) |          Extracting: "
 		echo "INFO      | $(date) |          SNP $MY_FIRST_MATCH_LINE (VCF row), alignment position (nt) $MY_FIRST_MATCH_POSITION "
 		
-	done < raxml_partitions.part_ranges_spaced.txt
+	done < "$MY_PART_RANGES_FILE"
 )
 
 	## Put it all together. Grab the VCF header. Then concatenate the VCF header and final, 
 	## subsampled VCF body file to create a final subsampled VCF file:
 	grep '\#' "$MY_INPUT_VCF_FILE" > ./header.tmp
 
-	if [[ "$MY_OUTPUT_FILENAME" = "NULL" ]]; then
+	if [[ "$MY_OUTPUT_FILENAME" = "NULL" ]] && [[ -s ./vcf.body.tmp ]]; then
 		echo "INFO      | $(date) |          Saving subsampled SNPs to file ${MY_FASTA_BASENAME}.subsampled.vcf "
 		cat ./header.tmp ./vcf.body.tmp > "$MY_FASTA_BASENAME".subsampled.vcf
-	elif [[ "$MY_OUTPUT_FILENAME" != "NULL" ]]; then
+	elif [[ "$MY_OUTPUT_FILENAME" != "NULL" ]] && [[ -s ./vcf.body.tmp ]]; then
 		echo "INFO      | $(date) |          Saving subsampled SNPs to file ${MY_OUTPUT_FILENAME}.subsampled.vcf "
 		cat ./header.tmp ./vcf.body.tmp > "$MY_OUTPUT_FILENAME".subsampled.vcf 
+	elif [[ "$MY_OUTPUT_FILENAME" = "NULL" ]] || [[ "$MY_OUTPUT_FILENAME" != "NULL" ]] && [[ ! -s ./vcf.body.tmp ]]; then
+		echo "WARNING!  | $(date) |          Failed to save subsampled SNPs to file. This is probably because your FASTA file has one locus, or too few "
+		echo "WARNING!  | $(date) |             loci/variable sites. Please try with another FASTA file. "
 	fi
 
 fi
@@ -300,12 +311,28 @@ fi
 echo "INFO      | $(date) | Step #4: Clean up working directory by removing temporary files. "
 ## Remove temporary files generated above.
 	rm ./*.tmp
+	rm ./args.txt ;	## Remove arguments file generated when parsing the options.
+
 
 #echo "INFO      | $(date) | Done converting your multiple sequence FASTA file to VCF format using FASTA2VCF.sh. "
 #echo "INFO      | $(date) | Bye.
 #"
 
 echo "----------------------------------------------------------------------------------------------------------"
+if [[ -s "$MY_FASTA_BASENAME".subsampled.vcf ]]; then
+	echo "output file(s): ${MY_FASTA_BASENAME}.vcf "
+	echo "                ${MY_FASTA_BASENAME}.subsampled.vcf "
+fi
+if [[ -s "$MY_OUTPUT_FILENAME".subsampled.vcf ]]; then
+	echo "output file(s): ${MY_OUTPUT_FILENAME}.vcf "
+	echo "                ${MY_OUTPUT_FILENAME}.subsampled.vcf "
+fi
+if [[ -s "$MY_FASTA_BASENAME".vcf ]] && [[ ! -s "$MY_FASTA_BASENAME".subsampled.vcf ]]; then
+	echo "output file(s): ${MY_FASTA_BASENAME}.vcf "
+fi
+if [[ -s "$MY_OUTPUT_FILENAME".vcf ]] && [[ ! -s "$MY_OUTPUT_FILENAME".subsampled.vcf ]]; then
+	echo "output file(s): ${MY_OUTPUT_FILENAME}.vcf "
+fi
 echo ""
 
 ##########################################################################################
@@ -334,7 +361,7 @@ echo ""
 ############ SCRIPT OPTIONS
 ## OPTION DEFAULTS ##
 MY_INPUT_FASTA=NULL
-MY_PART_RANGES=NULL
+MY_PART_RANGES_FILE=NULL
 MY_OUTPUT_FILENAME=NULL
 MY_SUBSAMPLE_SNPS_SWITCH=NULL
 MY_LOGFILE_SWITCH=NULL
@@ -406,7 +433,7 @@ USAGE="Usage: $(basename $0) [OPTION]...
 "
 
 if [[ "$1" == "-h" ]] || [[ "$1" == "-help" ]]; then
-	echo "$Usage"
+	echo "$USAGE"
 	exit
 fi
 
@@ -415,27 +442,95 @@ if [[ "$1" == "-V" ]] || [[ "$1" == "--version" ]]; then
 	exit
 fi
 
-############ PARSE THE OPTIONS
-while getopts 'i:r:o:s:l:p:' opt ; do
-  case $opt in
+############ CHECK ARGUMENTS
+	# echo "$@"; echo "$#"; echo "$1" 
+	# for i in "$@"; do
+	# 	echo "$i";
+	# done
+	# MY_ARGS="$(echo "$@" | perl -pe $'s/\ /\n/')"
+	# echo "$MY_ARGS"
 
-## FASTA2VCF options:
-    i) MY_INPUT_FASTA=$OPTARG ;;
-    r) MY_PART_RANGES=$OPTARG ;;
-    o) MY_OUTPUT_FILENAME=$OPTARG ;;
-    s) MY_SUBSAMPLE_SNPS_SWITCH=$OPTARG ;;
-    l) MY_LOGFILE_SWITCH=$OPTARG ;;
-    p) MY_OUTPUT_PHYLIP_SWITCH=$OPTARG ;;
 
-## Missing and illegal options:
-    :) printf "Missing argument for -%s\n" "$OPTARG" >&2
-       echo "$USAGE" >&2
-       exit 1 ;;
-   \?) printf "Illegal option: -%s\n" "$OPTARG" >&2
-       echo "$USAGE" >&2
-       exit 1 ;;
-  esac
-done
+############ CAPTURE ARGUMENTS, SEND TO FILE FOR PARSING
+	if [[ -s ./args.tmp ]]; then rm ./args.tmp ; fi ;
+	if [[ -s ./args.txt ]]; then rm ./args.txt ; fi ;
+
+	ALL_MY_ARGUMENTS="$(echo "$@")"
+	echo "$ALL_MY_ARGUMENTS" > ./args.txt
+	perl -p -i -e $'s/\-/\n\-/g' ./args.txt
+	#perl -p -i -e $'s/\ /\n/g' ./args.txt
+	#wc -l ./args.txt | perl -pe 's/\.\/args\.txt.*//g' | perl -pe 's/\ //g'
+
+
+############ MANUALLY PARSE THE OPTIONS FROM ARGS
+
+### SET OPTIONS TO DEFAULT VALUES, EXCEPT WHERE VALUES WERE READ IN FROM USER ARGS
+	if [[  "$(grep -h '\-i' ./args.txt | wc -l | perl -pe 's/\ //g')" = "0" ]]; then
+		MY_INPUT_FASTA=NULL ;
+	else 
+		MY_ARG="$(grep -h '\-i' ./args.txt | perl -pe 's/\-i//g' | perl -pe 's/\ //g')";
+		MY_INPUT_FASTA="$MY_ARG" ;
+	fi
+#
+	if [[  "$(grep -h '\-r' ./args.txt | wc -l | perl -pe 's/\ //g')" = "0" ]]; then
+		MY_PART_RANGES_FILE=NULL ;
+	else 
+		MY_ARG="$(grep -h '\-r' ./args.txt | perl -pe 's/\-r//g' | perl -pe 's/\ //g')";
+		MY_PART_RANGES_FILE="$MY_ARG" ;
+	fi
+#
+	if [[  "$(grep -h '\-o' ./args.txt | wc -l | perl -pe 's/\ //g')" = "0" ]]; then
+		MY_OUTPUT_FILENAME=NULL ;
+	else 
+		MY_ARG="$(grep -h '\-o' ./args.txt | perl -pe 's/\-o//g' | perl -pe 's/\ //g')";
+		MY_OUTPUT_FILENAME="$MY_ARG" ;
+	fi
+#
+	if [[  "$(grep -h '\-s' ./args.txt | wc -l | perl -pe 's/\ //g')" = "0" ]]; then
+		MY_SUBSAMPLE_SNPS_SWITCH=NULL ;
+	else 
+		MY_ARG="$(grep -h '\-s' ./args.txt | perl -pe 's/\-s//g' | perl -pe 's/\ //g')";
+		MY_SUBSAMPLE_SNPS_SWITCH="$MY_ARG" ;
+	fi
+#
+	if [[  "$(grep -h '\-l' ./args.txt | wc -l | perl -pe 's/\ //g')" = "0" ]]; then
+		MY_LOGFILE_SWITCH=NULL ;
+	else 
+		MY_ARG="$(grep -h '\-l' ./args.txt | perl -pe 's/\-l//g' | perl -pe 's/\ //g')";
+		MY_LOGFILE_SWITCH="$MY_ARG" ;
+	fi
+#
+	if [[  "$(grep -h '\-p' ./args.txt | wc -l | perl -pe 's/\ //g')" = "0" ]]; then
+		MY_OUTPUT_PHYLIP_SWITCH=NULL ;
+	else 
+		MY_ARG="$(grep -h '\-p' ./args.txt | perl -pe 's/\-p//g' | perl -pe 's/\ //g')";
+		MY_OUTPUT_PHYLIP_SWITCH="$MY_ARG" ;
+	fi
+#
+
+
+
+# ############ PARSE THE OPTIONS
+# while getopts 'i:r:o:s:l:p:' opt ; do
+#   case $opt in
+# 
+# ## FASTA2VCF options:
+#     i) MY_INPUT_FASTA=$OPTARG ;;
+#     r) MY_PART_RANGES_FILE=$OPTARG ;;
+#     o) MY_OUTPUT_FILENAME=$OPTARG ;;
+#     s) MY_SUBSAMPLE_SNPS_SWITCH=$OPTARG ;;
+#     l) MY_LOGFILE_SWITCH=$OPTARG ;;
+#     p) MY_OUTPUT_PHYLIP_SWITCH=$OPTARG ;;
+# 
+# ## Missing and illegal options:
+#     :) printf "Missing argument for -%s\n" "$OPTARG" >&2
+#        echo "$USAGE" >&2
+#        exit 1 ;;
+#    \?) printf "Illegal option: -%s\n" "$OPTARG" >&2
+#        echo "$USAGE" >&2
+#        exit 1 ;;
+#   esac
+# done
 
 
 # ############# ############# #############
diff --git a/bin/concatenateSeqs b/bin/concatenateSeqs
--- a/bin/concatenateSeqs
+++ b/bin/concatenateSeqs
@@ -6,10 +6,10 @@
 # |                                                                                      #
 #                                                                                        #
 # File: concatenateSeqs.sh                                                               #
-  VERSION="v1.0.0"                                                                       #
+  VERSION="v1.2.0"                                                                       #
 # Author: Justin C. Bagley                                                               #
 # Date: Created by Justin Bagley on Tue, Mar 12 21:23:30 CDT 2019.                       #
-# Last update: March 15, 2019                                                            #
+# Last update: April 10, 2019                                                            #
 # Copyright (c) 2019 Justin C. Bagley. All rights reserved.                              #
 # Please report bugs to <bagleyj@umsl.edu>.                                              #
 #                                                                                        #
@@ -57,7 +57,7 @@ fi
 # trapCleanup Function
 # -----------------------------------
 # Any actions that should be taken if the script is prematurely
-# exited.  Always call this function at the top of your script.
+# exited. Always make this function at the top of your script.
 # -----------------------------------
 trapCleanup () {
   echo ""
@@ -136,13 +136,18 @@ concatenateSeqs () {
 ##########################################################################################
 
 echo "INFO      | $(date) |----------------------------------------------------------------"
-echo "INFO      | $(date) | concatenateSeqs, v1.0.0 March 2019  (in PIrANHA v0.2-alpha.2) "
+echo "INFO      | $(date) | concatenateSeqs, v1.2.0 April 2019  (in PIrANHA v0.2-alpha.2)  "
 echo "INFO      | $(date) | Copyright (c) 2019 Justin C. Bagley. All rights reserved.      "
 echo "INFO      | $(date) |----------------------------------------------------------------"
 
 ######################################## START ###########################################
 if [[ "$MY_VERBOSE_OUT_SWITCH" != "0" ]]; then
 	echo "INFO      | $(date) | Starting concatenateSeqs analysis... "
+	echo "INFO      | $(date) |          Running with the following options: "
+	echo "INFO      | $(date) |          - Taxon names and spaces file, <taxonNamesSpaces> = ${USER_SPEC_NAMSPACES_FILE} "
+	echo "INFO      | $(date) |          - <outputFile> option = ${MY_OUTPUT_FILE_SWITCH} "
+	echo "INFO      | $(date) |          - Verbose output switch, <verbose> = ${MY_VERBOSE_OUT_SWITCH} "
+
 	echo "INFO      | $(date) | Step #1: Set up workspace, check machine type, and determine output file settings. "
 fi
 ############ SET WORKING DIRECTORY AND CHECK MACHINE TYPE
@@ -188,6 +193,7 @@ count=1
  		j="$i".tmp ;
  		MY_PHYLIP_NCHAR="$(head -n1 $i | perl -pe 's/^[0-9]*\ +//g; s/\ //g')" ;
  		echo "###----------   $i,  $MY_PHYLIP_NCHAR bp   ----------###"
+		echo "$USER_SPEC_NAMSPACES_FILE"
 
 		## On first loop iteration, make concatenated seqs PHYLIP file from complete locus1 
 		## PHYLIP file, then make partitions/charsets files. Specifically, when you make the
@@ -199,6 +205,8 @@ count=1
 
 		if [[ "$count" = "1" ]]; then
 
+			#echo "$count"
+
 			# Make concatenated seqs file from complete locus1 PHYLIP file, and move original
 			# locus1 PHYLIP file to orig_phylip/ subfolder.
 			mkdir orig_phylip/ ;
@@ -207,10 +215,12 @@ count=1
 
 		elif [[ "$count" -gt "1" ]]; then
 
+			#echo "$count"
+
 			# Concatenate $i > 1 PHYLIP sequences to concatenated seqs PHYLIP file
 			while read l; do
 				MY_TAXON_NAME="$(echo $l | sed 's/\ //g')" ;
-				MY_1ST_INST_LINE="$(grep -n "$MY_TAXON_NAME" "$i" | head -n1 | sed 's/\:.*//g; s/\ //g' | perl -pe 's/\t//g')"	 ;			
+				MY_1ST_INST_LINE="$(grep -n "$MY_TAXON_NAME" $i | head -n1 | sed 's/\:.*//g; s/\ //g' | perl -pe 's/\t//g')" ;			
 					# extract/copy corresponding sequence from $i and paste it to end of
 					# line with same name ($MY_TAXON_NAME) in tmp file $j:
 					MY_SEQUENCE="$(grep -h "$MY_TAXON_NAME" $i | perl -pe 's/^[A-Za-z0-9\-\_\ ]*\ //g' | sed 's/\ //g')" ;
@@ -257,11 +267,13 @@ fi
 ############ CLEAN UP WORKING DIR BY DELETING TEMPORARY FILES.
 	
 	rm ./*.tmp ;
+	rm ./args.txt ;	## Remove arguments file generated when parsing the options:
 
 echo "----------------------------------------------------------------------------------------------------------"
-if [[ "$MY_VERBOSE_OUT_SWITCH" != "0" ]]; then
-	echo "output file(s): ./concatenated_seqs.phy "
-fi
+echo "output file(s): ./concatenated_seqs.phy "
+#if [[ "$MY_VERBOSE_OUT_SWITCH" != "0" ]]; then
+#	echo "output file(s): ./concatenated_seqs.phy "
+#fi
 echo ""
 
 ##########################################################################################
@@ -270,11 +282,6 @@ echo ""
 }
 
 
-
-############ SCRIPT OPTIONS
-USER_SPEC_NAMSPACES_FILE=NULL
-MY_OUTPUT_FILE_SWITCH=NULL
-MY_VERBOSE_OUT_SWITCH=0
 
 ############ CREATE USAGE & HELP TEXTS
 USAGE="Usage: $(basename $0) [OPTION]...
@@ -330,16 +337,87 @@ if [[ "$1" == "-h" ]] || [[ "$1" == "-help" ]]; then
 	exit
 fi
 
-# Saves all script output to file named 'output.txt'
-exec >> ./output.txt 
-exec 2>&1
-
-############ Check for mandatory positional parameters
-if [ $# -lt 2 ]; then
-	echo "WARNING!  | $(date) |          Missing one or more mandatory positional parameters. Quitting... "
-	echo "$USAGE"
-  exit 1
+if [[ "$1" == "-V" ]] || [[ "$1" == "--version" ]]; then
+	echo "$(basename $0) $VERSION";
+	exit
 fi
-USER_SPEC_NAMSPACES_FILE="$1"
-USER_SPEC_PATH="$2"
 
+############ CHECK ARGUMENTS
+	# echo "$@"; echo "$#"; echo "$1" 
+	# for i in "$@"; do
+	# 	echo "$i";
+	# done
+	# MY_ARGS="$(echo "$@" | perl -pe $'s/\ /\n/')"
+	# echo "$MY_ARGS"
+
+
+############ CAPTURE ARGUMENTS, SEND TO FILE FOR PARSING
+	if [[ -s ./args.tmp ]]; then rm ./args.tmp ; fi ;
+	if [[ -s ./args.txt ]]; then rm ./args.txt ; fi ;
+
+	ALL_MY_ARGUMENTS="$(echo "$@")"
+	echo "$ALL_MY_ARGUMENTS" > ./args.txt
+	perl -p -i -e $'s/\ /\n/g' ./args.txt
+	#wc -l ./args.txt | perl -pe 's/\.\/args\.txt.*//g' | perl -pe 's/\ //g'
+
+
+############ MANUALLY PARSE THE OPTIONS FROM ARGS
+
+### SET OPTIONS TO DEFAULT VALUES, EXCEPT WHERE VALUES WERE READ IN FROM USER ARGS
+	if [[  "$(grep -h '\-t' ./args.txt | wc -l | perl -pe 's/\ //g')" = "0" ]]; then
+		USER_SPEC_NAMSPACES_FILE=NULL ;
+	else 
+		MY_ARG="$(grep -h '\-t' ./args.txt | perl -pe 's/\-t//g' | perl -pe 's/\ //g')";
+		USER_SPEC_NAMSPACES_FILE="$MY_ARG" ;
+	fi
+#
+	if [[  "$(grep -h '\-o' ./args.txt | wc -l | perl -pe 's/\ //g')" = "0" ]]; then
+		MY_OUTPUT_FILE_SWITCH=NULL ;
+	else 
+		MY_ARG="$(grep -h '\-o' ./args.txt | perl -pe 's/\-o//g' | perl -pe 's/\ //g')";
+		MY_OUTPUT_FILE_SWITCH="$MY_ARG" ;
+	fi
+#
+	if [[  "$(grep -h '\-v' ./args.txt | wc -l | perl -pe 's/\ //g')" = "0" ]]; then
+		MY_VERBOSE_OUT_SWITCH=0 ;
+	else 
+		MY_ARG="$(grep -h '\-v' ./args.txt | perl -pe 's/\-v//g' | perl -pe 's/\ //g')";
+		MY_VERBOSE_OUT_SWITCH="$MY_ARG" ;
+	fi
+
+
+# ############# ############# #############
+# ##       TIME TO RUN THE SCRIPT        ##
+# ##                                     ##
+# ## You shouldn't need to edit anything ##
+# ## beneath this line                   ##
+# ##                                     ##
+# ############# ############# #############
+
+# Trap bad exits with your cleanup function
+trap trapCleanup EXIT INT TERM
+
+# Set IFS to preferred implementation
+IFS=$'\n\t'
+
+# Exit on error. Append '||true' when you run the script if you expect an error.
+set -o errexit
+
+# Run in debug mode, if set
+if ${debug}; then set -x ; fi
+
+# Exit on empty variable
+if ${strict}; then set -o nounset ; fi
+
+# Bash will remember & return the highest exitcode in a chain of pipes.
+# This way you can catch the error in case mysqldump fails in `mysqldump |gzip`, for example.
+set -o pipefail
+
+# Invoke the checkDependenices function to test for Bash packages.  Uncomment if needed.
+# checkDependencies
+
+# Run the script
+concatenateSeqs
+
+# Exit cleanly
+safeExit
diff --git a/bin/renameTaxa b/bin/renameTaxa
--- a/bin/renameTaxa
+++ b/bin/renameTaxa
@@ -6,7 +6,7 @@
 # |                                                                                      #
 #                                                                                        #
 # File: renameTaxa.sh                                                                    #
-  VERSION="v1.0.0"                                                                       #
+  VERSION="v1.1.0"                                                                       #
 # Author: Justin C. Bagley                                                               #
 # Date: Created by Justin Bagley on Wed, Apr 10 08:43:01 CDT 2019.                       #
 # Last update: April 10, 2019                                                            #
@@ -57,7 +57,7 @@ fi
 # trapCleanup Function
 # -----------------------------------
 # Any actions that should be taken if the script is prematurely
-# exited.  Always call this function at the top of your script.
+# exited. Always make this function at the top of your script.
 # -----------------------------------
 trapCleanup () {
   echo ""
@@ -136,12 +136,21 @@ renameTaxa () {
 ##########################################################################################
 
 echo "INFO      | $(date) |----------------------------------------------------------------"
-echo "INFO      | $(date) | renameTaxa, v1.0.0 April 2019  (part of PIrANHA v0.2-alpha.2) "
+echo "INFO      | $(date) | renameTaxa, v1.1.0 April 2019  (part of PIrANHA v0.2-alpha.2) "
 echo "INFO      | $(date) | Copyright (c) 2019 Justin C. Bagley. All rights reserved.      "
 echo "INFO      | $(date) |----------------------------------------------------------------"
 
+#echo "INFO      | $(date) |          Logging output to default file named ./renameTaxa_output.txt ... "
+#	exec >> ./renameTaxa_output.txt ;
+#	exec 2>&1 ;
+
 ######################################## START ###########################################
 echo "INFO      | $(date) | Starting renameTaxa analysis... "
+echo "INFO      | $(date) |          Running with the following options: "
+echo "INFO      | $(date) |          - Original names file, <origNames> = ${MY_ORIG_NAMES_FILE} "
+echo "INFO      | $(date) |          - New names file, <newNames> = ${MY_NEW_NAMES_FILE} "
+echo "INFO      | $(date) |          - <fileType> option = ${MY_FILE_TYPE} "
+
 echo "INFO      | $(date) | Step #1: Set up workspace and check machine type. "
 ############ SET WORKING DIRECTORY AND CHECK MACHINE TYPE
 USER_SPEC_PATH="$(printf '%q\n' "$(pwd)")";
@@ -151,51 +160,58 @@ checkMachineType
 #echo "INFO      | $(date) |               Found machine type ${machine}. "
 
 
-echo "INFO      | $(date) |          Logging output to default file named ./renameTaxa_output.txt ... "
-	exec >> ./renameTaxa_output.txt ;
-	exec 2>&1 ;
-
-
 ############ CONVERT NAMES FILES TO SED FORMAT.
-echo "INFO      | $(date) | Step #2: Convert name lists $MY_ORIG_NAMES_FILE and $MY_NEW_NAMES_FILE to shell (stream editor) format. "
+echo "INFO      | $(date) | Step #2: Convert name lists ${MY_ORIG_NAMES_FILE} and ${MY_NEW_NAMES_FILE} to shell (stream editor) format. "
+				
+				if [[ -s ./orig_taxon_names.tmp ]]; then rm ./orig_taxon_names.tmp ; fi
+				if [[ -s ./new_taxon_names.tmp ]]; then rm ./new_taxon_names.tmp ; fi
+#
 				cp "$MY_ORIG_NAMES_FILE" ./orig_taxon_names.tmp ;
 				cp "$MY_NEW_NAMES_FILE" ./new_taxon_names.tmp   ;
 #				
 				if [[ "${machine}" = "Mac" ]]; then
+#					echo "1"
 					sed -i '' 's/\_/\\_/g' ./orig_taxon_names.tmp  ;
+#					echo "2"
 					sed -i '' 's/\_/\\_/g' ./new_taxon_names.tmp  ;
+#					echo "3"
 					sed -i '' 's/\./\\./g' ./orig_taxon_names.tmp  ;
+#					echo "4"
 					sed -i '' 's/\./\\./g' ./new_taxon_names.tmp  ;
 					
-					MY_ORIG_NAMES_W_SPACES_CHECK="$(grep -n '\ ' ./orig_taxon_names.tmp | wc -l | sed 's/\ .*//g' )";
-					if [[ "$MY_ORIG_NAMES_W_SPACES_CHECK" -gt "0" ]]; then 
-						echo "WARNING!  | $(date) |          Found taxon names with spaces, which is not allowed. Converting spaces to underscores... "
-						sed -i '' 's/\ /\\_/g' ./orig_taxon_names.tmp  ; 
-					fi
-					
-					MY_NEW_NAMES_W_SPACES_CHECK="$(grep -n '\ ' ./new_taxon_names.tmp | wc -l | sed 's/\ .*//g' )";
-					if [[ "$MY_NEW_NAMES_W_SPACES_CHECK" -gt "0" ]]; then 
-						echo "WARNING!  | $(date) |          Found taxon names with spaces, which is not allowed. Converting spaces to underscores... "
-						sed -i '' 's/\ /\\_/g' ./new_taxon_names.tmp  ; 
-					fi
+#					echo "5"
+#					MY_ORIG_NAMES_W_SPACES_CHECK="$(grep -n '\ ' ./orig_taxon_names.tmp | wc -l | perl -pe 's/\ .*//g' )";
+#					echo "6"
+#					echo "$MY_ORIG_NAMES_W_SPACES_CHECK"
+#					if [[ "$MY_ORIG_NAMES_W_SPACES_CHECK" -gt "0" ]]; then 
+#						echo "WARNING!  | $(date) |          Found taxon names with spaces, which is not allowed. Converting spaces to underscores... "
+#						sed -i '' 's/\ /\\_/g' ./orig_taxon_names.tmp  ; 
+#					fi
+#					
+#					MY_NEW_NAMES_W_SPACES_CHECK="$(grep -n '\ ' ./new_taxon_names.tmp | wc -l | sed 's/\ .*//g' )";
+#					if [[ "$MY_NEW_NAMES_W_SPACES_CHECK" -gt "0" ]]; then 
+#						echo "WARNING!  | $(date) |          Found taxon names with spaces, which is not allowed. Converting spaces to underscores... "
+#						sed -i '' 's/\ /\\_/g' ./new_taxon_names.tmp  ; 
+#					fi
 				fi
+#
 				if [[ "${machine}" = "Linux" ]]; then
 					sed -i 's/\_/\\_/g' ./orig_taxon_names.tmp  ;
 					sed -i 's/\_/\\_/g' ./new_taxon_names.tmp  ;
 					sed -i 's/\./\\./g' ./orig_taxon_names.tmp  ;
 					sed -i 's/\./\\./g' ./new_taxon_names.tmp  ;
 					
-					MY_ORIG_NAMES_W_SPACES_CHECK="$(grep -n '\ ' ./orig_taxon_names.tmp | wc -l | sed 's/\ .*//g' )";
-					if [[ "$MY_ORIG_NAMES_W_SPACES_CHECK" -gt "0" ]]; then 
-						echo "WARNING!  | $(date) |          Found taxon names with spaces, which is not allowed. Converting spaces to underscores... "
-						sed -i 's/\ /\\_/g' ./orig_taxon_names.tmp  ; 
-					fi
-					
-					MY_NEW_NAMES_W_SPACES_CHECK="$(grep -n '\ ' ./new_taxon_names.tmp | wc -l | sed 's/\ .*//g' )";
-					if [[ "$MY_NEW_NAMES_W_SPACES_CHECK" -gt "0" ]]; then 
-						echo "WARNING!  | $(date) |          Found taxon names with spaces, which is not allowed. Converting spaces to underscores... "
-						sed -i 's/\ /\\_/g' ./new_taxon_names.tmp  ; 
-					fi
+#					MY_ORIG_NAMES_W_SPACES_CHECK="$(grep -n '\ ' ./orig_taxon_names.tmp | wc -l | sed 's/\ .*//g' )";
+#					if [[ "$MY_ORIG_NAMES_W_SPACES_CHECK" -gt "0" ]]; then 
+#						echo "WARNING!  | $(date) |          Found taxon names with spaces, which is not allowed. Converting spaces to underscores... "
+#						sed -i 's/\ /\\_/g' ./orig_taxon_names.tmp  ; 
+#					fi
+#					
+#					MY_NEW_NAMES_W_SPACES_CHECK="$(grep -n '\ ' ./new_taxon_names.tmp | wc -l | sed 's/\ .*//g' )";
+#					if [[ "$MY_NEW_NAMES_W_SPACES_CHECK" -gt "0" ]]; then 
+#						echo "WARNING!  | $(date) |          Found taxon names with spaces, which is not allowed. Converting spaces to underscores... "
+#						sed -i 's/\ /\\_/g' ./new_taxon_names.tmp  ; 
+#					fi
 				fi			
 
 
@@ -233,7 +249,7 @@ echo "INFO      | $(date) | Step #3: Rename taxa (sample names) in PHYLIP multip
 echo "INFO      | $(date) | name lists ${MY_ORIG_NAMES_FILE} and ${MY_NEW_NAMES_FILE}. "
 #file_count=1
 (
-	for MY_PHYLIP in ./*.fas; do
+	for MY_PHYLIP in ./*.phy; do
 		echo "INFO      | $(date) |          ###------   $MY_PHYLIP   ------###"
 		name_count=1
 		while read orig_name; do
@@ -308,6 +324,13 @@ if [[ "$MY_FILE_TYPE" = "NULL" ]]; then
 	safeExit ;
 fi
 
+echo "INFO      | $(date) | Step #4: Clean up workspace by removing temporary files generated during run. "
+echo "INFO      | $(date) |          Deleting temporary files... "
+############ CLEAN UP WORKING DIR BY DELETING TEMPORARY FILES.
+	
+	rm ./*.tmp ;
+	rm ./args.txt ;	## Remove arguments file generated when parsing the options:
+
 
 echo "----------------------------------------------------------------------------------------------------------"
 echo ""
@@ -318,12 +341,6 @@ echo ""
 }
 
 
-
-############ SCRIPT OPTIONS
-## OPTION DEFAULTS ##
-MY_ORIG_NAMES_FILE=NULL
-MY_NEW_NAMES_FILE=NULL
-MY_FILE_TYPE=NULL
 
 ############ CREATE USAGE & HELP TEXTS
 USAGE="Usage: $(basename $0) [OPTION]...
@@ -346,7 +363,8 @@ USAGE="Usage: $(basename $0) [OPTION]...
  cause the program to attempt renaming taxa in all FASTA files in the current dir. The -o, 
  -n, and -f flags provide mandatory input for the program, and thus are all required arguments,
  passed within the PIrANHA --args flag (see usage below). By default, the program is designed 
- to run quietly, with stdout and stderr saved to an output file named 'renameTaxa_output.txt'.
+ to run with stdout and stderr saved to an output file named 'renameTaxa_output.txt' in the
+ current directory.
  	This program runs on UNIX-like and Linux systems using commonly distributed utility 
  software, with usage obtained by running the script with the -h flag. It has been tested
  on macOS High Sierra (v10.13+) and Mojave but should work on many earlier versions or
@@ -384,22 +402,68 @@ if [[ "$1" == "-V" ]] || [[ "$1" == "--version" ]]; then
 	exit
 fi
 
-############ PARSE THE OPTIONS
-while getopts 'o:n:f:' opt ; do
-  case $opt in
-## renameTaxa options:
-    o) MY_ORIG_NAMES_FILE=$OPTARG ;;
-    n) MY_NEW_NAMES_FILE=$OPTARG ;;
-    f) MY_FILE_TYPE=$OPTARG ;;
-## Missing and illegal options:
-    :) printf "Missing argument for -%s\n" "$OPTARG" >&2
-       echo "$USAGE" >&2
-       exit 1 ;;
-   \?) printf "Illegal option: -%s\n" "$OPTARG" >&2
-       echo "$USAGE" >&2
-       exit 1 ;;
-  esac
-done
+
+############ CHECK ARGUMENTS
+	# echo "$@"; echo "$#"; echo "$1" 
+	# for i in "$@"; do
+	# 	echo "$i";
+	# done
+	# MY_ARGS="$(echo "$@" | perl -pe $'s/\ /\n/')"
+	# echo "$MY_ARGS"
+
+
+############ CAPTURE ARGUMENTS, SEND TO FILE FOR PARSING
+	if [[ -s ./args.tmp ]]; then rm ./args.tmp ; fi ;
+	if [[ -s ./args.txt ]]; then rm ./args.txt ; fi ;
+
+	ALL_MY_ARGUMENTS="$(echo "$@")"
+	echo "$ALL_MY_ARGUMENTS" > ./args.txt
+	perl -p -i -e $'s/\-/\n\-/g' ./args.txt
+	#wc -l ./args.txt | perl -pe 's/\.\/args\.txt.*//g' | perl -pe 's/\ //g'
+
+
+############ MANUALLY PARSE THE OPTIONS FROM ARGS
+
+### SET OPTIONS TO DEFAULT VALUES, EXCEPT WHERE VALUES WERE READ IN FROM USER ARGS
+	if [[  "$(grep -h '\-o' ./args.txt | wc -l | perl -pe 's/\ //g')" = "0" ]]; then
+		MY_ORIG_NAMES_FILE=NULL ;
+	else 
+		MY_ARG="$(grep -h '\-o' ./args.txt | perl -pe 's/\-o//g' | perl -pe 's/\ //g')";
+		MY_ORIG_NAMES_FILE="$MY_ARG" ;
+	fi
+#
+	if [[  "$(grep -h '\-n' ./args.txt | wc -l | perl -pe 's/\ //g')" = "0" ]]; then
+		MY_NEW_NAMES_FILE=NULL ;
+	else 
+		MY_ARG="$(grep -h '\-n' ./args.txt | perl -pe 's/\-n//g' | perl -pe 's/\ //g')";
+		MY_NEW_NAMES_FILE="$MY_ARG" ;
+	fi
+#
+	if [[  "$(grep -h '\-f' ./args.txt | wc -l | perl -pe 's/\ //g')" = "0" ]]; then
+		MY_FILE_TYPE=NULL ;
+	else 
+		MY_ARG="$(grep -h '\-f' ./args.txt | perl -pe 's/\-f//g' | perl -pe 's/\ //g')";
+		MY_FILE_TYPE="$MY_ARG" ;
+	fi
+
+
+# ############ PARSE THE OPTIONS
+# #while getopts 'o:n:f:' opt ; do
+# while getopts 'o:n:f:' opt ; do
+#   case $opt in
+# ## renameTaxa options:
+#     o) MY_ORIG_NAMES_FILE=$OPTARG ;;
+#     n) MY_NEW_NAMES_FILE=$OPTARG ;;
+#     f) MY_FILE_TYPE=$OPTARG ;;
+# ## Missing and illegal options:
+#     :) printf "Missing argument for -%s\n" "$OPTARG" >&2
+#        echo "$USAGE" >&2
+#        exit 1 ;;
+#    \?) printf "Illegal option: -%s\n" "$OPTARG" >&2
+#        echo "$USAGE" >&2
+#        exit 1 ;;
+#   esac
+# done
 
 
 # ############# ############# #############
