Add files via upload

diff --git a/bin/BEASTRunner b/bin/BEASTRunner
--- a/bin/BEASTRunner
+++ b/bin/BEASTRunner
@@ -6,10 +6,10 @@
 # |                                                                                      #
 #                                                                                        #
 # File: BEASTRunner.sh                                                                   #
-  VERSION="v1.2.1"                                                                       #
+  VERSION="v1.4.0"                                                                       #
 # Author: Justin C. Bagley                                                               #
 # Date: Created by Justin Bagley on Fri, 11 Nov 2016 14:33:51 -0600.                     #
-# Last update: March 6, 2019                                                             #
+# Last update: March 13, 2019                                                            #
 # Copyright (c) 2016-2019 Justin C. Bagley. All rights reserved.                         #
 # Please report bugs to <bagleyj@umsl.edu>.                                              #
 #                                                                                        #
@@ -17,6 +17,141 @@
 # SHELL SCRIPT FOR AUTOMATING RUNNING BEAST ON A REMOTE SUPERCOMPUTING CLUSTER           #
 #                                                                                        #
 ##########################################################################################
+
+# Provide a variable with the location of this script.
+SCRIPT_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+
+# Source Scripting Utilities
+# -----------------------------------
+# These shared utilities provide many functions which are needed to provide
+# the functionality in this boilerplate. This script will fail if they can
+# not be found.
+# -----------------------------------
+
+UTILS_LOCATION="${SCRIPT_PATH}/../lib/utils.sh" # Update this path to find the utilities.
+
+if [[ -f "${UTILS_LOCATION}" ]]; then
+  source "${UTILS_LOCATION}"
+else
+  echo "Please find the file util.sh and add a reference to it in this script. Exiting..."
+  exit 1
+fi
+
+
+# Source shared functions and variables
+# -----------------------------------
+
+FUNCS_LOCATION="${SCRIPT_PATH}/../lib/sharedFunctions.sh" # Update this path to find the shared functions.
+VARS_LOCATION="${SCRIPT_PATH}/../lib/sharedVariables.sh" # Update this path to find the shared variables.
+
+if [[ -f "${FUNCS_LOCATION}" ]] && [[ -f "${VARS_LOCATION}" ]]; then
+  source "${FUNCS_LOCATION}" ;
+  source "${VARS_LOCATION}" ;
+else
+  echo "Please find the files sharedFunctions.sh and sharedVariables.sh and add references to them in this script. Exiting... "
+  exit 1
+fi
+
+
+# trapCleanup Function
+# -----------------------------------
+# Any actions that should be taken if the script is prematurely
+# exited.  Always call this function at the top of your script.
+# -----------------------------------
+function trapCleanup() {
+  echo ""
+  # Delete temp files, if any
+  if is_dir "${tmpDir}"; then
+    rm -r "${tmpDir}"
+  fi
+  die "Exit trapped. In function: '${FUNCNAME[*]}'"
+}
+
+# safeExit
+# -----------------------------------
+# Non destructive exit for when script exits naturally.
+# Usage: Add this function at the end of every script.
+# -----------------------------------
+function safeExit() {
+  # Delete temp files, if any
+  if is_dir "${tmpDir}"; then
+    rm -r "${tmpDir}"
+  fi
+  trap - INT TERM EXIT
+  exit
+}
+
+# Set Flags
+# -----------------------------------
+# Flags which can be overridden by user input.
+# Default values are below
+# -----------------------------------
+quiet=false
+printLog=false
+verbose=false
+force=false
+strict=false
+debug=false
+args=()
+
+# Set Temp Directory
+# -----------------------------------
+# Create temp directory with three random numbers and the process ID
+# in the name.  This directory is removed automatically at exit.
+# -----------------------------------
+tmpDir="/tmp/${SCRIPT_NAME}.$RANDOM.$RANDOM.$RANDOM.$$"
+(umask 077 && mkdir "${tmpDir}") || {
+  die "Could not create temporary directory! Exiting."
+}
+
+# Logging
+# -----------------------------------
+# Log is only used when the '-l' flag is set.
+#
+# To never save a logfile change variable to '/dev/null'
+# Save to Desktop use: $HOME/Desktop/${SCRIPT_BASENAME}.log
+# Save to standard user log location use: $HOME/Library/Logs/${SCRIPT_BASENAME}.log
+# -----------------------------------
+logFile="$HOME/Library/Logs/${SCRIPT_BASENAME}.log"
+
+# Check for Dependencies
+# -----------------------------------
+# Arrays containing package dependencies needed to execute this script.
+# The script will fail if dependencies are not installed.  For Mac users,
+# most dependencies can be installed automatically using the package
+# manager 'Homebrew'.  Mac applications will be installed using
+# Homebrew Casks. Ruby and gems via RVM.
+# -----------------------------------
+homebrewDependencies=()
+caskDependencies=()
+gemDependencies=()
+
+
+
+
+function BEASTRunner () {
+
+######################################## START ###########################################
+##########################################################################################
+
+echo "INFO      | $(date) |----------------------------------------------------------------"
+echo "INFO      | $(date) | BEASTRunner, v1.4.0 March 2019  (part of PIrANHA v1.0.0)       "
+echo "INFO      | $(date) | Copyright (c) 2016-2019 Justin C. Bagley. All rights reserved. "
+echo "INFO      | $(date) |----------------------------------------------------------------"
+
+######################################## START ###########################################
+echo "INFO      | $(date) | Starting BEASTRunner pipeline... "
+echo "INFO      | $(date) | Step #1: Set up workspace and check machine type. "
+############ SET WORKING DIRECTORY AND CHECK MACHINE TYPE
+USER_SPEC_PATH="$(printf '%q\n' "$(pwd)")";
+echoCDWorkingDir
+#echo "INFO      | $(date) |          Checking machine type... "
+checkMachineType
+#echo "INFO      | $(date) |               Found machine type ${machine}. "
+
+
+
+
 
 ############ SCRIPT OPTIONS
 ## OPTION DEFAULTS ##
@@ -398,11 +533,11 @@ echo "INFO      | $(date) |          Cleaning up: removing temporary files from 
 	rm ./batch_qsub_bottom.txt;
 	rm ./beastrunner_batch_qsub.sh;
 
-echo "INFO      | $(date) |          Bye.
-"
-#
-#
-#
-######################################### END ############################################
+#echo "INFO      | $(date) |          Bye.
+#"
 
-exit 0
+
+
+BEASTRunner
+
+
diff --git a/bin/BEAST_PSPrepper b/bin/BEAST_PSPrepper
--- a/bin/BEAST_PSPrepper
+++ b/bin/BEAST_PSPrepper
@@ -6,10 +6,10 @@
 # |                                                                                      #
 #                                                                                        #
 # File: BEAST_PSPrepper.sh                                                               #
-  VERSION="v0.1.2"                                                                       #
+  VERSION="v1.0.0"                                                                       #
 # Author: Justin C. Bagley                                                               #
 # Date: Created by Justin Bagley on Thu, 19 Jan 2017 10:24:47 -0600.                     #
-# Last update: March 6, 2019                                                             #
+# Last update: March 13, 2019                                                            #
 # Copyright (c) 2017-2019 Justin C. Bagley. All rights reserved.                         #
 # Please report bugs to <bagleyj@umsl.edu>.                                              #
 #                                                                                        #
@@ -19,135 +19,140 @@
 #                                                                                        #
 ##########################################################################################
 
-############ SCRIPT OPTIONS
-## OPTION DEFAULTS ##
-CHAIN_LENGTH=100000
-ALPHA_VALUE=0.3
-ROOT_DIR=/tmp
-BURN_IN_PERCENT=50
-PRE_BURN_IN=100000
-DELETE_OLDLOGS=true
-NUM_PS_STEPS=10
+# Provide a variable with the location of this script.
+SCRIPT_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 
-############ CREATE USAGE & HELP TEXTS
-Usage="Usage: $(basename $0) [Help: -h help] [Options: -l a r b p d n V --version] [stdin:] <inputXMLFile>
- ## Help:
-  -h   help text (also: -help) echo this help text and exit
+# Source Scripting Utilities
+# -----------------------------------
+# These shared utilities provide many functions which are needed to provide
+# the functionality in this boilerplate. This script will fail if they can
+# not be found.
+# -----------------------------------
 
- ## Options:
-  -l   chainLength (length of MCMC chin for each path sampling step; default=100000)
-  -a   alpha (shape parameter of the Beta distribution; default=0.3)
-  -r   rootdir (absolute path to root directory where files for each step will be kept; default=/tmp)
-  -b   burnInPercentage (percent of samples discarded as burnin; default=50, same as in BEAST)
-  -p   preBurnin (number of samples discarded from first step of analysis; default=100000)
-  -d   deleteOldLogs (logical variable specifying whether or not to delete previous logs that 
-       may be present in the rootdir)
-  -n   nrOfSteps (total number of path sampling steps for analysis)
-  -V   version (also: --version) echo version and exit
+UTILS_LOCATION="${SCRIPT_PATH}/../lib/utils.sh" # Update this path to find the utilities.
 
- OVERVIEW
- This script works by (STEP #1) setting up user options/input, and then (STEP #2) using a 
- function to go through the XML file or files (should be the only XMLs in working dir) and 
- edit them for path sampling. For downstream processing and queuing, XML files should end
- in 'run.xml' (e.g. 'ULN_PS100_run.xml').
-	The script expects as <inputXMLFile> one of the following: (i) one XML file, created and
- formatted for BEAST v2++ using BEAUti v2++ (e.g. latest release is v2.4.5), and present in
- the current working directory (pwd); or (ii) the code 'multiXML', which tells the script
- to use a loop to process multiple XML input files present in the current working directory. 
- Regarding other inputs/flags, the rootdir variable requires an absolute path, with opening 
- and closing forward slashes. If no rootdir is passed using the -r flag, then the user will
- be asked (yes/no) if the default '/tmp' path is acceptable. If no, then the user will be 
- prompted to provide a rootdir path on their local machine or supercomputing account, and 
- if nothing is provided then rootdir will be left at '/tmp'.
-	Option defaults for path sampling parameters may or may not be ideal for your purposes. 
- For example, many more than 10 steps will likely be required to obtain good path sampling
- results, especially for larger or more complex data files. The author has found that setting 
- chainLength to 1 million and setting the nrOfSteps parameter to 100 has produced good results 
- for a range of XMLs he uses in his research (e.g. Bagley et al. 2016). Also, by default, the 
- alpha parameter used to space out the path sampling steps is set to 0.3, a value that Xie 
- et al. (2011) found to be near optimal for simulated data and a phylogenetic example, and
- thus suggested was 'generally optimal'. However, recent papers have published analyses using
- alpha values as high as 0.4. The new -a flag lets the user change this value in the XMLs.
-
- CITATION
- Bagley, J.C. 2019. PIrANHA v0.1.7. GitHub repository, Available at: 
-	<https://github.com/justincbagley/PIrANHA>.
-
- REFERENCES
- Bagley JC, Matamoros W, McMahan C, Chakrabarty P, Johnson JB (2016) Phylogeography and 
- 	species delimitation in convict cichlids (Cichlidae: Amatitlania): implications for 
- 	taxonomy and Plio–Pleistocene evolutionary history in Central America. Biological Journal
-  	of the Linnean Society. Early View on BJLS website. doi: 10.1111/bij.12845.
-
- Xie W, Lewis PO, Fan Y, Kuo L, Chen MH. 2011. Improving marginal likelihood estimation for 
- 	Bayesian phylogenetic model selection. Systematic Biology 60: 150–160.
-
-Created by Justin Bagley on Thu, 19 Jan 2017 10:24:47 -0600.
-Copyright (c) 2017-2019 Justin C. Bagley. All rights reserved.
-"
-
-if [[ "$1" == "-h" ]] || [[ "$1" == "-help" ]]; then
-	echo "$Usage"
-	exit
-fi
-
-if [[ "$1" == "-V" ]] || [[ "$1" == "--version" ]]; then
-	echo "$(basename $0) $VERSION";
-	exit
-fi
-
-############ PARSE THE OPTIONS
-while getopts 'l:a:r:b:p:d:n:' opt ; do
-  case $opt in
-## Path sampling options:
-    l) CHAIN_LENGTH=$OPTARG ;;
-    a) ALPHA_VALUE=$OPTARG ;;
-    r) ROOT_DIR=$OPTARG ;;
-    b) BURN_IN_PERCENT=$OPTARG ;;
-    p) PRE_BURN_IN=$OPTARG ;;
-    d) DELETE_OLDLOGS=$OPTARG ;;
-    n) NUM_PS_STEPS=$OPTARG ;;
-## Missing and illegal options:
-    :) printf "Missing argument for -%s\n" "$OPTARG" >&2
-       echo "$Usage" >&2
-       exit 1 ;;
-   \?) printf "Illegal option: -%s\n" "$OPTARG" >&2
-       echo "$Usage" >&2
-       exit 1 ;;
-  esac
-done
-
-############ SKIP OVER THE PROCESSED OPTIONS
-shift $((OPTIND-1)) 
-# Check for mandatory positional parameters
-if [ $# -lt 1 ]; then
-echo "$Usage"
+if [[ -f "${UTILS_LOCATION}" ]]; then
+  source "${UTILS_LOCATION}"
+else
+  echo "Please find the file util.sh and add a reference to it in this script. Exiting..."
   exit 1
 fi
-USER_SPEC_PATH="$1"
 
 
-echo "
-##########################################################################################
-#                           BEAST_PSPrepper v0.1.2, March 2019                           #
-##########################################################################################
-"
+# Source shared functions and variables
+# -----------------------------------
+
+FUNCS_LOCATION="${SCRIPT_PATH}/../lib/sharedFunctions.sh" # Update this path to find the shared functions.
+VARS_LOCATION="${SCRIPT_PATH}/../lib/sharedVariables.sh" # Update this path to find the shared variables.
+
+if [[ -f "${FUNCS_LOCATION}" ]] && [[ -f "${VARS_LOCATION}" ]]; then
+  source "${FUNCS_LOCATION}" ;
+  source "${VARS_LOCATION}" ;
+else
+  echo "Please find the files sharedFunctions.sh and sharedVariables.sh and add references to them in this script. Exiting... "
+  exit 1
+fi
+
+
+# trapCleanup Function
+# -----------------------------------
+# Any actions that should be taken if the script is prematurely
+# exited.  Always call this function at the top of your script.
+# -----------------------------------
+function trapCleanup() {
+  echo ""
+  # Delete temp files, if any
+  if is_dir "${tmpDir}"; then
+    rm -r "${tmpDir}"
+  fi
+  die "Exit trapped. In function: '${FUNCNAME[*]}'"
+}
+
+# safeExit
+# -----------------------------------
+# Non destructive exit for when script exits naturally.
+# Usage: Add this function at the end of every script.
+# -----------------------------------
+function safeExit() {
+  # Delete temp files, if any
+  if is_dir "${tmpDir}"; then
+    rm -r "${tmpDir}"
+  fi
+  trap - INT TERM EXIT
+  exit
+}
+
+# Set Flags
+# -----------------------------------
+# Flags which can be overridden by user input.
+# Default values are below
+# -----------------------------------
+quiet=false
+printLog=false
+verbose=false
+force=false
+strict=false
+debug=false
+args=()
+
+# Set Temp Directory
+# -----------------------------------
+# Create temp directory with three random numbers and the process ID
+# in the name.  This directory is removed automatically at exit.
+# -----------------------------------
+tmpDir="/tmp/${SCRIPT_NAME}.$RANDOM.$RANDOM.$RANDOM.$$"
+(umask 077 && mkdir "${tmpDir}") || {
+  die "Could not create temporary directory! Exiting."
+}
+
+# Logging
+# -----------------------------------
+# Log is only used when the '-l' flag is set.
+#
+# To never save a logfile change variable to '/dev/null'
+# Save to Desktop use: $HOME/Desktop/${SCRIPT_BASENAME}.log
+# Save to standard user log location use: $HOME/Library/Logs/${SCRIPT_BASENAME}.log
+# -----------------------------------
+logFile="$HOME/Library/Logs/${SCRIPT_BASENAME}.log"
+
+# Check for Dependencies
+# -----------------------------------
+# Arrays containing package dependencies needed to execute this script.
+# The script will fail if dependencies are not installed.  For Mac users,
+# most dependencies can be installed automatically using the package
+# manager 'Homebrew'.  Mac applications will be installed using
+# Homebrew Casks. Ruby and gems via RVM.
+# -----------------------------------
+homebrewDependencies=()
+caskDependencies=()
+gemDependencies=()
+
+
+
+
+function BEAST_PSPrepper () {
+
 ######################################## START ###########################################
-echo "INFO      | $(date) | Starting BEAST_PSPrepper pipeline... "
-echo "INFO      | $(date) | STEP #1: SETUP. "
+##########################################################################################
 
-echo "INFO      | $(date) |          Setting user-specified path to: "
-echo "$USER_SPEC_PATH "	
+echo "INFO      | $(date) |----------------------------------------------------------------"
+echo "INFO      | $(date) | BEAST_PSPrepper, v1.0.0 March 2019  (part of PIrANHA v1.0.0)   "
+echo "INFO      | $(date) | Copyright (c) 2017-2019 Justin C. Bagley. All rights reserved. "
+echo "INFO      | $(date) |----------------------------------------------------------------"
 
-## Make input file, <inputXMLFile>, a mandatory parameter:
-	MY_INPUTXMLFILE_VAR="$1"
-## Prep useful stuff:
-	CR=$(printf '\r')
-	calc () {
-	   	bc -l <<< "$@"
-	}
+######################################## START ###########################################
+echo "INFO      | $(date) | Starting BEAST_PSPrepper analysis... "
+echo "INFO      | $(date) | Step #1: Set up workspace and check machine type. "
+############ SET WORKING DIRECTORY AND CHECK MACHINE TYPE
+USER_SPEC_PATH="$(printf '%q\n' "$(pwd)")";
+echoCDWorkingDir
+#echo "INFO      | $(date) |          Checking machine type... "
+checkMachineType
+#echo "INFO      | $(date) |               Found machine type ${machine}. "
 
-##--PRE-EMPTIVELY FIX issues with echoing shell text containing dollar signs and minus signs
+
+
+## PRE-EMPTIVELY FIX issues with echoing shell text containing dollar signs and minus signs
 ## (i.e. within the run element tmp file created in the editXMLFiles function below):
 	RUNELEM_DIR_VAR=$(echo "\$(dir)");
 	RUNELEM_CP_FLAG=$(echo "-cp");
@@ -187,7 +192,7 @@ echo "INFO      | $(date) | STEP #2: MAKE AND RUN FUNCTION TO EDIT XML FILES SO 
 	editXMLFiles () {
 	count=0
 
-	MY_XML_FILES=./*.xml;		## Assign multiple BEAST XML input file(s) in run directory to variable using extension with wildcard.
+	MY_XML_FILES=./*.xml ;		## Assign multiple BEAST XML input file(s) in run directory to variable using extension with wildcard.
 
 		(
 			for i in $MY_XML_FILES; do
@@ -226,7 +231,7 @@ java $RUNELEM_CP_FLAG $RUNELEM_JAVA_CLASS beast.app.beastapp.BeastMain $RUNELEM_
 		)
 }
 
-##--Don't forget to run the function!
+## Don't forget to run the function!
 editXMLFiles
 
 
@@ -271,7 +276,7 @@ java $RUNELEM_CP_FLAG $RUNELEM_JAVA_CLASS beast.app.beastapp.BeastMain $RUNELEM_
   
 }
 
-##--Don't forget to run the function!
+## Don't forget to run the function!
 editXMLFiles
 
 
@@ -282,12 +287,160 @@ editXMLFiles
 
 fi
 
-echo "INFO      | $(date) | Finished prepping XML files for path sampling analyses in BEAST PathSampler using BEAST_PSPrepper.sh!!"
-echo "INFO      | $(date) | Bye.
-"
-#
-#
-#
+#echo "INFO      | $(date) | Finished prepping XML files for path sampling analyses in BEAST PathSampler using BEAST_PSPrepper.sh!!"
+#echo "INFO      | $(date) | Bye.
+#"
+
+echo "----------------------------------------------------------------------------------------------------------"
+echo ""
+
+##########################################################################################
 ######################################### END ############################################
 
-exit 0
+}
+
+
+
+############ SCRIPT OPTIONS
+## OPTION DEFAULTS ##
+CHAIN_LENGTH=100000
+ALPHA_VALUE=0.3
+ROOT_DIR=/tmp
+BURN_IN_PERCENT=50
+PRE_BURN_IN=100000
+DELETE_OLDLOGS=true
+NUM_PS_STEPS=10
+
+############ CREATE USAGE & HELP TEXTS
+USAGE="Usage: $(basename $0) [OPTION]...
+
+ ${bold}Options:${reset}
+  -i   inputXMLFile (def: NULL) input XML file for BEAST
+  -l   chainLength (def: 100000) length of MCMC chin for each path sampling step
+  -a   alpha (shape parameter of the Beta distribution; default=0.3)
+  -r   rootdir (def: /tmp) absolute path to root directory where files for each step will be kept
+  -b   burnInPercentage (def: 50, same as in BEAST) percent of samples discarded as burnin
+  -p   preBurnin (def: 100000) number of samples discarded from first step of analysis
+  -d   deleteOldLogs (def: true) logical variable specifying whether or not to delete previous 
+       logs that may be present in the rootdir
+  -n   nrOfSteps (def: 10) total number of path sampling steps for analysis
+  -h   help text (also: -help) echo this help text and exit
+  -V   version (also: --version) echo version of this script and exit
+
+ OVERVIEW
+ This script works by (Step #1) setting up user options/input, and then (Step #2) using a 
+ function to go through the XML file or files (should be the only XMLs in working dir) and 
+ edit them for path sampling. For downstream processing and queuing, XML files should end
+ in 'run.xml' (e.g. 'ULN_PS100_run.xml').
+	The script expects as <inputXMLFile> one of the following: (i) one XML file, created and
+ formatted for BEAST v2++ using BEAUti v2++ (e.g. latest release is v2.4.5), and present in
+ the current working directory (pwd); or (ii) the code 'multiXML', which tells the script
+ to use a loop to process multiple XML input files present in the current working directory. 
+ Regarding other inputs/flags, the rootdir variable requires an absolute path, with opening 
+ and closing forward slashes. If no rootdir is passed using the -r flag, then the user will
+ be asked (yes/no) if the default '/tmp' path is acceptable. If no, then the user will be 
+ prompted to provide a rootdir path on their local machine or supercomputing account, and 
+ if nothing is provided then rootdir will be left at '/tmp'.
+	Option defaults for path sampling parameters may or may not be ideal for your purposes. 
+ For example, many more than 10 steps will likely be required to obtain good path sampling
+ results, especially for larger or more complex data files. The author has found that setting 
+ chainLength to 1 million and setting the nrOfSteps parameter to 100 has produced good results 
+ for a range of XMLs he uses in his research (e.g. Bagley et al. 2016). Also, by default, the 
+ alpha parameter used to space out the path sampling steps is set to 0.3, a value that Xie 
+ et al. (2011) found to be near optimal for simulated data and a phylogenetic example, and
+ thus suggested was 'generally optimal'. However, recent papers have published analyses using
+ alpha values as high as 0.4. The new -a flag lets the user change this value in the XMLs.
+
+ ${bold}Usage examples:${reset}
+ Call the program using PIrANHA, as follows:
+
+    piranha -f BEAST_PSPrepper
+    piranha -f BEAST_PSPrepper --args='-h'
+
+ ${bold}CITATION${reset}
+ Bagley, J.C. 2019. PIrANHA v1.0.0. GitHub repository, Available at:
+	<https://github.com/justincbagley/PIrANHA>.
+
+ ${bold}REFERENCES${reset}
+ Bagley, J.C., Matamoros, W., McMahan, C., Chakrabarty, P., Johnson, J.B. 2016. Phylogeography and 
+ 	species delimitation in convict cichlids (Cichlidae: Amatitlania): implications for 
+ 	taxonomy and Plio–Pleistocene evolutionary history in Central America. Biological Journal
+  	of the Linnean Society. Early View on BJLS website. doi: 10.1111/bij.12845.
+ Xie, W., Lewis, P.O., Fan, Y., Kuo, L., Chen, M.H. 2011. Improving marginal likelihood estimation for 
+ 	Bayesian phylogenetic model selection. Systematic Biology, 60, 150–160.
+
+ Created by Justin Bagley on Thu, 19 Jan 2017 10:24:47 -0600.
+ Copyright (c) 2017-2019 Justin C. Bagley. All rights reserved.
+"
+
+if [[ "$1" == "-h" ]] || [[ "$1" == "-help" ]]; then
+	echo "$USAGE"
+	exit
+fi
+
+if [[ "$1" == "-V" ]] || [[ "$1" == "--version" ]]; then
+	echo "$(basename $0) $VERSION";
+	exit
+fi
+
+############ PARSE THE OPTIONS
+while getopts 'i:l:a:r:b:p:d:n:' opt ; do
+  case $opt in
+## BEAST Path sampling options:
+    i) MY_INPUTXMLFILE_VAR=$OPTARG ;;
+    l) CHAIN_LENGTH=$OPTARG ;;
+    a) ALPHA_VALUE=$OPTARG ;;
+    r) ROOT_DIR=$OPTARG ;;
+    b) BURN_IN_PERCENT=$OPTARG ;;
+    p) PRE_BURN_IN=$OPTARG ;;
+    d) DELETE_OLDLOGS=$OPTARG ;;
+    n) NUM_PS_STEPS=$OPTARG ;;
+## Missing and illegal options:
+    :) printf "Missing argument for -%s\n" "$OPTARG" >&2
+       echo "$USAGE" >&2
+       exit 1 ;;
+   \?) printf "Illegal option: -%s\n" "$OPTARG" >&2
+       echo "$USAGE" >&2
+       exit 1 ;;
+  esac
+done
+
+# Store the remaining part as arguments.
+# args+=("$@")
+
+
+# ############# ############# #############
+# ##       TIME TO RUN THE SCRIPT        ##
+# ##                                     ##
+# ## You shouldn't need to edit anything ##
+# ## beneath this line                   ##
+# ##                                     ##
+# ############# ############# #############
+
+# Trap bad exits with your cleanup function
+trap trapCleanup EXIT INT TERM
+
+# Set IFS to preferred implementation
+IFS=$'\n\t'
+
+# Exit on error. Append '||true' when you run the script if you expect an error.
+set -o errexit
+
+# Run in debug mode, if set
+if ${debug}; then set -x ; fi
+
+# Exit on empty variable
+if ${strict}; then set -o nounset ; fi
+
+# Bash will remember & return the highest exitcode in a chain of pipes.
+# This way you can catch the error in case mysqldump fails in `mysqldump |gzip`, for example.
+set -o pipefail
+
+# Invoke the checkDependenices function to test for Bash packages.  Uncomment if needed.
+# checkDependencies
+
+# Run the script
+BEAST_PSPrepper
+
+# Exit cleanly
+safeExit
diff --git a/bin/completeConcatSeqs b/bin/completeConcatSeqs
--- a/bin/completeConcatSeqs
+++ b/bin/completeConcatSeqs
@@ -2,20 +2,22 @@
 
 ##########################################################################################
 #  __  o  __   __   __  |__   __                                                         #
-# |__) | |  ' (__( |  ) |  ) (__(                                                        #
+# |__) | |  ' (__( |  ) |  ) (__(                                                        # 
 # |                                                                                      #
 #                                                                                        #
-# File: concatenateSeqs.sh                                                               #
+# File: completeConcatSeqs.sh                                                            #
   VERSION="v1.0.0"                                                                       #
 # Author: Justin C. Bagley                                                               #
-# Date: Created by Justin Bagley on Tue, Mar 12 21:23:30 CDT 2019.                       #
-# Last update: March 13, 2019                                                            #
+# Date: Created by Justin Bagley on Tue, Mar 12 19:11:08 CDT 2019.                       #
+# Last update: March 12, 2019                                                            #
 # Copyright (c) 2019 Justin C. Bagley. All rights reserved.                              #
 # Please report bugs to <bagleyj@umsl.edu>.                                              #
 #                                                                                        #
 # Description:                                                                           #
-# SHELL SCRIPT THAT CONVERTS SERIES OF PHYLIP DNA SEQUENCE ALIGNMENTS WITH EQUAL TAXON   #
-# SAMPLING INTO A SINGLE CONCATENATED PHYLIP ALIGNMENT                                   #
+# SHELL SCRIPT THAT CONVERTS SERIES OF PHYLIP DNA SEQUENCE ALIGNMENTS (WITH OR WITHOUT   #
+# VARYING NUMBERS OF TAXA) INTO A SINGLE CONCATENATED PHYLIP ALIGNMENT WITH COMPLETE     #
+# TAXON SAMPLING; ALSO MAKES CHARACTER SUBSET/PARTITION FILES IN RAxML, PartitionFinder  #
+# AND NEXUS FORMATS FOR THE RESULTING ALIGNMENT                                          #
 #                                                                                        #
 ##########################################################################################
 
@@ -129,22 +131,19 @@ gemDependencies=()
 
 
 
-
-function concatenateSeqs () {
+function completeConcatSeqs () {
 
 ######################################## START ###########################################
 ##########################################################################################
 
 echo "INFO      | $(date) |----------------------------------------------------------------"
-echo "INFO      | $(date) | concatenateSeqs, v1.0.0 March 2019  (part of PIrANHA v1.0.0)   "
+echo "INFO      | $(date) | completeConcatSeqs, v1.0.0 March 2019  (part of PIrANHA v1.0.0)"
 echo "INFO      | $(date) | Copyright (c) 2019 Justin C. Bagley. All rights reserved.      "
 echo "INFO      | $(date) |----------------------------------------------------------------"
 
 ######################################## START ###########################################
-if [[ "$MY_VERBOSE_OUT_SWITCH" != "0" ]]; then
-	echo "INFO      | $(date) | Starting concatenateSeqs analysis... "
-	echo "INFO      | $(date) | Step #1: Set up workspace, check machine type, and determine output file settings. "
-fi
+echo "INFO      | $(date) | Starting completeConcatSeqs analysis... "
+echo "INFO      | $(date) | Step #1: Set up workspace and check machine type. "
 ############ SET WORKING DIRECTORY AND CHECK MACHINE TYPE
 USER_SPEC_PATH="$(printf '%q\n' "$(pwd)")";
 echoCDWorkingDir
@@ -164,30 +163,70 @@ if [[ "$MY_OUTPUT_FILE_SWITCH" != "NULL" ]]; then
 		echo "INFO      | $(date) |          Output file switch activated. Logging output to file at ./${MY_OUTPUT_FILE_SWITCH} ... "
 	fi
 elif [[ "$MY_OUTPUT_FILE_SWITCH" = "NULL" ]]; then
-	exec >> ./concatenateSeqs_output.txt ;
+	exec >> ./completeConcatSeqs_output.txt ;
 	exec 2>&1 ;
 #
 	if [[ "$MY_VERBOSE_OUT_SWITCH" != "0" ]]; then
-		echo "INFO      | $(date) |          Default output file settings. Logging output to file at ./concatenateSeqs_output.txt ... "
+		echo "INFO      | $(date) |          Default output file settings. Logging output to file at ./completeConcatSeqs_output.txt ... "
 	fi
 fi
 
 
 if [[ "$MY_VERBOSE_OUT_SWITCH" != "0" ]]; then
-	echo "INFO      | $(date) | Step #2: Run main concatenateSeqs analysis. "
+	echo "INFO      | $(date) | Step #3: Run completeConcatSeqs (including completeSeqs and concatenateSeqs routines) on PHYLIP alignments in current working dir. "
 fi
-
-
 count=1
 (
 	for i in ./*.phy; do
- 
-		######  concatenateSeqs  ######
 
- 		cp "$USER_SPEC_NAMSPACES_FILE" "$i".tmp ;
- 		j="$i".tmp ;
- 		MY_PHYLIP_NCHAR="$(head -n1 $i | perl -pe 's/^[0-9]*\ +//g; s/\ //g')" ;
- 		echo "###----------   $i,  $MY_PHYLIP_NCHAR bp   ----------###"
+		######  completeSeqs  ######
+
+		cp "$USER_SPEC_NAMSPACES_FILE" "$i".tmp ;
+		j="$i".tmp ;
+		MY_PHYLIP_NCHAR="$(head -n1 $i | perl -pe 's/^[0-9]*\ +//g; s/\ //g')" ;
+		echo "###----------   $i,  $MY_PHYLIP_NCHAR bp   ----------###" ;
+
+			while read k; do
+				MY_TAXON_NAME="$(echo $k | sed 's/\ //g')" ;
+				MY_N_IND_INSTS="$(grep -n "$MY_TAXON_NAME" "$i" | wc -l | perl -pe 's/\t//g; s/\ //g')" ;
+				MY_1ST_INST_LINE="$(grep -n "$MY_TAXON_NAME" "$i" | head -n1 | sed 's/\:.*//g; s/\ //g' | perl -pe 's/\t//g')" ;
+				
+				if [[ "$MY_N_IND_INSTS" = "1" ]]; then
+					# extract/copy corresponding sequence from $i and paste it to end of
+					# line with same name ($MY_TAXON_NAME) in tmp file $j:
+					MY_SEQUENCE="$(grep -h "$MY_TAXON_NAME" $i | perl -pe 's/^[A-Za-z0-9\-\_\ ]*\ //g' | sed 's/\ //g')" ;
+					if [[ "${machine}" = "Mac" ]]; then
+						sed -i '' 's/\(^'"$MY_TAXON_NAME"'[\ ]*\)/\1'"$MY_SEQUENCE"'/g' "$j" ;
+					fi
+
+					if [[ "${machine}" = "Linux" ]]; then
+						sed -i 's/\(^'"$MY_TAXON_NAME"'[\ ]*\)/\1'"$MY_SEQUENCE"'/g' "$j" ;
+					fi
+
+					
+				elif [[ "$MY_N_IND_INSTS" = "0" ]]; then
+					# only add correct # N's (dummy sequence) to end of line with same
+					# name in tmp file $j:
+					if [[ "${machine}" = "Mac" ]]; then
+						sed -i '' 's/\(^'"$MY_TAXON_NAME"'[\ ]*\)/\1'"$(printf 'N%.0s' {$(seq 1 $MY_PHYLIP_NCHAR)})"'/g' "$j" ;
+					fi
+
+					if [[ "${machine}" = "Linux" ]]; then
+						sed -i 's/\(^'"$MY_TAXON_NAME"'[\ ]*\)/\1'"$(printf 'N%.0s' {$(seq 1 $MY_PHYLIP_NCHAR)})"'/g' "$j" ;
+					fi
+
+				fi				
+				
+			done < "$USER_SPEC_NAMSPACES_FILE"
+
+		# Add header with corrected ntax and nchar information:
+		MY_PHY_NTAX="$(awk 'END {print NR,"lines"}' $j | sed 's/\ .*//g')" ;
+		echo "$MY_PHY_NTAX  $MY_PHYLIP_NCHAR" > ./header.tmp ;
+		# Overwrite original phy file with new phy file:
+		cat ./header.tmp "$j" > "$i" ;
+
+
+		######  concatenateSeqs  ######
 
 		## On first loop iteration, make concatenated seqs PHYLIP file from complete locus1 
 		## PHYLIP file, then make partitions/charsets files. Specifically, when you make the
@@ -205,23 +244,47 @@ count=1
 			cp "$i" ./concatenated_seqs.phy ;
 			cp "$i" ./orig_phylip/ ;
 
+			# Make partitions/charsets files with information from locus1...
+			#locus="$(echo $i | perl -pe 's/\.\///g; s/\.[A-Za-z]{3,}$//g')"
+			locus="$(basename $i '.phy')" ;
+			echo "DNA, ${locus} = 1-${MY_PHYLIP_NCHAR}" >> ./raxml_partitions.part ;
+			echo "${locus}=1-${MY_PHYLIP_NCHAR};" >> partitionfinder_subsets.txt ;
+			echo "  charset ${locus} = 1-${MY_PHYLIP_NCHAR};" >> NEXUS_charsets_lowercase.txt ;
+			echo "  CHARSET ${locus} = 1-${MY_PHYLIP_NCHAR};" >> NEXUS_charsets_uppercase.txt ;
+
+			MY_PREV_END_RANGE_VAL="$(echo $MY_PHYLIP_NCHAR)" ;
+
 		elif [[ "$count" -gt "1" ]]; then
 
 			# Concatenate $i > 1 PHYLIP sequences to concatenated seqs PHYLIP file
-			while read l; do
-				MY_TAXON_NAME="$(echo $l | sed 's/\ //g')" ;
-				MY_1ST_INST_LINE="$(grep -n "$MY_TAXON_NAME" "$i" | head -n1 | sed 's/\:.*//g; s/\ //g' | perl -pe 's/\t//g')"	 ;			
-					# extract/copy corresponding sequence from $i and paste it to end of
-					# line with same name ($MY_TAXON_NAME) in tmp file $j:
-					MY_SEQUENCE="$(grep -h "$MY_TAXON_NAME" $i | perl -pe 's/^[A-Za-z0-9\-\_\ ]*\ //g' | sed 's/\ //g')" ;
-					if [[ "${machine}" = "Mac" ]]; then
-						sed -i '' '/^'"$MY_TAXON_NAME"'/s/$/'"$MY_SEQUENCE"'/' ./concatenated_seqs.phy ;
-					fi
+			(
+				while read l; do
+					MY_TAXON_NAME="$(echo $l | sed 's/\ //g')" ;
+					MY_1ST_INST_LINE="$(grep -n "$MY_TAXON_NAME" "$i" | head -n1 | sed 's/\:.*//g; s/\ //g' | perl -pe 's/\t//g')" ;				
+						# extract/copy corresponding sequence from $i and paste it to end of
+						# line with same name ($MY_TAXON_NAME) in tmp file $j:
+						MY_SEQUENCE="$(grep -h "$MY_TAXON_NAME" $i | perl -pe 's/^[A-Za-z0-9\-\_\ ]*\ //g' | sed 's/\ //g')" ;
+						if [[ "${machine}" = "Mac" ]]; then
+							sed -i '' '/^'"$MY_TAXON_NAME"'/s/$/'"$MY_SEQUENCE"'/' ./concatenated_seqs.phy ;
+						fi
+	
+						if [[ "${machine}" = "Linux" ]]; then
+							sed -i '/^'"$MY_TAXON_NAME"'/s/$/'"$MY_SEQUENCE"'/' ./concatenated_seqs.phy ;
+						fi
+	
+				done < "$USER_SPEC_NAMSPACES_FILE"
+			)
+			# Add ith locus information to partitions/charsets files...
+			locus="$(basename $i '.phy')" ;
+			#MY_PREV_NCHAR="$(cat ./previous_nchar.tmp)" ;
+			MY_NEW_START_RANGE_VAL="$(calc $MY_PREV_END_RANGE_VAL + 1)" ;
+			MY_NEW_END_RANGE_VAL="$(calc $MY_PREV_END_RANGE_VAL + $MY_PHYLIP_NCHAR)" ;
+			echo "DNA, ${locus} = $MY_NEW_START_RANGE_VAL-${MY_NEW_END_RANGE_VAL}" >> ./raxml_partitions.part ;
+			echo "${locus}=$MY_NEW_START_RANGE_VAL-${MY_NEW_END_RANGE_VAL};" >> partitionfinder_subsets.txt ;
+			echo "  charset ${locus} = $MY_NEW_START_RANGE_VAL-${MY_NEW_END_RANGE_VAL};" >> NEXUS_charsets_lowercase.txt ;
+			echo "  CHARSET ${locus} = $MY_NEW_START_RANGE_VAL-${MY_NEW_END_RANGE_VAL};" >> NEXUS_charsets_uppercase.txt ;
 
-					if [[ "${machine}" = "Linux" ]]; then
-						sed -i '/^'"$MY_TAXON_NAME"'/s/$/'"$MY_SEQUENCE"'/' ./concatenated_seqs.phy ;
-					fi
-			done < "$USER_SPEC_NAMSPACES_FILE"
+			MY_PREV_END_RANGE_VAL="$(echo $MY_NEW_END_RANGE_VAL)" ;
 
 			cp "$i" ./orig_phylip/ ;
 
@@ -233,8 +296,6 @@ count=1
 		
 	done
 )
-
-
 
 
 ###### FIX NEW CONCATENATED PHYLIP ALIGNMENT TO HAVE THE CORRECT NCHAR INFORMATION
@@ -249,9 +310,8 @@ count=1
 		cat ./concat_header.tmp ./concatenated_seqs.tmp > ./concatenated_seqs.phy ;
 
 
-
 if [[ "$MY_VERBOSE_OUT_SWITCH" != "0" ]]; then
-	echo "INFO      | $(date) | Step #3: Clean up workspace by removing temporary files generated during run. "
+	echo "INFO      | $(date) | Step #4: Clean up workspace by removing temporary files generated during run. "
 	echo "INFO      | $(date) |          Deleting temporary files... "
 fi
 ############ CLEAN UP WORKING DIR BY DELETING TEMPORARY FILES.
@@ -259,6 +319,7 @@ fi
 	rm ./*.tmp ;
 
 echo "----------------------------------------------------------------------------------------------------------"
+
 if [[ "$MY_VERBOSE_OUT_SWITCH" != "0" ]]; then
 	echo "output file(s): ./concatenated_seqs.phy "
 fi
@@ -290,56 +351,89 @@ USAGE="Usage: $(basename $0) [OPTION]...
 
  ${bold}OVERVIEW${reset}
  THIS SCRIPT runs in a working directory containing a series of PHYLIP (Felsenstein 2002)
- DNA sequence alignments for different genes (e.g. 100s or 1000s of RAD or UCE loci) each
- having the same number of taxa, or taxon sampling. Given such a workspace, the script 
- takes as input a 'names and spaces file', <inputNameSpacesFile>, containing the names of
- tip taxa, one per line, as well as spaces extending the total number of characters to be
- the same on each line (e.g. 10 or 12 characters including spaces), passed using the -t
- flag. When run, the script concatenates the PHYLIP alignments together. The ordering of 
- the gene alignments is equal to the alphanumeric order in which bash or UNIX terminal would 
- read the PHYLIP files (e.g. locus1.phy, locus10.phy, ..., and not locus1.phy, locus2.phy, 
- ...). 
-	By default all script output is written to a file named 'concatenateSeqs_output.txt'. 
- The user may optionally specify verbose output (-v 1) or a desired output file name (using
- the -o flag).Taxon names in the PHYLIP files should contain only alphanumeric characters and 
- no spaces, or else there could be issues. Also, PHYLIP alignment files must have the extension 
- '.phy'.
+ DNA sequence alignments for different genes (e.g. 100s or 1000s of RAD or UCE loci) with 
+ varying levels of taxon sampling (completeness), such that out of the total number of tip 
+ taxa, some were sequenced for gene A, and possibly the same or a varying number of tip 
+ taxa were sequenced for gene B, and so on. Given such a workspace, this script takes as 
+ input a 'names and spaces file', <taxonNamesSpaces>, containing the names of tip taxa,
+ one per line, as well as spaces extending the total number of characters to be the same
+ on each line (e.g. 10 or 12 characters including spaces), passed using the -t flag. The 
+ script (1) converts the PHYLIP alignments into 'complete' alignments, each containing the 
+ full number of tip taxa, by filling in missing taxa with dummy sequences comprised entirely 
+ of missing data (coded as NNNs) in the alignment, and (2) concatenates all of the alignments 
+ into a single PHYLIP alignment named 'concatenated_seqs.phy'.
+	When calling the program, <taxonNamesSpaces> is a mandatory option, PHYLIP alignment 
+ files in working dir are overwritten with 'complete' alignments, and by default all script 
+ output is written to a file named 'completeConcatSeqs_output.txt'. The user may optionally 
+ specify verbose output (-v 1) or an output file name (-o flag). Taxon names in the PHYLIP 
+ files should contain only alphanumeric characters and no spaces, or else there could be 
+ issues. Also, PHYLIP alignment files must have the extension '.phy'.
 	This program runs on UNIX-like and Linux systems using commonly distributed utility 
  software, with usage obtained by running the script with the -h flag. It has been tested
  on macOS High Sierra (v10.13+) and Mojave but should work on many earlier versions or
  Linux (tested on CentOS 6/7). Besides standard UNIX/Linux command line tools, the only other 
  dependency is Perl (v5+), which is usually already installed on mac and Linux distributions.
 
+
  ${bold}Usage examples:${reset}
  To run in current directory with a names and spaces file named 'taxon_name_spaces12.txt' 
  containing each tip taxon name followed by x spaces taking the total character count per 
- line out to 12 characters, you would call the program using PIrANHA, as follows:
+ line out to 12 characters, with verbose output, you would call the program using PIrANHA, 
+ as follows:
 
-    piranha -f concatenateSeqs --args='-t taxon_name_spaces12.txt'
+    piranha -f completeConcatSeqs --args='-t taxon_name_spaces12.txt -v 1'
 
  ${bold}CITATION${reset}
  Bagley, J.C. 2019. PIrANHA v1.0.0. GitHub repository, Available at:
 	<https://github.com/justincbagley/PIrANHA>.
 
- Created by Justin Bagley on Tue, Mar 12 21:23:30 CDT 2019.
+ Created by Justin Bagley on Tue, Mar 12 19:11:08 CDT 2019.
  Copyright (c) 2019 Justin C. Bagley. All rights reserved.
 "
 
 if [[ "$1" == "-h" ]] || [[ "$1" == "-help" ]]; then
 	echo "$USAGE"
-	exit
+	exit ;
 fi
 
-# Saves all script output to file named 'output.txt'
-exec >> ./output.txt 
-exec 2>&1
-
-############ Check for mandatory positional parameters
-if [ $# -lt 2 ]; then
-	echo "WARNING!  | $(date) |          Missing one or more mandatory positional parameters. Quitting... "
-	echo "$USAGE"
-  exit 1
+if [[ "$1" == "-V" ]] || [[ "$1" == "--version" ]]; then
+	echo "$(basename $0) $VERSION"
+	exit ;
 fi
-USER_SPEC_NAMSPACES_FILE="$1"
-USER_SPEC_PATH="$2"
 
+
+# ############# ############# #############
+# ##       TIME TO RUN THE SCRIPT        ##
+# ##                                     ##
+# ## You shouldn't need to edit anything ##
+# ## beneath this line                   ##
+# ##                                     ##
+# ############# ############# #############
+
+# Trap bad exits with your cleanup function
+trap trapCleanup EXIT INT TERM
+
+# Set IFS to preferred implementation
+IFS=$'\n\t'
+
+# Exit on error. Append '||true' when you run the script if you expect an error.
+set -o errexit
+
+# Run in debug mode, if set
+if ${debug}; then set -x ; fi
+
+# Exit on empty variable
+if ${strict}; then set -o nounset ; fi
+
+# Bash will remember & return the highest exitcode in a chain of pipes.
+# This way you can catch the error in case mysqldump fails in `mysqldump |gzip`, for example.
+set -o pipefail
+
+# Invoke the checkDependenices function to test for Bash packages.  Uncomment if needed.
+# checkDependencies
+
+# Run the script
+completeConcatSeqs
+
+# Exit cleanly
+safeExit
