Add files via upload

diff --git a/bin/BEASTPostProc b/bin/BEASTPostProc
--- a/bin/BEASTPostProc
+++ b/bin/BEASTPostProc
@@ -6,10 +6,10 @@
 # |                                                                                      #
 #                                                                                        #
 # File: BEASTPostProc.sh                                                                 #
-  VERSION="v1.6.3"                                                                       #
+  VERSION="v1.7.0"                                                                       #
 # Author: Justin C. Bagley                                                               #
 # Date: Created by Justin Bagley on Fri, 29 Jul 2016 11:18:02 -0300.                     #
-# Last update: March 18, 2019                                                            #
+# Last update: May 28, 2019                                                              #
 # Copyright (c) 2016-2019 Justin C. Bagley. All rights reserved.                         #
 # Please report bugs to <bagleyj@umsl.edu>.                                              #
 #                                                                                        #
@@ -136,7 +136,7 @@ BEASTPostProc () {
 ##########################################################################################
 
 echo "INFO      | $(date) |----------------------------------------------------------------"
-echo "INFO      | $(date) | BEASTPostProc, v1.6.3 March 2019  (in PIrANHA v0.3a1)   "
+echo "INFO      | $(date) | BEASTPostProc, v1.7.0 May 2019  (in PIrANHA v0.3a1)   "
 echo "INFO      | $(date) | Copyright (c) 2016-2019 Justin C. Bagley. All rights reserved. "
 echo "INFO      | $(date) |----------------------------------------------------------------"
 
@@ -414,20 +414,6 @@ echo ""
 
 
 
-############ SCRIPT OPTIONS
-## OPTION DEFAULTS ##
-LOGANALYSER_PATH=NULL
-TREEANNOTATOR_PATH=NULL
-#LOGANALYSER_BURNIN_STEPS=10000
-#MLE_BURNIN_STEPS=10000
-#BEAST_TREE_BURNIN_STEPS=10000
-NUM_BURNIN_STEPS=10000
-NUM_POSTBURNIN_TREES=5000
-
-## TODO: Add an "all" option for -p flag, so that if the value is all the program summarizes
-## posterior distributions of parameters and trees in TreeAnnotator over _ALL_ posterior 
-## (post-burnin) trees...
-
 ############ CREATE USAGE & HELP TEXTS
 USAGE="Usage: $(basename $0) [OPTION]...
 
@@ -473,7 +459,8 @@ USAGE="Usage: $(basename $0) [OPTION]...
  Copyright (c) 2016-2019 Justin C. Bagley. All rights reserved.
 "
 
-if [[ "$1" == "-h" ]] || [[ "$1" == "--help" ]]; then
+
+if [[ "$1" == "-h" ]] || [[ "$1" == "-help" ]]; then
 	echo "$USAGE"
 	exit
 fi
@@ -483,23 +470,80 @@ if [[ "$1" == "-V" ]] || [[ "$1" == "--version" ]]; then
 	exit
 fi
 
-############ PARSE THE OPTIONS
-while getopts 'l:t:b:p:' opt ; do
-  case $opt in
-## taxonCompFilter options:
-    l) LOGANALYSER_PATH=$OPTARG ;;
-    t) TREEANNOTATOR_PATH=$OPTARG ;;
-    b) NUM_BURNIN_STEPS=$OPTARG ;;
-    p) NUM_POSTBURNIN_TREES=$OPTARG ;;
-## Missing and illegal options:
-    :) printf "Missing argument for -%s\n" "$OPTARG" >&2
-       echo "$USAGE" >&2
-       exit 1 ;;
-   \?) printf "Illegal option: -%s\n" "$OPTARG" >&2
-       echo "$USAGE" >&2
-       exit 1 ;;
-  esac
-done
+############ CHECK ARGUMENTS
+	# echo "$@"; echo "$#"; echo "$1" 
+	# for i in "$@"; do
+	# 	echo "$i";
+	# done
+	# MY_ARGS="$(echo "$@" | perl -pe $'s/\ /\n/')"
+	# echo "$MY_ARGS"
+
+
+############ CAPTURE ARGUMENTS, SEND TO FILE FOR PARSING
+	if [[ -s ./args.tmp ]]; then rm ./args.tmp ; fi ;
+	if [[ -s ./args.txt ]]; then rm ./args.txt ; fi ;
+	if [[ -s ./*.tmp ]]; then rm ./*.tmp ; fi ;
+
+	ALL_MY_ARGUMENTS="$(echo "$@")"
+	echo "$ALL_MY_ARGUMENTS" > ./args.txt
+	perl -p -i -e $'s/\-/\n\-/g' ./args.txt
+	#perl -p -i -e $'s/\ /\n/g' ./args.txt
+	#wc -l ./args.txt | perl -pe 's/\.\/args\.txt.*//g' | perl -pe 's/\ //g'
+
+
+############ MANUALLY PARSE THE OPTIONS FROM ARGS
+
+### SET OPTIONS TO DEFAULT VALUES, EXCEPT WHERE VALUES WERE READ IN FROM USER ARGS
+	if [[  "$(grep -h '\-l' ./args.txt | wc -l | perl -pe 's/\ //g')" = "0" ]]; then
+		LOGANALYSER_PATH=NULL ;
+	else 
+		MY_ARG="$(grep -h '\-l' ./args.txt | perl -pe 's/\-l//g' | perl -pe 's/\ //g')";
+		LOGANALYSER_PATH="$MY_ARG" ;
+	fi
+#
+	if [[  "$(grep -h '\-t' ./args.txt | wc -l | perl -pe 's/\ //g')" = "0" ]]; then
+		TREEANNOTATOR_PATH=NULL ;
+	else 
+		MY_ARG="$(grep -h '\-t' ./args.txt | perl -pe 's/\-t//g' | perl -pe 's/\ //g')";
+		TREEANNOTATOR_PATH="$MY_ARG" ;
+	fi
+#
+	if [[  "$(grep -h '\-b' ./args.txt | wc -l | perl -pe 's/\ //g')" = "0" ]]; then
+		NUM_BURNIN_STEPS=10000 ;
+	else 
+		MY_ARG="$(grep -h '\-b' ./args.txt | perl -pe 's/\-b//g' | perl -pe 's/\ //g')";
+		NUM_BURNIN_STEPS="$MY_ARG" ;
+	fi
+#
+	if [[  "$(grep -h '\-p' ./args.txt | wc -l | perl -pe 's/\ //g')" = "0" ]]; then
+		NUM_POSTBURNIN_TREES=5000 ;
+	else 
+		MY_ARG="$(grep -h '\-p' ./args.txt | perl -pe 's/\-p//g' | perl -pe 's/\ //g')";
+		NUM_POSTBURNIN_TREES="$MY_ARG" ;
+	fi
+#
+
+## TODO: Add an "all" option for -p flag, so that if the value is all the program summarizes
+## posterior distributions of parameters and trees in TreeAnnotator over _ALL_ posterior 
+## (post-burnin) trees...
+
+# ############ PARSE THE OPTIONS
+# while getopts 'l:t:b:p:' opt ; do
+#   case $opt in
+# ## taxonCompFilter options:
+#     l) LOGANALYSER_PATH=$OPTARG ;;
+#     t) TREEANNOTATOR_PATH=$OPTARG ;;
+#     b) NUM_BURNIN_STEPS=$OPTARG ;;
+#     p) NUM_POSTBURNIN_TREES=$OPTARG ;;
+# ## Missing and illegal options:
+#     :) printf "Missing argument for -%s\n" "$OPTARG" >&2
+#        echo "$USAGE" >&2
+#        exit 1 ;;
+#    \?) printf "Illegal option: -%s\n" "$OPTARG" >&2
+#        echo "$USAGE" >&2
+#        exit 1 ;;
+#   esac
+# done
 
 
 # ############# ############# #############
