Edited functions, removed outdated doc/ and examples/ dirs

diff --git a/bin/ExaBayesPostProc b/bin/ExaBayesPostProc
--- a/bin/ExaBayesPostProc
+++ b/bin/ExaBayesPostProc
@@ -6,35 +6,167 @@
 # |                                                                                      #
 #                                                                                        #
 # File: ExaBayesPostProc.sh                                                              #
-  VERSION="1.2"                                                                          #
+  VERSION="1.3.0"                                                                        #
 # Author: Justin C. Bagley                                                               #
 # Date: Created by Justin Bagley on Fri, 29 Jul 2016 11:28:02 -0300.                     #
-# Last update: March 6, 2019                                                             #
+# Last update: March 12, 2019                                                            #
 # Copyright (c) 2016-2019 Justin C. Bagley. All rights reserved.                         #
 # Please report bugs to <bagleyj@umsl.edu>.                                              #
 #                                                                                        #
 # Description:                                                                           #
-# SHELL SCRIPT THAT AUTOMATES SUBSAMPLING EACH OF ONE TO MULTIPLE PHYLIP ALIGNMENT       #
-# FILES DOWN TO ONE (RANDOM) SEQUENCE PER SPECIES (FOR SPECIES TREE ANALYSIS)            #
+# SHELL SCRIPT THAT AUTOMATES READING AND CONDUCTING POST-PROCESSING OF PHYLOGENETIC     #
+# RESULTS FROM EXABAYES                                                                  #
 #                                                                                        #
 ##########################################################################################
 
-if [[ "$1" == "-V" ]] || [[ "$1" == "--version" ]]; then
-	echo "$(basename $0) $VERSION";
-	exit
+# Provide a variable with the location of this script.
+SCRIPT_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+
+# Source Scripting Utilities
+# -----------------------------------
+# These shared utilities provide many functions which are needed to provide
+# the functionality in this boilerplate. This script will fail if they can
+# not be found.
+# -----------------------------------
+
+UTILS_LOCATION="${SCRIPT_PATH}/../lib/utils.sh" # Update this path to find the utilities.
+
+if [[ -f "${UTILS_LOCATION}" ]]; then
+  source "${UTILS_LOCATION}"
+else
+  echo "Please find the file util.sh and add a reference to it in this script. Exiting..."
+  exit 1
 fi
 
-echo "
-##########################################################################################
-#                           ExaBayesPostProc v1.2, March 2019                            #
-##########################################################################################
-"
 
-echo "INFO      | $(date) | STEP #1: CALL PROGRAMS TO DO ExaBayes POST-PROCESSING. "
-	MY_EXABAYES_TREEFILES=./ExaBayes_topologies.*	## Assign "topologies" files in current directory to variable.
-	MY_EXABAYES_PARAMFILES=./ExaBayes_parameters.*	## Assign "parameters" files in current directory to variable.
+# Source shared functions and variables
+# -----------------------------------
 
-###### RUN SUMMARY: coming soon...
+FUNCS_LOCATION="${SCRIPT_PATH}/../lib/sharedFunctions.sh" # Update this path to find the shared functions.
+VARS_LOCATION="${SCRIPT_PATH}/../lib/sharedVariables.sh" # Update this path to find the shared variables.
+
+if [[ -f "${FUNCS_LOCATION}" ]] && [[ -f "${VARS_LOCATION}" ]]; then
+  source "${FUNCS_LOCATION}" ;
+  source "${VARS_LOCATION}" ;
+else
+  echo "Please find the files sharedFunctions.sh and sharedVariables.sh and add references to them in this script. Exiting... "
+  exit 1
+fi
+
+
+# trapCleanup Function
+# -----------------------------------
+# Any actions that should be taken if the script is prematurely
+# exited.  Always call this function at the top of your script.
+# -----------------------------------
+function trapCleanup() {
+  echo ""
+  # Delete temp files, if any
+  if is_dir "${tmpDir}"; then
+    rm -r "${tmpDir}"
+  fi
+  die "Exit trapped. In function: '${FUNCNAME[*]}'"
+}
+
+# safeExit
+# -----------------------------------
+# Non destructive exit for when script exits naturally.
+# Usage: Add this function at the end of every script.
+# -----------------------------------
+function safeExit() {
+  # Delete temp files, if any
+  if is_dir "${tmpDir}"; then
+    rm -r "${tmpDir}"
+  fi
+  trap - INT TERM EXIT
+  exit
+}
+
+# Set Flags
+# -----------------------------------
+# Flags which can be overridden by user input.
+# Default values are below
+# -----------------------------------
+quiet=false
+printLog=false
+verbose=false
+force=false
+strict=false
+debug=false
+args=()
+
+# Set Temp Directory
+# -----------------------------------
+# Create temp directory with three random numbers and the process ID
+# in the name.  This directory is removed automatically at exit.
+# -----------------------------------
+tmpDir="/tmp/${SCRIPT_NAME}.$RANDOM.$RANDOM.$RANDOM.$$"
+(umask 077 && mkdir "${tmpDir}") || {
+  die "Could not create temporary directory! Exiting."
+}
+
+# Logging
+# -----------------------------------
+# Log is only used when the '-l' flag is set.
+#
+# To never save a logfile change variable to '/dev/null'
+# Save to Desktop use: $HOME/Desktop/${SCRIPT_BASENAME}.log
+# Save to standard user log location use: $HOME/Library/Logs/${SCRIPT_BASENAME}.log
+# -----------------------------------
+logFile="$HOME/Library/Logs/${SCRIPT_BASENAME}.log"
+
+# Check for Dependencies
+# -----------------------------------
+# Arrays containing package dependencies needed to execute this script.
+# The script will fail if dependencies are not installed.  For Mac users,
+# most dependencies can be installed automatically using the package
+# manager 'Homebrew'.  Mac applications will be installed using
+# Homebrew Casks. Ruby and gems via RVM.
+# -----------------------------------
+homebrewDependencies=()
+caskDependencies=()
+gemDependencies=()
+
+
+
+
+function ExaBayesPostProc () {
+
+######################################## START ###########################################
+##########################################################################################
+
+echo "INFO      | $(date) |----------------------------------------------------------------"
+echo "INFO      | $(date) | ExaBayesPostProc, v1.3.0 March 2019  (part of PIrANHA v1.0.0)  "
+echo "INFO      | $(date) | Copyright (c) 2016-2019 Justin C. Bagley. All rights reserved. "
+echo "INFO      | $(date) |----------------------------------------------------------------"
+
+######################################## START ###########################################
+echo "INFO      | $(date) | Step #1: Set up workspace and check machine type. "
+############ SET WORKING DIRECTORY AND CHECK MACHINE TYPE
+## Nothing to do for working dir because script executes in current working dir (of execution/
+## sourcing). Only set to run in current working dir, and echo cwd to screen:
+USER_SPEC_PATH="$(printf '%q\n' "$(pwd)")";
+echoCDWorkingDir
+MY_WORKING_DIR="$(pwd -P)";
+
+#echo "INFO      | $(date) |          Checking machine type... "
+checkMachineType
+#echo "INFO      | $(date) |               Found machine type ${machine}. "
+
+
+echo "INFO      | $(date) | Step #2: Read output file names and call programs needed to conduct ExaBayes post-processing. "
+
+### TODO: Add a check on whether or not the ExaBayes program and its utilities programs
+### are actually installed and available from the command line. If so, fine; if not available,
+### then add code to download and install them.
+
+echo "INFO      | $(date) |          A. Read ExaBayes results files into environmental variables... "
+MY_EXABAYES_TREEFILES=./ExaBayes_topologies.*	## Assign "topologies" files in current directory to variable.
+MY_EXABAYES_PARAMFILES=./ExaBayes_parameters.*	## Assign "parameters" files in current directory to variable.
+
+
+echo "INFO      | $(date) |          B. Conduct ExaBayes run summary... "
+###### RUN SUMMARY:
 
 echo "INFO      | $(date) |         TREE SUMMARY: "
 echo "INFO      | $(date) |         Getting 50% percentile credible set of trees from ExaBayes analysis... "
@@ -45,6 +177,7 @@ echo "INFO      | $(date) |         Getting 50% percentile credible set of trees
 	done
 )
 
+echo "INFO      | $(date) |          Getting bipartitions, plus branch lengths and ESS scores for all bipartitions, of ExaBayes trees... "
 ###### Get bipartitions, plus branch lengths & ESS scores for all bipartitions, of ExaBayes trees:
 (
 	for i in $MY_EXABAYES_TREEFILES; do 
@@ -53,8 +186,10 @@ echo "INFO      | $(date) |         Getting 50% percentile credible set of trees
 	done
 )
 
+echo "INFO      | $(date) |          C. Conduct parameters summary... "
 ###### PARAMETERS SUMMARY: 
 ###### Summarize parameters of each run using postProcParam utility:
+echo "INFO      | $(date) |          Summarizing parameters of each ExaBayes run in current working directory using postProcParam utility... "
 (
 	for j in $MY_EXABAYES_PARAMFILES; do 				## This looks in the current directory for tree files output by ExaBayes to use as input files for the following operations.
 		echo "$j";
@@ -62,26 +197,35 @@ echo "INFO      | $(date) |         Getting 50% percentile credible set of trees
 	done
 )
 
-echo "INFO      | $(date) | STEP #2: REFORMAT (FOR) & PROCESS ExaBayes OUTPUT FILES IN MrBayes. "
+echo "INFO      | $(date) | Step #3: Reformat ExaBayes output files and conduct additional file processing in MrBayes v3.2+. "
 (
 	for k in ./ExaBayes_topologies.*; do 
 		echo "$k";
-		sed 's/.{.}//g' ${k} > ${k}_1.tmp ;
-			sed 's/:0.0;/;/g' ${k}_1.tmp > ${k}.t ;
+		sed 's/.{.}//g' "${k}" > "${k}"_1.tmp ;
+			sed 's/:0.0;/;/g' "${k}"_1.tmp > "${k}".t ;
 	done
 )
 
+### TODO: Add an option that reads in the number of runs and creates or sets the following loop 
+### accordingly (so that if -n 2 , then the loop goes through the first two lines, through
+### .run2.t, and if -n3, then the loop goes through .run3.t, etc.)
 (
 	for l in *.t; do
-		mv $l ${l/.0.t/.run1.t} ;
-		mv $l ${l/.1.t/.run2.t} ;
-	#	mv $l ${l/.2.t/.run2.t}	;					## __UNCOMMENT THESE NEXT LINES AS NEEDED__, according to number of tree files you are starting with, by uncommenting 1 line for each subsequent tree file beyond two runs.
-	#	mv $l ${l/.3.t/.run2.t} ;
-	#	mv $l ${l/.4.t/.run2.t} ;
+		mv "$l" ${l/.0.t/.run1.t} ;
+		mv "$l" ${l/.1.t/.run2.t} ;
+	#	mv "$l" ${l/.2.t/.run2.t} ;					## __UNCOMMENT THESE NEXT LINES AS NEEDED__, according to number of tree files you are starting with, by uncommenting 1 line for each subsequent tree file beyond two runs.
+	#	mv "$l" ${l/.3.t/.run2.t} ;
+	#	mv "$l" ${l/.4.t/.run2.t} ;
 	done
 )
 
-###### Prep files and then Summarize trees, their posterior probabilities, and their errors using MrBayes.
+echo "INFO      | $(date) | Step #4: Prep files and then summarize trees, their posterior probabilities, and their errors using MrBayes v3.2+. "
+###### Prep files and then summarize trees, their posterior probabilities, and their errors using MrBayes.
+
+### TODO: Add an option to read in the user's NEXUS file that corresponds to the ExaBayes run. This 
+### way, the user can write code to run the ExaBayesPostProc script on multiple runs, run folders,
+### or even results of multiple runs in same folder...
+
 	MY_NEXUS=./*.nex
 	MY_NEXUS_FILENAME="$(echo ./*.nex | sed -n 's/.\///p')";		## Assumes only one NEXUS file in working directory corresponding to ExaBayes run input file.
 	MY_MRBAYES_FILENAME="$(ls | sed -n 's/\.0$//p' | grep -n "topologies" | sed -n 's/.://p')";
@@ -94,19 +238,65 @@ sumt Filename=${MY_MRBAYES_FILENAME} relburnin=yes burninfrac= 0.25
 quit" > ./batch.txt
 
 	
-	mb <./batch.txt > Mrbayes_sumt_log.txt &		## Use batch to run MrBayes.
+	mb <./batch.txt > Mrbayes_sumt_log.txt &
+	## The '&' calls a batch run of mrbayes on the batch file we created above. What a nice and convenient way to do things. :)
+
+echo "INFO      | $(date) | Step #5: Clean up workspace by deleting temporary files generated during run. "
+echo "INFO      | $(date) |          Removing temporary files... "
+	
+	rm *_1.tmp batch.txt ;
 
 
-echo "INFO      | $(date) | STEP #3: CLEANUP FILES. "
-	rm *_1.tmp batch.txt ;							## Remove temporary files created above.
+#echo "INFO      | $(date) | Done post-processing ExaBayes results. "
+#echo "INFO      | $(date) | Bye. 
+#"
 
+echo "----------------------------------------------------------------------------------------------------------"
 
-echo "INFO      | $(date) | Done post-processing ExaBayes results. "
-echo "INFO      | $(date) | Bye. 
-"
-#
-#
-#
+##########################################################################################
 ######################################### END ############################################
 
-exit 0
+}
+
+
+
+############ SCRIPT OPTIONS
+## None at this time. TODO: Add options if you are serious about using this yourself, or
+## about having other people actually use this script/function in PIrANHA.
+
+
+# ############# ############# #############
+# ##       TIME TO RUN THE SCRIPT        ##
+# ##                                     ##
+# ## You shouldn't need to edit anything ##
+# ## beneath this line                   ##
+# ##                                     ##
+# ############# ############# #############
+
+# Trap bad exits with your cleanup function
+trap trapCleanup EXIT INT TERM
+
+# Set IFS to preferred implementation
+IFS=$'\n\t'
+
+# Exit on error. Append '||true' when you run the script if you expect an error.
+set -o errexit
+
+# Run in debug mode, if set
+if ${debug}; then set -x ; fi
+
+# Exit on empty variable
+if ${strict}; then set -o nounset ; fi
+
+# Bash will remember & return the highest exitcode in a chain of pipes.
+# This way you can catch the error in case mysqldump fails in `mysqldump |gzip`, for example.
+set -o pipefail
+
+# Invoke the checkDependenices function to test for Bash packages.  Uncomment if needed.
+# checkDependencies
+
+# Run the script
+ExaBayesPostProc
+
+# Exit cleanly
+safeExit
diff --git a/bin/makePartitions b/bin/makePartitions
--- a/bin/makePartitions
+++ b/bin/makePartitions
@@ -1,86 +1,196 @@
 #!/bin/sh
 
-## makePartitions.sh
-## Justin C. Bagley
-## February 24, 2019
-##
-## Usage: ./makePartitions.sh [stdin:] <workingDir>
-##
-## THIS SCRIPT loops through a set of PHYLIP DNA sequence alignments in <workingDir>
-## (working directory path; mandatory input) and uses their header information to make
-## partitions/charsets files with RAxML partition, PartitionFinder subset, and NEXUS charset
-## formats. Here, the ordering of charsets is equivalent to the alphanumeric order in 
-## which a bash UNIX terminal would read the PHYLIP files (e.g. locus1.phy, locus10.phy, ...,
-## and not locus1.phy, locus2.phy, ...), which is the same order that the ElConcatenero
-## script(s) (https://github.com/ODiogoSilva/ElConcatenero) and my concatenateSeqs.sh script 
-## (in this repository; https://github.com/justincbagley/Anoura-UCE-Phylogenomics-Project/)
-## read and concatenate the PHYLIP alignments. 
-## 
-## This script was written during development of concatenateSeqs.sh, but as a standalone 
-## script it solves the problem of correcting partitions output by ElConcatenero if, upon
-## checking, ElConcatenero has given the correct order of loci but incorrect ranges of 
-## nucleotides for the partitions in its output.
+##########################################################################################
+#  __  o  __   __   __  |__   __                                                         #
+# |__) | |  ' (__( |  ) |  ) (__(                                                        # 
+# |                                                                                      #
+#                                                                                        #
+# File: makePartitions.sh                                                                #
+  VERSION="v1.2.1"                                                                       #
+# Author: Justin C. Bagley                                                               #
+# Date: Created by Justin Bagley on Tue, 19 Feb 2019 22:36:23 -0600.                     #
+# Last update: March 12, 2019                                                            #
+# Copyright (c) 2019 Justin C. Bagley. All rights reserved.                              #
+# Please report bugs to <bagleyj@umsl.edu>.                                              #
+#                                                                                        #
+# Description:                                                                           #
+# SHELL SCRIPT THAT USES PHYLIP DNA SEQUNENCE ALIGNMENTS IN CURRENT DIRECTORY TO MAKE    #
+# PARTITIONS / CHARSETS FILES IN RAxML PARTITION, PartitionFinder SUBSET, AND NEXUS      #
+# CHARSET FORMATS, WHICH ARE ALL OUTPUT TO FILE                                          #
+#                                                                                        #
+##########################################################################################
 
+# Provide a variable with the location of this script.
+SCRIPT_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 
-# Saves all makePartitions script output to file named 'makePartitions_output.txt'
-exec >> ./makePartitions_output.txt 
-exec 2>&1
+# Source Scripting Utilities
+# -----------------------------------
+# These shared utilities provide many functions which are needed to provide
+# the functionality in this boilerplate. This script will fail if they can
+# not be found.
+# -----------------------------------
 
-############ Check for mandatory positional parameters
-if [ $# -lt 1 ]; then
-	echo "WARNING!  | $(date) |          Missing one or more mandatory positional parameters. Quitting... "
-	echo "INFO      | $(date) |          Usage: $(basename "$0") workingDir "
+UTILS_LOCATION="${SCRIPT_PATH}/../lib/utils.sh" # Update this path to find the utilities.
+
+if [[ -f "${UTILS_LOCATION}" ]]; then
+  source "${UTILS_LOCATION}"
+else
+  echo "Please find the file util.sh and add a reference to it in this script. Exiting..."
   exit 1
 fi
-USER_SPEC_PATH="$1"
 
 
-############ Set <workingDir>
-if [[ "$USER_SPEC_PATH" = "$(printf '%q\n' "$(pwd)")" ]] || [[ "$USER_SPEC_PATH" = "." ]]; then
-	#MY_CWD=`pwd -P`
-	MY_CWD="$(printf '%q\n' "$(pwd)" | sed 's/\\//g')"
-	echo "INFO      | $(date) |          Setting working directory to:  "
-	echo "$MY_CWD "
-elif [[ "$USER_SPEC_PATH" != "$(printf '%q\n' "$(pwd)")" ]]; then
-	if [[ "$USER_SPEC_PATH" = ".." ]] || [[ "$USER_SPEC_PATH" = "../" ]] || [[ "$USER_SPEC_PATH" = "..;" ]] || [[ "$USER_SPEC_PATH" = "../;" ]]; then
-		cd ..;
-		MY_CWD="$(printf '%q\n' "$(pwd)" | sed 's/\\//g')"
-	else
-		MY_CWD=$USER_SPEC_PATH
-		echo "INFO      | $(date) |          Setting working directory to user-specified dir:  "	
-		echo "$MY_CWD "
-		cd "$MY_CWD"
-	fi
+# Source shared functions and variables
+# -----------------------------------
+
+FUNCS_LOCATION="${SCRIPT_PATH}/../lib/sharedFunctions.sh" # Update this path to find the shared functions.
+VARS_LOCATION="${SCRIPT_PATH}/../lib/sharedVariables.sh" # Update this path to find the shared variables.
+
+if [[ -f "${FUNCS_LOCATION}" ]] && [[ -f "${VARS_LOCATION}" ]]; then
+  source "${FUNCS_LOCATION}" ;
+  source "${VARS_LOCATION}" ;
 else
-	echo "WARNING!  | $(date) |          Null working directory path. Quitting... "
-	exit 1
+  echo "Please find the files sharedFunctions.sh and sharedVariables.sh and add references to them in this script. Exiting... "
+  exit 1
 fi
 
 
-######################################## START ###########################################
-
-###### SET UP ENVIRONMENT BY CREATING USEFUL VARIABLES AND FUNCTIONS AND CHECKING MACHINE TYPE.
-	CR=$(printf '\r')
-	TAB=$(printf '\t')
-	calc () {
-		bc -l <<< "$@"
+# trapCleanup Function
+# -----------------------------------
+# Any actions that should be taken if the script is prematurely
+# exited.  Always call this function at the top of your script.
+# -----------------------------------
+function trapCleanup() {
+  echo ""
+  # Delete temp files, if any
+  if is_dir "${tmpDir}"; then
+    rm -r "${tmpDir}"
+  fi
+  die "Exit trapped. In function: '${FUNCNAME[*]}'"
 }
 
+# safeExit
+# -----------------------------------
+# Non destructive exit for when script exits naturally.
+# Usage: Add this function at the end of every script.
+# -----------------------------------
+function safeExit() {
+  # Delete temp files, if any
+  if is_dir "${tmpDir}"; then
+    rm -r "${tmpDir}"
+  fi
+  trap - INT TERM EXIT
+  exit
+}
+
+# Set Flags
+# -----------------------------------
+# Flags which can be overridden by user input.
+# Default values are below
+# -----------------------------------
+quiet=false
+printLog=false
+verbose=false
+force=false
+strict=false
+debug=false
+args=()
+
+# Set Temp Directory
+# -----------------------------------
+# Create temp directory with three random numbers and the process ID
+# in the name.  This directory is removed automatically at exit.
+# -----------------------------------
+tmpDir="/tmp/${SCRIPT_NAME}.$RANDOM.$RANDOM.$RANDOM.$$"
+(umask 077 && mkdir "${tmpDir}") || {
+  die "Could not create temporary directory! Exiting."
+}
+
+# Logging
+# -----------------------------------
+# Log is only used when the '-l' flag is set.
+#
+# To never save a logfile change variable to '/dev/null'
+# Save to Desktop use: $HOME/Desktop/${SCRIPT_BASENAME}.log
+# Save to standard user log location use: $HOME/Library/Logs/${SCRIPT_BASENAME}.log
+# -----------------------------------
+logFile="$HOME/Library/Logs/${SCRIPT_BASENAME}.log"
+
+# Check for Dependencies
+# -----------------------------------
+# Arrays containing package dependencies needed to execute this script.
+# The script will fail if dependencies are not installed.  For Mac users,
+# most dependencies can be installed automatically using the package
+# manager 'Homebrew'.  Mac applications will be installed using
+# Homebrew Casks. Ruby and gems via RVM.
+# -----------------------------------
+homebrewDependencies=()
+caskDependencies=()
+gemDependencies=()
 
 
-###### GENERATE AND RUN MAKEPARTITIONS FUNCTION TO MAKE FILES WITH VARIOUS PARTITION/CHARSET
-###### FORMATS
 
-makePartitions () {
 
+function makePartitions () {
+
+######################################## START ###########################################
+##########################################################################################
+
+echo "INFO      | $(date) |----------------------------------------------------------------"
+echo "INFO      | $(date) | makePartitions, v1.2.1 March 2019  (part of PIrANHA v1.0.0)    "
+echo "INFO      | $(date) | Copyright (c) 2019 Justin C. Bagley. All rights reserved.      "
+echo "INFO      | $(date) |----------------------------------------------------------------"
+
+######################################## START ###########################################
+if [[ "$MY_VERBOSE_OUT_SWITCH" != "0" ]]; then
+	echo "INFO      | $(date) | Starting makePartitions analysis... "
+	echo "INFO      | $(date) | Step #1: Set up workspace and check machine type. "
+fi
+############ SET WORKING DIRECTORY AND CHECK MACHINE TYPE
+## Nothing to do for working dir because script executes in current working dir (of execution/
+## sourcing). Only set to run in current working dir, and echo cwd to screen:
+USER_SPEC_PATH="$(printf '%q\n' "$(pwd)")";
+echoCDWorkingDir
+MY_WORKING_DIR="$(pwd -P)";
+
+#echo "INFO      | $(date) |          Checking machine type... "
+checkMachineType
+#echo "INFO      | $(date) |               Found machine type ${machine}. "
+
+
+if [[ "$MY_VERBOSE_OUT_SWITCH" != "0" ]]; then
+	echo "INFO      | $(date) | Step #2: Set output file. "
+fi
+if [[ "$MY_OUTPUT_FILE_SWITCH" != "NULL" ]]; then
+	mkdir output/ ;
+	exec >> ./output/"$MY_OUTPUT_FILE_SWITCH" ;
+	exec 2>&1 ;
+#
+	if [[ "$MY_VERBOSE_OUT_SWITCH" != "0" ]]; then
+		echo "INFO      | $(date) |          Output file switch activated. Logging all output to file at ./output/${MY_OUTPUT_FILE_SWITCH} ... "
+	fi
+elif [[ "$MY_OUTPUT_FILE_SWITCH" = "NULL" ]]; then
+	mkdir output/ ;
+	exec >> ./output/makePartitions_output.txt ;
+	exec 2>&1 ;
+#
+	if [[ "$MY_VERBOSE_OUT_SWITCH" != "0" ]]; then
+		echo "INFO      | $(date) |          Default output file settings. Logging all output to file at ./output/makePartitions_output.txt ... "
+	fi
+fi
+
+
+if [[ "$MY_VERBOSE_OUT_SWITCH" != "0" ]]; then
+	echo "INFO      | $(date) | Step #3: Extract partitions information from PHYLIP headers and make partitions files. "
+fi
 count=1
 (
 	for i in ./*.phy; do
 
 		######  makePartitions  ######
 
-		MY_PHYLIP_NCHAR="$(head -n1 $i | perl -pe 's/^[0-9]*\ +//g; s/\ //g')"
-		echo "###----------   $i,  $MY_PHYLIP_NCHAR bp   ----------###"
+		MY_PHYLIP_NCHAR="$(head -n1 $i | perl -pe 's/^[0-9]*\ +//g; s/\ //g')" ;
+		echo "###----------   $i,  $MY_PHYLIP_NCHAR bp   ----------###" ;
 
 
 		if [[ "$count" = "1" ]]; then
@@ -91,54 +201,162 @@ count=1
 		# raxml format: "DNA, locus1 = 1-607"
 		# PF format: "locus1=1-607;"
 		# NEXUS format: "  charset locus1 = 1-607;" 
-			locus="$(basename $i '.phy')"
-			echo "DNA, ${locus} = 1-${MY_PHYLIP_NCHAR}" >> ./raxml_partitions.part
-			echo "${locus}=1-${MY_PHYLIP_NCHAR};" >> partitionfinder_subsets.txt
-			echo "  charset ${locus} = 1-${MY_PHYLIP_NCHAR};" >> NEXUS_charsets_lowercase.txt
-			echo "  CHARSET ${locus} = 1-${MY_PHYLIP_NCHAR};" >> NEXUS_charsets_uppercase.txt
+			locus="$(basename $i '.phy')" ;
+			echo "DNA, ${locus} = 1-${MY_PHYLIP_NCHAR}" >> ./raxml_partitions.part ;
+			echo "${locus}=1-${MY_PHYLIP_NCHAR};" >> partitionfinder_subsets.txt ;
+			echo "  charset ${locus} = 1-${MY_PHYLIP_NCHAR};" >> NEXUS_charsets_lowercase.txt ;
+			echo "  CHARSET ${locus} = 1-${MY_PHYLIP_NCHAR};" >> NEXUS_charsets_uppercase.txt ;
 
-			#echo "$MY_PHYLIP_NCHAR" > previous_nchar.tmp
-			MY_PREV_END_RANGE_VAL="$(echo $MY_PHYLIP_NCHAR)"
+			#echo "$MY_PHYLIP_NCHAR" > previous_nchar.tmp ;
+			MY_PREV_END_RANGE_VAL="$(echo $MY_PHYLIP_NCHAR)";
 
 		elif [[ "$count" -gt "1" ]]; then
 
 		## On second and subsequent loop iterations ($count > 1), add the partitions/charsets
 		## to the partitions/charsets files by making calculations using previous locus 
 		## information and current, ith locus information, as follows:
-			locus="$(basename $i '.phy')"
-			#MY_PREV_NCHAR="$(cat ./previous_nchar.tmp)"
-			MY_NEW_START_RANGE_VAL="$(calc $MY_PREV_END_RANGE_VAL + 1)"
-			MY_NEW_END_RANGE_VAL="$(calc $MY_PREV_END_RANGE_VAL + $MY_PHYLIP_NCHAR)"
-			echo "DNA, ${locus} = $MY_NEW_START_RANGE_VAL-${MY_NEW_END_RANGE_VAL}" >> ./raxml_partitions.part
-			echo "${locus}=$MY_NEW_START_RANGE_VAL-${MY_NEW_END_RANGE_VAL};" >> partitionfinder_subsets.txt
-			echo "  charset ${locus} = $MY_NEW_START_RANGE_VAL-${MY_NEW_END_RANGE_VAL};" >> NEXUS_charsets_lowercase.txt
-			echo "  CHARSET ${locus} = $MY_NEW_START_RANGE_VAL-${MY_NEW_END_RANGE_VAL};" >> NEXUS_charsets_uppercase.txt
+			locus="$(basename $i '.phy')" ;
 
-			#echo "$MY_PHYLIP_NCHAR" > previous_nchar.tmp
-			MY_PREV_END_RANGE_VAL="$(echo $MY_NEW_END_RANGE_VAL)"
+			#MY_PREV_NCHAR="$(cat ./previous_nchar.tmp)" ;
+
+			MY_NEW_START_RANGE_VAL="$(calc $MY_PREV_END_RANGE_VAL + 1)" ;
+			MY_NEW_END_RANGE_VAL="$(calc $MY_PREV_END_RANGE_VAL + $MY_PHYLIP_NCHAR)" ;
+			echo "DNA, ${locus} = $MY_NEW_START_RANGE_VAL-${MY_NEW_END_RANGE_VAL}" >> ./raxml_partitions.part ;
+			echo "${locus}=$MY_NEW_START_RANGE_VAL-${MY_NEW_END_RANGE_VAL};" >> partitionfinder_subsets.txt ;
+			echo "  charset ${locus} = $MY_NEW_START_RANGE_VAL-${MY_NEW_END_RANGE_VAL};" >> NEXUS_charsets_lowercase.txt ;
+			echo "  CHARSET ${locus} = $MY_NEW_START_RANGE_VAL-${MY_NEW_END_RANGE_VAL};" >> NEXUS_charsets_uppercase.txt ;
+
+			#echo "$MY_PHYLIP_NCHAR" > previous_nchar.tmp ;
+			MY_PREV_END_RANGE_VAL="$(echo $MY_NEW_END_RANGE_VAL)" ;
 
 		fi
 
-	echo "$((count++))" > count.tmp
+	echo "$((count++))" > count.tmp ;
 		
 	done
 )
 
-}
 
-## DON'T FORGET TO RUN THE FUNCTION!
-makePartitions
-
-
+if [[ "$MY_VERBOSE_OUT_SWITCH" != "0" ]]; then
+	echo "INFO      | $(date) | Step #4: Clean up workspace by removing temporary files generated during run. "
+	echo "INFO      | $(date) |          Deleting temporary files... "
+fi
 ############ CLEAN UP WORKING DIR BY DELETING TEMPORARY FILES.
 	
 	rm ./*.tmp
 
+echo "----------------------------------------------------------------------------------------------------------"
 
-#
-#
-#
+##########################################################################################
 ######################################### END ############################################
 
-exit 0
+}
+
+
+
+############ SCRIPT OPTIONS
+## OPTION DEFAULTS ##
+MY_OUTPUT_FILE_SWITCH=NULL
+MY_VERBOSE_OUT_SWITCH=0
+
+############ CREATE USAGE & HELP TEXTS
+USAGE="Usage: $(basename $0) [OPTION]...
+
+ ${bold}Options:${reset}
+  -o   outputFile (def: NULL) send screen output to file in working dir with user-specified 
+       name, for example 'output.txt'
+  -v   verbose (def: 0, off; 1, on) specify verbose filename conversion and step output to
+       screen (stdout)
+  -h   help text (also: --help) echo this help text and exit
+  -V   version (also: --version) echo version and exit
+
+ ${bold}OVERVIEW${reset}
+ THIS SCRIPT loops through a set of PHYLIP (Felsenstein 2002) DNA sequence alignments in the 
+ current working directory and uses their headers to make partitions/charsets files with RAxML 
+ partition, PartitionFinder subset, and NEXUS charset formats. Results are output to multiple
+ partitions files. The ordering of charsets is equal to the alphanumeric order in which bash 
+ or UNIX terminal would read the PHYLIP files (e.g. locus1.phy, locus10.phy, ..., and not 
+ locus1.phy, locus2.phy, ...). This is the same order in which PIrANHA's related concatenateSeqs 
+ function will read and concatenate the PHYLIP alignments. 
+	This script was written during development of the concatenateSeqs function but can be
+ used as a standalone function to solve the problems of (1) obtaining partitions files
+ for a set of PHYLIP alignments, or specifically (2) correcting partitions output by 
+ ElConcatenero (https://github.com/ODiogoSilva/ElConcatenero; currently packaged with 
+ PIrANHA) if, upon checking, ElConcatenero has given the correct order of loci but incorrect
+ ranges of nucleotides for the partitions in its output. 
+
+ ${bold}Usage examples:${reset}
+    piranha -f makePartitions            Run makePartitions in current working directory
+    piranha -f makePartitions --args='-h'    Get this makePartitions-specific help text
+
+ ${bold}CITATION${reset}
+ Bagley, J.C. 2019. PIrANHA v1.0.0. GitHub repository, Available at:
+	<https://github.com/justincbagley/PIrANHA>.
+
+ Created by Justin Bagley on Tue, 19 Feb 2019 22:36:23 -0600.
+ Copyright (c) 2019 Justin C. Bagley. All rights reserved.
+"
+
+if [[ "$1" == "-h" ]] || [[ "$1" == "-help" ]]; then
+	echo "$USAGE"
+	exit
+fi
+
+if [[ "$1" == "-V" ]] || [[ "$1" == "--version" ]]; then
+	echo "$(basename $0) $VERSION";
+	exit
+fi
+
+############ PARSE THE OPTIONS
+while getopts 'o:v:' opt ; do
+  case $opt in
+## makePartitions options:
+    o) MY_OUTPUT_FILE_SWITCH=$OPTARG ;;
+    v) MY_VERBOSE_OUT_SWITCH=$OPTARG ;;
+## Missing and illegal options:
+    :) printf "Missing argument for -%s\n" "$OPTARG" >&2
+       echo "$Usage" >&2
+       exit 1 ;;
+   \?) printf "Illegal option: -%s\n" "$OPTARG" >&2
+       echo "$Usage" >&2
+       exit 1 ;;
+  esac
+done
+
+
+# ############# ############# #############
+# ##       TIME TO RUN THE SCRIPT        ##
+# ##                                     ##
+# ## You shouldn't need to edit anything ##
+# ## beneath this line                   ##
+# ##                                     ##
+# ############# ############# #############
+
+# Trap bad exits with your cleanup function
+trap trapCleanup EXIT INT TERM
+
+# Set IFS to preferred implementation
+IFS=$'\n\t'
+
+# Exit on error. Append '||true' when you run the script if you expect an error.
+set -o errexit
+
+# Run in debug mode, if set
+if ${debug}; then set -x ; fi
+
+# Exit on empty variable
+if ${strict}; then set -o nounset ; fi
+
+# Bash will remember & return the highest exitcode in a chain of pipes.
+# This way you can catch the error in case mysqldump fails in `mysqldump |gzip`, for example.
+set -o pipefail
+
+# Invoke the checkDependenices function to test for Bash packages.  Uncomment if needed.
+# checkDependencies
+
+# Run the script
+makePartitions
+
+# Exit cleanly
+safeExit
 
diff --git a/bin/renameForStarBeast2 b/bin/renameForStarBeast2
--- a/bin/renameForStarBeast2
+++ b/bin/renameForStarBeast2
@@ -1,11 +1,11 @@
 #!/bin/sh
 
 ##########################################################################################
-# File: renameForStarBeast2.sh                                                           #
-  VERSION="v1.0"                                                                         #
+# File: renameForStarBEAST2.sh                                                           #
+  VERSION="v1.2.0"                                                                       #
 # Author: Justin C. Bagley                                                               #
 # Date: Created by Justin Bagley on Tue, Mar 5 11:32:42 CST 2019.                        #
-# Last update: March 5, 2019                                                             #
+# Last update: March 12, 2019                                                            #
 # Copyright (c) 2019 Justin C. Bagley. All rights reserved.                              #
 # Please report bugs to <bagleyj@umsl.edu>.                                              #
 #                                                                                        #
@@ -15,107 +15,142 @@
 #                                                                                        #
 ##########################################################################################
 
-############ SCRIPT OPTIONS
-## OPTION DEFAULTS ##
-MY_INPUT_FILE_TYPE=phylip
+# Provide a variable with the location of this script.
+SCRIPT_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 
-############ CREATE USAGE & HELP TEXTS
-USAGE="Usage: $(basename $0) [Options: -i V --version] [stdin:] <assignmentFile> <workingDir>
- ## Help:
-  -h   help text (also: --help) echo this help text and exit
+# Source Scripting Utilities
+# -----------------------------------
+# These shared utilities provide many functions which are needed to provide
+# the functionality in this boilerplate. This script will fail if they can
+# not be found.
+# -----------------------------------
 
- ## Options:
-  -i   input file type (def: phylip; other: fasta) type of file(s) in <workingDir> that 
-       will be renamed (assumes .phy or .fas extensions for PHYLIP or FASTA format, 
-       respectively)
-  -V   version (also: --version) echo version and exit
+UTILS_LOCATION="${SCRIPT_PATH}/../lib/utils.sh" # Update this path to find the utilities.
 
- ## Mandatory input:
-  <assignmentFile> ASTRAL-III style assignment file detailing which individual tips correspond
-                   to which species or taxa
-  <workingDir>     Path to working directory; use '.' for current directory and '..' for up
-                   one directory
-
- INFO
- For best results, species assignments in assignment file parameter, <assignmentFile>, should 
- be simple alphanumeric names (e.g. 'unimaculatus') with no spaces, hyphens, underscores, or
- other nonalphanumeric characters.
-
- ## Examples:
-  ./renameForStarBeast2.sh -i phylip assignment.txt .
-  ./renameForStarBeast2.sh -i fasta assignment.txt .
-  ./renameForStarBeast2.sh --version
-
-Created by Justin Bagley on Tue, Mar 5 11:32:42 CST 2019.
-Copyright (c) 2019 Justin C. Bagley. All rights reserved.
-"
-
-if [[ "$1" == "-h" ]] || [[ "$1" == "--help" ]]; then
-	echo "$USAGE"
-	exit
-fi
-
-if [[ "$1" == "-V" ]] || [[ "$1" == "--version" ]]; then
-	echo "$(basename $0) $VERSION";
-	exit
-fi
-
-############ PARSE THE OPTIONS
-while getopts 'i:' opt ; do
-  case $opt in
-## Script options:
-    i) MY_INPUT_FILE_TYPE=$OPTARG ;;
-
-## Missing and illegal options:
-    :) printf "Missing argument for -%s\n" "$OPTARG" >&2
-       echo "$USAGE" >&2
-       exit 1 ;;
-   \?) printf "Illegal option: -%s\n" "$OPTARG" >&2
-       echo "$USAGE" >&2
-       exit 1 ;;
-  esac
-done
-
-############ SKIP OVER THE PROCESSED OPTIONS
-############ Check for mandatory positional parameters
-shift $((OPTIND-1)) 
-if [ $# -lt 2 ]; then
-	echo "WARNING!  | $(date) |          Missing mandatory positional parameters. Quitting... "
-	echo ""
-	echo "$USAGE"
+if [[ -f "${UTILS_LOCATION}" ]]; then
+  source "${UTILS_LOCATION}"
+else
+  echo "Please find the file util.sh and add a reference to it in this script. Exiting..."
   exit 1
 fi
-USER_SPEC_ASSIGNMENT_FILE="$1"
-USER_SPEC_PATH="$2"
 
-############ SET AND MOVE INTO WORKING DIRECTORY
-############ Set <workingDir>
-if [[ "$USER_SPEC_PATH" = "$(printf '%q\n' "$(pwd)")" ]] || [[ "$USER_SPEC_PATH" = "." ]]; then
-	MY_CWD="$(printf '%q\n' "$(pwd)" | sed 's/\\//g')"
-	echo "INFO      | $(date) |          Setting working directory to:  "
-	echo "$MY_CWD "
-elif [[ "$USER_SPEC_PATH" != "$(printf '%q\n' "$(pwd)")" ]]; then
-	if [[ "$USER_SPEC_PATH" = ".." ]] || [[ "$USER_SPEC_PATH" = "../" ]] || [[ "$USER_SPEC_PATH" = "..;" ]] || [[ "$USER_SPEC_PATH" = "../;" ]]; then
-		cd ..;
-		MY_CWD="$(printf '%q\n' "$(pwd)" | sed 's/\\//g')"
-		echo "INFO      | $(date) |          Setting working directory to:  "
-		echo "$MY_CWD "
-	else
-		MY_CWD=$USER_SPEC_PATH
-		cd "$MY_CWD"
-		echo "INFO      | $(date) |          Setting working directory to user-specified dir:  "	
-		echo "$MY_CWD "
-	fi
+
+# Source shared functions and variables
+# -----------------------------------
+
+FUNCS_LOCATION="${SCRIPT_PATH}/../lib/sharedFunctions.sh" # Update this path to find the shared functions.
+VARS_LOCATION="${SCRIPT_PATH}/../lib/sharedVariables.sh" # Update this path to find the shared variables.
+
+if [[ -f "${FUNCS_LOCATION}" ]] && [[ -f "${VARS_LOCATION}" ]]; then
+  source "${FUNCS_LOCATION}" ;
+  source "${VARS_LOCATION}" ;
 else
-	echo "WARNING!  | $(date) |          Null working directory path. Quitting... "
-	exit 1
+  echo "Please find the files sharedFunctions.sh and sharedVariables.sh and add references to them in this script. Exiting... "
+  exit 1
 fi
 
 
+# trapCleanup Function
+# -----------------------------------
+# Any actions that should be taken if the script is prematurely
+# exited.  Always call this function at the top of your script.
+# -----------------------------------
+function trapCleanup() {
+  echo ""
+  # Delete temp files, if any
+  if is_dir "${tmpDir}"; then
+    rm -r "${tmpDir}"
+  fi
+  die "Exit trapped. In function: '${FUNCNAME[*]}'"
+}
+
+# safeExit
+# -----------------------------------
+# Non destructive exit for when script exits naturally.
+# Usage: Add this function at the end of every script.
+# -----------------------------------
+function safeExit() {
+  # Delete temp files, if any
+  if is_dir "${tmpDir}"; then
+    rm -r "${tmpDir}"
+  fi
+  trap - INT TERM EXIT
+  exit
+}
+
+# Set Flags
+# -----------------------------------
+# Flags which can be overridden by user input.
+# Default values are below
+# -----------------------------------
+quiet=false
+printLog=false
+verbose=false
+force=false
+strict=false
+debug=false
+args=()
+
+# Set Temp Directory
+# -----------------------------------
+# Create temp directory with three random numbers and the process ID
+# in the name.  This directory is removed automatically at exit.
+# -----------------------------------
+tmpDir="/tmp/${SCRIPT_NAME}.$RANDOM.$RANDOM.$RANDOM.$$"
+(umask 077 && mkdir "${tmpDir}") || {
+  die "Could not create temporary directory! Exiting."
+}
+
+# Logging
+# -----------------------------------
+# Log is only used when the '-l' flag is set.
+#
+# To never save a logfile change variable to '/dev/null'
+# Save to Desktop use: $HOME/Desktop/${SCRIPT_BASENAME}.log
+# Save to standard user log location use: $HOME/Library/Logs/${SCRIPT_BASENAME}.log
+# -----------------------------------
+logFile="$HOME/Library/Logs/${SCRIPT_BASENAME}.log"
+
+# Check for Dependencies
+# -----------------------------------
+# Arrays containing package dependencies needed to execute this script.
+# The script will fail if dependencies are not installed.  For Mac users,
+# most dependencies can be installed automatically using the package
+# manager 'Homebrew'.  Mac applications will be installed using
+# Homebrew Casks. Ruby and gems via RVM.
+# -----------------------------------
+homebrewDependencies=()
+caskDependencies=()
+gemDependencies=()
+
+
+
+
+function renameForStarBEAST2 () {
+
 ######################################## START ###########################################
+##########################################################################################
 
-renameForStarBeast2 () {
+echo "INFO      | $(date) |----------------------------------------------------------------"
+echo "INFO      | $(date) | renameForStarBEAST2, v1.2.0 March 2019  (part of PIrANHA v1.0.0)"
+echo "INFO      | $(date) | Copyright (c) 2019 Justin C. Bagley. All rights reserved.      "
+echo "INFO      | $(date) |----------------------------------------------------------------"
 
+######################################## START ###########################################
+echo "INFO      | $(date) | Step #1: Set up workspace and check machine type. "
+############ SET WORKING DIRECTORY AND CHECK MACHINE TYPE
+## Nothing to do for working dir because script executes in current working dir (of execution/
+## sourcing). Set to run in current working dir, and echo cwd to screen:
+USER_SPEC_PATH="$(printf '%q\n' "$(pwd)")";
+echoCDWorkingDir
+MY_WORKING_DIR="$(pwd -P)";
+
+#echo "INFO      | $(date) |          Checking machine type... "
+checkMachineType
+#echo "INFO      | $(date) |               Found machine type ${machine}. "
+
+
+echo "INFO      | $(date) | Step #2: Read and process ASTRAL-III style taxon-assignment file. "
 ## Split input ASTRAL-III-type taxon-assignment file into separate .tmp files for species
 ## (*_assign_names.tmp) and individuals or tips (*_assign_tips.tmp)
 echo "INFO      | $(date) |          Splitting up assignment file... "
@@ -126,6 +161,7 @@ perl -pe $'s/\ /\t/g' "$USER_SPEC_ASSIGNMENT_FILE" | cut -f 3- > ./species_assig
 MY_NUM_SPECIES_ASSIGN="$(wc -l ./species_assign_names.tmp | sed 's/\ //g; s/\.\/.*//g')"
 MY_NUM_TIP_INDS="$(perl -pe $'s/\ /\n/g; s/\t/\n/g' ./species_assign_tips.tmp | sort -u | wc -l | sed 's/\ //g; s/\.\/.*//g')"
 
+echo "INFO      | $(date) | Step #3: Run main parts of script that conduct renaming. "
 ## Main script loop sets run conditional on input file type:
 if [[ "$MY_INPUT_FILE_TYPE" = "phylip" ]]; then
 echo "INFO      | $(date) |          Assignment file: $USER_SPEC_ASSIGNMENT_FILE "
@@ -139,11 +175,11 @@ for i in ./*.phy; do
 		while read TIP_NAME; do 
 			MY_SPECIES="$(sed -n ${MY_COUNT}p ./species_assign_names.tmp)"; 
 			MY_TIP_NAMES="$TIP_NAME"; 
-	#		
+	
 				for j in $MY_TIP_NAMES; do 
 					perl -p -i -e 's/'"$j"'/'"$MY_SPECIES"'\_'"$j"'/g' "$i"; 
 				done; 
-	#
+
 			echo "INFO      | $(date) |          Finished processing species $((MY_COUNT++))... "; 
 		done < ./species_assign_tips.tmp
 	)
@@ -155,6 +191,7 @@ echo "INFO      | $(date) |          Assignment file: $USER_SPEC_ASSIGNMENT_FILE
 echo "INFO      | $(date) |          Number of species assignments: $MY_NUM_SPECIES_ASSIGN "
 echo "INFO      | $(date) |          Number of tips: $MY_NUM_TIP_INDS "
 echo "INFO      | $(date) |          Renaming FASTA MSAs in current working directory... "
+
 for i in ./*.fas; do
 	echo "INFO      | $(date) |          $i "
 	MY_COUNT=1
@@ -162,29 +199,134 @@ for i in ./*.fas; do
 		while read TIP_NAME; do 
 			MY_SPECIES="$(sed -n ${MY_COUNT}p ./species_assign_names.tmp)"; 
 			MY_TIP_NAMES="$TIP_NAME"; 
-	#		
+	
 				for j in $MY_TIP_NAMES; do 
 					perl -p -i -e 's/'"$j"'/'"$MY_SPECIES"'\_'"$j"'/g' "$i"; 
 				done; 
-	#
+
 			echo "INFO      | $(date) |          Finished processing species $((MY_COUNT++))... "; 
 		done < ./species_assign_tips.tmp
 	)
 done
 fi
 
+echo "INFO      | $(date) | Step #4: Clean up workspace by deleting temporary files created during run. "
+echo "INFO      | $(date) |          Removing temporary files... "
 rm ./species_assign_names.tmp ./species_assign_tips.tmp;
+
+echo "----------------------------------------------------------------------------------------------------------"
+
+##########################################################################################
+######################################### END ############################################
 
 }
 
-## DON'T FORGET TO RUN THE FUNCTION!
-renameForStarBeast2
 
 
+############ SCRIPT OPTIONS
+## OPTION DEFAULTS ##
+MY_INPUT_FILE_TYPE=phylip
+USER_SPEC_ASSIGNMENT_FILE=assignment.txt
 
-#
-#
-#
-######################################### END ############################################
+############ CREATE USAGE & HELP TEXTS
+USAGE="Usage: $(basename $0) [OPTION]...
 
-exit 0
+ ${bold}Options:${reset}
+  -f   input file type (def: phylip; other: fasta) type of file(s) in <workingDir> that 
+       will be renamed (assumes .phy or .fas extensions for PHYLIP or FASTA format, 
+       respectively)
+  -a   assignmentFile (def: assignment.txt) ASTRAL-III style assignment file detailing which
+       individual tips correspond to which species or taxa
+  -h   help text (also: --help) echo this help text and exit
+  -V   version (also: --version) echo version and exit
+
+ ${bold}INFO${reset}
+ For best results, species assignments in the assignment file should be given as simple
+ alphanumeric names with no spaces, hyphens, underscores, or nonalphanumeric characters
+ (e.g. the assignment 'unimaculatus' gave no errors in testing).
+
+ ${bold}Usage examples:${reset}
+    piranha -f renameForStarBEAST2.sh --args='-f phylip -a assignment.txt'
+
+ ${bold}CITATION${reset}
+ Bagley, J.C. 2019. PIrANHA v1.0.0. GitHub repository, Available at:
+	<https://github.com/justincbagley/PIrANHA>.
+
+ Created by Justin Bagley on Tue, Mar 5 11:32:42 CST 2019.
+ Copyright (c) 2019 Justin C. Bagley. All rights reserved.
+"
+
+if [[ "$1" == "-h" ]] || [[ "$1" == "--help" ]]; then
+	echo "$USAGE"
+	exit
+fi
+
+if [[ "$1" == "-V" ]] || [[ "$1" == "--version" ]]; then
+	echo "$(basename $0) $VERSION";
+	exit
+fi
+
+############ PARSE THE OPTIONS
+while getopts 'f:a:' opt ; do
+  case $opt in
+## renameForStarBEAST2 options:
+    f) MY_INPUT_FILE_TYPE=$OPTARG ;;
+    a) USER_SPEC_ASSIGNMENT_FILE=$OPTARG ;;
+## Missing and illegal options:
+    :) printf "Missing argument for -%s\n" "$OPTARG" >&2
+       echo "$USAGE" >&2
+       exit 1 ;;
+   \?) printf "Illegal option: -%s\n" "$OPTARG" >&2
+       echo "$USAGE" >&2
+       exit 1 ;;
+  esac
+done
+
+# ############ SKIP OVER THE PROCESSED OPTIONS
+# ############ Check for mandatory positional parameters
+# shift $((OPTIND-1)) 
+# if [ $# -lt 2 ]; then
+# 	echo "WARNING!  | $(date) |          Missing mandatory positional parameters. Quitting... "
+# 	echo ""
+# 	echo "$USAGE"
+#   exit 1
+# fi
+# USER_SPEC_ASSIGNMENT_FILE="$1"
+# USER_SPEC_PATH="$2"
+
+
+# ############# ############# #############
+# ##       TIME TO RUN THE SCRIPT        ##
+# ##                                     ##
+# ## You shouldn't need to edit anything ##
+# ## beneath this line                   ##
+# ##                                     ##
+# ############# ############# #############
+
+# Trap bad exits with your cleanup function
+trap trapCleanup EXIT INT TERM
+
+# Set IFS to preferred implementation
+IFS=$'\n\t'
+
+# Exit on error. Append '||true' when you run the script if you expect an error.
+set -o errexit
+
+# Run in debug mode, if set
+if ${debug}; then set -x ; fi
+
+# Exit on empty variable
+if ${strict}; then set -o nounset ; fi
+
+# Bash will remember & return the highest exitcode in a chain of pipes.
+# This way you can catch the error in case mysqldump fails in `mysqldump |gzip`, for example.
+set -o pipefail
+
+# Invoke the checkDependenices function to test for Bash packages.  Uncomment if needed.
+# checkDependencies
+
+# Run the script
+renameForStarBEAST2
+
+# Exit cleanly
+safeExit
