Add files via upload

diff --git a/bin/ExaBayesPostProc b/bin/ExaBayesPostProc
--- a/bin/ExaBayesPostProc
+++ b/bin/ExaBayesPostProc
@@ -379,13 +379,6 @@ echo ""
 
 
 
-############ SCRIPT OPTIONS
-## OPTION DEFAULTS ##
-MY_NEXUS=NULL
-MY_NUM_REPLICATE_RUNS=2
-MY_CREDIBLE_INT=50
-MY_REL_BURNIN_PROPORTION=0.25
-
 ############ CREATE USAGE & HELP TEXTS
 USAGE="Usage: $(basename $0) [OPTION]...
 
@@ -452,7 +445,8 @@ USAGE="Usage: $(basename $0) [OPTION]...
  Copyright (c) 2016–2019 Justin C. Bagley. All rights reserved.
 "
 
-if [[ "$1" == "-h" ]] || [[ "$1" == "--help" ]]; then
+
+if [[ "$1" == "-h" ]] || [[ "$1" == "-help" ]]; then
 	echo "$USAGE"
 	exit
 fi
@@ -462,22 +456,76 @@ if [[ "$1" == "-V" ]] || [[ "$1" == "--version" ]]; then
 	exit
 fi
 
-############ PARSE THE OPTIONS
-while getopts 'r:c:b:' opt ; do
-  case $opt in
-## ExaBayesPostProc options:
-    t) MY_NUM_REPLICATE_RUNS=$OPTARG ;;
-    t) MY_CREDIBLE_INT=$OPTARG ;;
-    t) MY_REL_BURNIN_PROPORTION=$OPTARG ;;
-## Missing and illegal options:
-    :) printf "Missing argument for -%s\n" "$OPTARG" >&2
-       echo "$USAGE" >&2
-       exit 1 ;;
-   \?) printf "Illegal option: -%s\n" "$OPTARG" >&2
-       echo "$USAGE" >&2
-       exit 1 ;;
-  esac
-done
+############ CHECK ARGUMENTS
+	# echo "$@"; echo "$#"; echo "$1" 
+	# for i in "$@"; do
+	# 	echo "$i";
+	# done
+	# MY_ARGS="$(echo "$@" | perl -pe $'s/\ /\n/')"
+	# echo "$MY_ARGS"
+
+
+############ CAPTURE ARGUMENTS, SEND TO FILE FOR PARSING
+	if [[ -s ./args.tmp ]]; then rm ./args.tmp ; fi ;
+	if [[ -s ./args.txt ]]; then rm ./args.txt ; fi ;
+	if [[ -s ./*.tmp ]]; then rm ./*.tmp ; fi ;
+
+	ALL_MY_ARGUMENTS="$(echo "$@")"
+	echo "$ALL_MY_ARGUMENTS" > ./args.txt
+	perl -p -i -e $'s/\-/\n\-/g' ./args.txt
+	#perl -p -i -e $'s/\ /\n/g' ./args.txt
+	#wc -l ./args.txt | perl -pe 's/\.\/args\.txt.*//g' | perl -pe 's/\ //g'
+
+
+############ MANUALLY PARSE THE OPTIONS FROM ARGS
+
+### SET OPTIONS TO DEFAULT VALUES, EXCEPT WHERE VALUES WERE READ IN FROM USER ARGS
+	if [[  "$(grep -h '\-i' ./args.txt | wc -l | perl -pe 's/\ //g')" = "0" ]]; then
+		MY_NEXUS=NULL ;
+	else 
+		MY_ARG="$(grep -h '\-i' ./args.txt | perl -pe 's/\-i//g' | perl -pe 's/\ //g')";
+		MY_NEXUS="$MY_ARG" ;
+	fi
+#
+	if [[  "$(grep -h '\-r' ./args.txt | wc -l | perl -pe 's/\ //g')" = "0" ]]; then
+		MY_NUM_REPLICATE_RUNS=2 ;
+	else 
+		MY_ARG="$(grep -h '\-r' ./args.txt | perl -pe 's/\-r//g' | perl -pe 's/\ //g')";
+		MY_NUM_REPLICATE_RUNS="$MY_ARG" ;
+	fi
+#
+	if [[  "$(grep -h '\-c' ./args.txt | wc -l | perl -pe 's/\ //g')" = "0" ]]; then
+		MY_CREDIBLE_INT=50 ;
+	else 
+		MY_ARG="$(grep -h '\-c' ./args.txt | perl -pe 's/\-c//g' | perl -pe 's/\ //g')";
+		MY_CREDIBLE_INT="$MY_ARG" ;
+	fi
+#
+	if [[  "$(grep -h '\-b' ./args.txt | wc -l | perl -pe 's/\ //g')" = "0" ]]; then
+		MY_REL_BURNIN_PROPORTION=0.25 ;
+	else 
+		MY_ARG="$(grep -h '\-b' ./args.txt | perl -pe 's/\-b//g' | perl -pe 's/\ //g')";
+		MY_REL_BURNIN_PROPORTION="$MY_ARG" ;
+	fi
+#
+
+# ############ PARSE THE OPTIONS
+# while getopts 'i:r:c:b:' opt ; do
+#   case $opt in
+# ## ExaBayesPostProc options:
+#     i) MY_NEXUS=$OPTARG ;;
+#     r) MY_NUM_REPLICATE_RUNS=$OPTARG ;;
+#     c) MY_CREDIBLE_INT=$OPTARG ;;
+#     b) MY_REL_BURNIN_PROPORTION=$OPTARG ;;
+# ## Missing and illegal options:
+#     :) printf "Missing argument for -%s\n" "$OPTARG" >&2
+#        echo "$USAGE" >&2
+#        exit 1 ;;
+#    \?) printf "Illegal option: -%s\n" "$OPTARG" >&2
+#        echo "$USAGE" >&2
+#        exit 1 ;;
+#   esac
+# done
 
 
 # ############# ############# #############
