Updates to bin/ functions

diff --git a/bin/MrBayesPostProc b/bin/MrBayesPostProc
--- a/bin/MrBayesPostProc
+++ b/bin/MrBayesPostProc
@@ -6,10 +6,10 @@
 # |                                                                                      #
 #                                                                                        #
 # File: MrBayesPostProc.sh                                                               #
-  version="v1.8.0"                                                                       #
+  version="v1.9.0"                                                                       #
 # Author: Justin C. Bagley                                                               #
 # Date: Created by Justin Bagley on Thu, 4 May 2017 22:39:41 -0400.                      #
-# Last update: April 7, 2020                                                             #
+# Last update: April 12, 2020                                                            #
 # Copyright (c) 2017-2020 Justin C. Bagley. All rights reserved.                         #
 # Please report bugs to <bagleyj@umsl.edu>.                                              #
 #                                                                                        #
@@ -143,7 +143,7 @@ MrBayesPostProc () {
 ##########################################################################################
 
 echo "INFO      | $(date) |----------------------------------------------------------------"
-echo "INFO      | $(date) | MrBayesPostProc, v1.8.0 April 2020                             "
+echo "INFO      | $(date) | MrBayesPostProc, v1.9.0 April 2020                             "
 echo "INFO      | $(date) | Copyright (c) 2017–2020 Justin C. Bagley. All rights reserved. "
 echo "INFO      | $(date) |----------------------------------------------------------------"
 
@@ -161,7 +161,47 @@ checkMachineType
 ## START DEBUG MODE
 if [[ "$MY_DEBUG_MODE_SWITCH" != "0" ]]; then set -xv; fi
 
-echo "INFO      | $(date) | Step #2: Fix NEXUS filenames, check whether MrBayes is installed, and attempt to set name or path to MrBayes executable. "
+
+###
+if [[ "$MY_INPUT_NEXUS" != "NULL" ]] && [[ -s "$MY_INPUT_NEXUS" ]] && [[ "$MY_MRBAYES_FILENAME" != "NULL" ]]; then 
+
+	echo "INFO      | $(date) | Step #2: Prepare input NEXUS, check whether MrBayes is installed, and attempt to set name or path to MrBayes executable. "
+	MY_NEXUS_EXTENSION=".${MY_INPUT_NEXUS##*.}";
+	MY_NEXUS_BASENAME="$(echo "${MY_INPUT_NEXUS%%.*}")";
+	if [[ "$MY_NEXUS_EXTENSION" = ".NEX" ]]; then 
+		mv "$MY_INPUT_NEXUS" "$MY_NEXUS_BASENAME".nex ;
+		MY_INPUT_NEXUS="$MY_NEXUS_BASENAME".nex ;
+	fi
+
+if [[ "$MY_INPUT_NEXUS" != "NULL" ]] && [[ -s "$MY_INPUT_NEXUS" ]] && [[ "$MY_MRBAYES_FILENAME" = "NULL" ]]; then 
+
+	echo "INFO      | $(date) | Step #2: Prepare input NEXUS, check whether MrBayes is installed, and attempt to set name or path to MrBayes executable. "
+	MY_NEXUS_EXTENSION=".${MY_INPUT_NEXUS##*.}";
+	MY_NEXUS_BASENAME="$(echo "${MY_INPUT_NEXUS%%.*}")";
+	if [[ "$MY_NEXUS_EXTENSION" = ".NEX" ]]; then 
+		mv "$MY_INPUT_NEXUS" "$MY_NEXUS_BASENAME".nex ;
+		MY_INPUT_NEXUS="$MY_NEXUS_BASENAME".nex ;
+	fi
+	## $MY_MRBAYES_FILENAME is the name of the output of the run, which will be the root/prefix 
+	## of each output file. Here we have to guess this information because the user did not provide it
+	## with the -m flag as expected. Echo a warning and attempt to guess the correct basename:
+	echo "WARNING!  | $(date) | No MrBayes basename (output file name prefix) provided! "
+	echo "INFO      | $(date) | Guessing input NEXUS file (first file after listing), but this could lead to errors.  "
+	MY_MRBAYES_FILENAME="$(ls | grep -n ".mcmc" | sed -n 's/.*://p' | sed 's/\.mcmc$//g')";
+	
+elif [[ "$MY_INPUT_NEXUS" != "NULL" ]] && [[ ! -s "$MY_INPUT_NEXUS" ]]; then 
+
+	echo "WARNING!  | $(date) | Found no NEXUS file named $MY_INPUT_NEXUS in current directory. "
+	echo "ERROR     | $(date) | Quitting... "
+	exit 1 ;
+
+elif [[ "$MY_INPUT_NEXUS" = "NULL" ]]; then 
+
+	echo "INFO      | $(date) | Step #2: Prepare input NEXUS, check whether MrBayes is installed, and attempt to set name or path to MrBayes executable. "
+	echo "WARNING!  | $(date) | No input NEXUS filename provided! "
+	echo "INFO      | $(date) | Guessing input NEXUS file (first file after listing), but this could lead to errors.  "
+	echo "INFO      | $(date) | Stop this run (Ctrl + C) or check output files carefully... "
+
 	## First, fix NEXUS filename extensions to conform to the standard ('.nex') expected by
 	## the script. For now, this only handles the cases of the '.NEX' extension and the
 	## '.nexus' extension, fixing both of these.
@@ -186,39 +226,26 @@ echo "INFO      | $(date) | Step #2: Fix NEXUS filenames, check whether MrBayes 
 	## This script was written to expect only a single NEXUS file in pwd; however, users 
 	## will probably from time to time mistakenly run the script on a directory with 
 	## multiple NEXUS files. Here, we can account for this by taking the first .nex file
-	## found in the directory, by using the following line instead of MY_NEXUS=./*.nex 
+	## found in the directory, by using the following line instead of MY_INPUT_NEXUS=./*.nex 
 	## (which would only work with 1 file). $MY_MRBAYES_FILENAME is the name of the output
 	## of the run, which will be the root/prefix of each output file. 
 
 	if [[ -s "$(nex_FILES=./*.nex; echo $nex_FILES | head -n1 | sed 's/\ .*//g')" ]]; then 
-		MY_NEXUS="$(ls ./*.nex | head -n1 | sed 's/\ //g')";
+		MY_INPUT_NEXUS="$(ls ./*.nex | head -n1 | sed 's/\ //g')";
 	fi
 	MY_MRBAYES_FILENAME="$(ls | grep -n ".mcmc" | sed -n 's/.*://p' | sed 's/\.mcmc$//g')";
+fi
+###
 
 
-	## In addition to fixing NEXUS filenames and getting only one NEXUS file for use, another
-	## requirement for running this program is having the MrBayes executable name that is 
-	## available from the command line, or having the path to the MrBayes executable. In
-	## previous versions of this program, I had the user add the appropriate path to a 
-	## variable named 'mb_path' in a configuration file named 'mrbayes_post_proc.cfg' in 
-	## the run directory. I think grepped the path from the configuration file as follows:
-	#
-	#	MY_LOC_SC_MB_PATH="$(grep -n "mb_path" ./mrbayes_post_proc.cfg | awk -F"=" '{print $NF}')";
-	#
-	## This simply is not acceptable in a generalized software program that we want anyone
-	## to be able to use, and to use efficiently. I decided to scrap the configuration file,
-	## give the user the option to pass the executable name or path using a new option (-p flag).
-	## If user does not pass a value with the -p flag, then I will attempt to determine whether
-	## MrBayes is available as 'mb' or 'mrbayes' during the MrBayes software check below.
-
-if [[ "$MY_LOC_SC_MB_PATH" != "NULL" ]]; then
+	if [[ "$MY_LOC_SC_MB_PATH" != "NULL" ]]; then
 		echo "INFO      | $(date) |          <MrBayesPath> parameter is _not_ null. Checking user-specified MrBayes executable name or path on your system..."
 		MY_MRBAYES_EXECUT_CHECK="$(which $(echo $MY_LOC_SC_MB_PATH))"
 		if [[ -s "$MY_MRBAYES_EXECUT_CHECK" ]]; then
 			echo "INFO      | $(date) |          Check passed. MrBayes is installed on your machine..."
 		fi
-fi
-if [[ "$MY_LOC_SC_MB_PATH" = "NULL" ]]; then
+	fi
+	if [[ "$MY_LOC_SC_MB_PATH" = "NULL" ]]; then
 		echo "INFO      | $(date) |          <MrBayesPath> parameter is null. Attempting to determine MrBayes executable name or path on your system..."
 		MY_MRBAYES_EXECUT_CHECK1="$(which mb)";
 		MY_MRBAYES_EXECUT_CHECK2="$(which mrbayes)";
@@ -232,25 +259,25 @@ if [[ "$MY_LOC_SC_MB_PATH" = "NULL" ]]; then
 			fi
 			echo "INFO      | $(date) |          <MrBayesPath> parameter was set to: ${MY_LOC_SC_MB_PATH} "
 		else
-			echo "WARNING!  | $(date) |          Check FAILED. MrBayes is apparently _not_ installed on your machine..."
+			echo "WARNING!  | $(date) |          Check FAILED. MrBayes is apparently _not_ installed on your machine."
 			echo "INFO      | $(date) |          Please install or reinstall MrBayes, or make it available from the command line (e.g. using an alias) as 'mb' or 'mrbayes'. "
 			echo "INFO      | $(date) |          Find more information at the MrBayes v3.2+ website, here: http://nbisweden.github.io/MrBayes/, or "
 			echo "INFO      | $(date) |          if you have Anaconda/Miniconda installed, you could try a Bioconda install of MrBayes as follows: $ conda install -c bioconda mrbayes ; ## info: https://anaconda.org/bioconda/mrbayes"
 			echo "ERROR     | $(date) |          Quitting..."
 			exit 1 ;
 		fi
-fi
+	fi
 
 
 echo "INFO      | $(date) | Step #3: Remove MrBayes block from NEXUS file. "
 
-	MY_MRBAYES_BLOCK_START="$(grep -n "BEGIN MrBayes\|Begin MrBayes\|BEGIN mrbayes\|Begin mrbayes\|begin mrbayes" $MY_NEXUS | sed 's/\:.*//; s/\ //g')";
+	MY_MRBAYES_BLOCK_START="$(grep -n "BEGIN MrBayes\|Begin MrBayes\|BEGIN mrbayes\|Begin mrbayes\|begin mrbayes" $MY_INPUT_NEXUS | sed 's/\:.*//; s/\ //g')";
 	if [[ "$MY_MRBAYES_BLOCK_START" -gt "0" ]] || [[ -s "$MY_MRBAYES_BLOCK_START" ]]; then
 		MY_HEADSTOP="$(calc $MY_MRBAYES_BLOCK_START-1)";
-		head -n"$MY_HEADSTOP" "$MY_NEXUS" > simple.nex ;
+		head -n"$MY_HEADSTOP" "$MY_INPUT_NEXUS" > simple.nex ;
 	elif [[ ! "$MY_MRBAYES_BLOCK_START" -gt "0" ]]; then
 		echo "INFO      | $(date) |          NEXUS file contains no MrBayes block. Renaming NEXUS to 'simple.nex'... "
-		mv "$MY_NEXUS" simple.nex ;
+		mv "$MY_INPUT_NEXUS" simple.nex ;
 	fi	
 
 
@@ -264,7 +291,7 @@ sumt Filename=${MY_MRBAYES_FILENAME} relburnin=yes burninfrac=${MY_RELBURNIN_FRA
 sump Filename=${MY_MRBAYES_FILENAME} relburnin=yes burninfrac=${MY_RELBURNIN_FRAC}
 quit" > ./batch.txt
 
-##--Flow control. Check to make sure MrBayes batch file was successfully created.
+## Flow control. Check to make sure MrBayes batch file was successfully created.
     if [[ -f ./batch.txt ]]; then
         echo "INFO      | $(date) |          MrBayes batch file ('batch.txt') was successfully created. "
     else
@@ -274,10 +301,10 @@ quit" > ./batch.txt
 
 
 echo "INFO      | $(date) | Step #5: Summarize run and compute consensus tree in MrBayes. "
-##--This calls the commands in the batch.txt file to run within MrBayes, opening the 
-##--simplified nexus file and creating summaries of the tree and run parameters as wellas
-##--computing a majority-rule consensus tree with Bayesian posterior probabilities 
-##--annotated along each node.
+## This calls the commands in the batch.txt file to run within MrBayes, opening the 
+## simplified nexus file and creating summaries of the tree and run parameters as wellas
+## computing a majority-rule consensus tree with Bayesian posterior probabilities 
+## annotated along each node.
 
     $MY_LOC_SC_MB_PATH  < ./batch.txt > Mrbayes_sumtp_log.txt &		## Use batch to run MrBayes.
 
@@ -315,14 +342,10 @@ echo "INFO      | $(date) | Step #6: Clean up files in working dir. "
 		if [[ -f ./SS_batch.txt ]]; then rm ./SS_batch.txt; fi
 	fi
 
-	if [[ ! -z ./*.tmp ]]; then rm ./*.tmp ; fi
+	if [[ ! -z $(ls ./*.tmp) ]]; then rm ./*.tmp ; fi
 	if [[ -s ./args.txt ]]; then rm ./args.txt ; fi 	## Remove arguments file generated when parsing the options.
 
-
-#echo "INFO      | $(date) | Done with post-processing of MrBayes results using MrBayesPostProc. "
-#echo "INFO      | $(date) | Bye. 
-#"
-
+echo "INFO      | $(date) | Done."
 echo "----------------------------------------------------------------------------------------------------------"
 if [[ "$MY_SS_ANALYSIS_SWITCH" -eq "1" ]]; then
 	echo "output file(s): ./Mrbayes_sumtp_log.txt  "
@@ -342,6 +365,7 @@ else
 fi
 echo ""
 
+
 ## END DEBUG MODE
 if [[ "$MY_DEBUG_MODE_SWITCH" != "0" ]]; then set +xv; fi
 ######
@@ -354,14 +378,17 @@ if [[ "$MY_DEBUG_MODE_SWITCH" != "0" ]]; then set +xv; fi
 
 
 ############ CREATE USAGE & HELP TEXTS
-USAGE="Usage: $(basename $0) [OPTION]...
+USAGE="Usage: $(basename "$0") [OPTION]...
 
  ${bold}Options:${reset}
-  -p   MrBayesPath (def: NULL) takes name of MrBayes v3.2+ executable as available from the 
-       user's command line, or the absolute path to a working MrBayes executable
+  -i   inputNEXUS (def: NULL) input NEXUS alignment file
+  -m   MrBayesBasename (def: NULL) basename (file minus extension) of .mcmc file output by
+       MrBayes run from which files are being processed
+  -p   MrBayesPath (def: NULL) name of MrBayes v3.2+ executable as available from user's 
+       command line, or absolute path to a working MrBayes executable
   -b   relBurninFrac (def: $MY_RELBURNIN_FRAC) fraction of trees to discard as 'burn-in'
   -s   SS (def: 0, no stepping-stone (SS) analysis conducted; 1, run SS analysis) allows
-       calling stepping-stone analysis starting from NEXUS in current <workingDir>
+       calling stepping-stone analysis starting from NEXUS in current directory
   -g   SSnGen (def: $MY_SS_NGEN) if 1 for SS above, allows specifying the number of total 
        SS sampling iterations (uses default number of steps, 50; total iterations will 
        be split over 50 steps) 
@@ -375,21 +402,35 @@ USAGE="Usage: $(basename $0) [OPTION]...
 
  ${bold}OVERVIEW${reset}
  Runs a simple script for post-processing results of a MrBayes v3.2+ (Ronquist et al. 2012)
- run, whose output files are assumed to be in the current working directory. This script preps 
- the output files in pwd, and then summarizes trees and their posterior probabilities (sumt), 
+ run, whose output files are located in the current working directory. This script prepares
+ the output files, and then it summarizes trees and their posterior probabilities (sumt), 
  and parameters of the specified model (sump), using MrBayes. Options are provided for specifying 
- the burnin fraction, and for calling stepping-stone analysis (Xie et al. 2011; Baele et al.
- 2012) to robustly estimate the log marginal likelihood of the model/analysis, whose details 
- must be provided in a MrBayes block at the end of the input NEXUS file in the current dir.
+ the input NEXUS file (-i flag), MrBayes output file name (basename; -m flag), MrBayes 
+ executable path or filename (-p flag), burn-in fraction (-b flag), and for calling stepping-
+ stone analysis (pass details with -s, -g, and -d flags; Xie et al. 2011; Baele et al. 2012) 
+ to robustly estimate the log marginal likelihood of the model/analysis, whose details must 
+ be provided in a MrBayes block at the end of the input NEXUS file in the current dir.
 	This program runs on UNIX-like and Linux systems using commonly distributed utility 
  software, with usage obtained by running the script with the -h flag. It has been tested
  on macOS High Sierra (v10.13+) and Mojave but should work on many earlier versions or
- Linux (tested on CentOS 6/7). The key dependency is MrBayes v3.2+, so the program checks
+ Linux (tested on CentOS 5/6/7). The key dependency is MrBayes v3.2+, so the program checks
  whether MrBayes is installed and available from the command line, and will print messages 
  and quit if MrBayes is not found. The user can pre-emptively solve this problem by passing
  the program the name or absolute path to a working MrBayes executable using the -p flag (e.g.
  on the author's machine, MrBayes is available as simply 'mb', so I add '-p mb' to my call 
  to MrBayesPostProc).
+
+ ${bold}Usage examples:${reset}
+ Call the program using PIrANHA, as follows:
+
+    Run with default settings (ymmv):
+    piranha -f MrBayesPostProc -i <inputNEXUS> -p <MrBayesPath>
+
+    Give full information for basic run:
+    piranha -f MrBayesPostProc -i <inputNEXUS> -m <MrBayesBasename> -p <MrBayesPath> -b <relBurninFrac>
+
+    Show this help text and exit:
+    piranha -f MrBayesPostProc -h
 
  ${bold}CITATION${reset}
  Bagley, J.C. 2019. PIrANHA v0.3a2. GitHub repository, Available at:
@@ -448,6 +489,20 @@ fi
 ############ MANUALLY PARSE THE OPTIONS FROM ARGS
 
 ### SET OPTIONS TO DEFAULT VALUES, EXCEPT WHERE VALUES WERE READ IN FROM USER ARGS
+	if [[  "$(grep -h '\-i' ./args.txt | wc -l | perl -pe 's/\ //g')" = "0" ]]; then
+		MY_INPUT_NEXUS=NULL ;
+	else 
+		MY_ARG="$(grep -h '\-i' ./args.txt | perl -pe 's/\-i//g' | perl -pe 's/\ //g')";
+		MY_INPUT_NEXUS="$MY_ARG" ;
+	fi
+#
+	if [[  "$(grep -h '\-m' ./args.txt | wc -l | perl -pe 's/\ //g')" = "0" ]]; then
+		MY_MRBAYES_FILENAME=NULL ;
+	else 
+		MY_ARG="$(grep -h '\-m' ./args.txt | perl -pe 's/\-m//g' | perl -pe 's/\ //g')";
+		MY_MRBAYES_FILENAME="$MY_ARG" ;
+	fi
+#
 	if [[  "$(grep -h '\-p' ./args.txt | wc -l | perl -pe 's/\ //g')" = "0" ]]; then
 		MY_LOC_SC_MB_PATH=NULL ;
 	else 
diff --git a/bin/PHYLIPcleaner b/bin/PHYLIPcleaner
--- a/bin/PHYLIPcleaner
+++ b/bin/PHYLIPcleaner
@@ -6,10 +6,10 @@
 # |                                                                                      #
 #                                                                                        #
 # File: PHYLIPcleaner.sh                                                                 #
-  VERSION="v1.0.2"                                                                       #
+  VERSION="v1.1.1"                                                                       #
 # Author: Justin C. Bagley                                                               #
 # Date: Created by Justin Bagley on Sun, Feb 24 11:33:48 CDT 2019.                       #
-# Last update: April 6, 2020                                                             #
+# Last update: April 12, 2020                                                            #
 # Copyright (c) 2019-2020 Justin C. Bagley. All rights reserved.                         #
 # Please report bugs to <bagleyj@umsl.edu>.                                              #
 #                                                                                        #
@@ -140,7 +140,7 @@ PHYLIPcleaner () {
 ##########################################################################################
 
 echo "INFO      | $(date) |----------------------------------------------------------------"
-echo "INFO      | $(date) | PHYLIPcleaner, v1.0.2 April 2020                               "
+echo "INFO      | $(date) | PHYLIPcleaner, v1.1.1 April 2020                               "
 echo "INFO      | $(date) | Copyright (c) 2019-2020 Justin C. Bagley. All rights reserved. "
 echo "INFO      | $(date) |----------------------------------------------------------------"
 
@@ -155,9 +155,10 @@ if [[ "$MY_OUTPUT_FILE_SWITCH" != "NULL" ]]; then
 	echo "INFO      | $(date) | Output file switch activated. Logging output to file at ./output/${MY_OUTPUT_FILE_SWITCH} ... "
 fi
 
+############ STEP #1: SETUP 
 if [[ "$MY_VERBOSE_OUT_SWITCH" != "0" ]]; then
 	echo "INFO      | $(date) | Starting PHYLIPcleaner analysis... "
-	echo "INFO      | $(date) | Step #1: Set up workspace by defining useful environmental variables and functions, and check machine type. "
+	echo "INFO      | $(date) | Step #1: Set up workspace (e.g. functions, working directory) and check machine type. "
 fi
 ############ SET WORKING DIRECTORY AND CHECK MACHINE TYPE
 USER_SPEC_PATH="$(printf '%q\n' "$(pwd)")";
@@ -165,6 +166,11 @@ echoCDWorkingDir
 #echo "INFO      | $(date) |          Checking machine type... "
 checkMachineType
 #echo "INFO      | $(date) |               Found machine type ${machine}. "
+
+######
+## START DEBUG MODE
+if [[ "$MY_DEBUG_MODE_SWITCH" != "0" ]]; then set -xv; fi
+
 
 	if [[ "$MY_KEEP_PHYLIP_SWITCH" = "1" ]] && [[ ! -s ./orig_phylip/ ]]; then
 		mkdir orig_phylip/ ;
@@ -179,15 +185,19 @@ fi
 	(
 		for i in ./*.phy; do 
 
-			echo "INFO      | $(date) |          ###------    ${i}    ------### "
-
+			if [[ "$MY_VERBOSE_OUT_SWITCH" != "0" ]]; then
+				echo "INFO      | $(date) |          ###------    ${i}    ------### "
+			fi
+			
 			MY_ORIG_NTAX="$(head -n1 "$i" | sed 's/\ [0-9]*//g'| sed 's/[\]*//g')";
 
 			if [[ "$MY_KEEP_PHYLIP_SWITCH" = "1" ]]; then
 				cp -f "$i" orig_phylip/;
 			fi
 
-	echo "INFO      | $(date) |          Removing empty lines (newlines) and lines that have been commented out, if present... "
+	if [[ "$MY_VERBOSE_OUT_SWITCH" != "0" ]]; then
+		echo "INFO      | $(date) |          Removing empty lines (newlines) and lines that have been commented out, if present... "
+	fi
 	## If present, remove empty lines / newlines from current PHYLIP file, $i.
 		if [[ "$(grep -n '^[\s]*$' $i | wc -l | sed 's/\ //g' | perl -pe 's/\t//g')" -gt "0" ]]; then 
 			if [[ "${machine}" = "Mac" ]]; then
@@ -211,7 +221,9 @@ fi
 			fi
 		fi
 
+if [[ "$MY_VERBOSE_OUT_SWITCH" != "0" ]]; then
 	echo "INFO      | $(date) |          Checking for and removing individuals comprised entirely of undetermined sites (gaps, missing characters)... "
+fi
 	## Check and remove individuals with all missing data:
 			if [[ "${machine}" = "Mac" ]]; then
 				sed -i.bak '/\ [N\-]*$/d' "$i" ;
@@ -262,8 +274,10 @@ fi
 	
 ###
 if [[ "$MY_DEEP_CLEAN_SWITCH" = "1" ]]; then
-echo "WARNING!  | $(date) |          Experimental 'deep clean' option invoked. WARNING: this may cause errors. "
-echo "INFO      | $(date) |          Check results thoroughly, then start over and rerun analysis without -d flag if necessary."
+if [[ "$MY_VERBOSE_OUT_SWITCH" != "0" ]]; then
+	echo "WARNING!  | $(date) |          Experimental 'deep clean' option invoked. WARNING: this may cause errors. "
+	echo "INFO      | $(date) |          Check results thoroughly, then start over and rerun analysis without -d flag if necessary."
+fi
 	##### MOSTLY MISSING DATA CHECKER
 	## Check and remove individuals with very few sites at start, finish, or only in middle 
 	## of the alignment (looking to remove indiv's with only 5-20 sites total):
@@ -323,9 +337,14 @@ if [[ "$MY_OUTPUT_FILE_SWITCH" != "NULL" ]]; then
 	cd .. ;
 fi
 
+	if [[ -s ./args.txt ]]; then rm ./args.txt ; fi 	## Remove arguments file generated when parsing the options.
 
 echo "----------------------------------------------------------------------------------------------------------"
 echo ""
+
+## END DEBUG MODE
+if [[ "$MY_DEBUG_MODE_SWITCH" != "0" ]]; then set +xv; fi
+######
 
 ##########################################################################################
 ######################################### END ############################################
@@ -343,26 +362,31 @@ fi
 USAGE="Usage: $(basename "$0") [OPTION]...
 
  ${bold}Options:${reset}
-  -k   keepPHYLIP (def: 0, off; 1, on) whether or not to the original PHYLIP files; if invoked,
-       they are stored in a subfolder named orig_phylip/
+  -i   inputPHYLIP (def: NULL) name of input PHYLIP DNA sequence alignment file
+  -m   multiPHYLIP (def: 0, turned off; 1, on) whether or not to clean multiple PHYLIP DNA 
+       sequence alignment files in current working directory
+  -k   keepPHYLIP (def: 0, off; 1, on) whether or not to keep the original PHYLIP files; if 
+       invoked, originals are stored in orig_phylip/ subfolder
   -o   outputFile (def: NULL) send screen output to file in ./output/ with user-specified 
        name, for example 'output.txt'
-  -v   verbose (def: 0, off; 1, on) step verbose output to screen (stdout)
-  -d   deepClean (def: 0, off; 1, on) **experimental** option specifying whether or not to 
+  -v   verbose (def: 0, off; 1, on) output more information to screen (stdout)
+  -c   deepClean (def: 0, off; 1, on) **experimental** option specifying whether or not to 
        attempt removal of individuals with _mostly_ missing data (not tested!!!)
   -h   help text (also: --help) echo this help text and exit
   -V   version (also: --version) echo version and exit
+  -d   debug (def: 0, off; 1, on also: --debug) run function in Bash debug mode
 
  ${bold}OVERVIEW${reset}
- THIS SCRIPT loops through PHYLIP ('.phy'; Felsenstein 2002) multiple sequence alignments in
- current working directory and removes individuals composed of completely undetermined sites
- (e.g. containing DNA sequences comprised 100% of gaps, '-', or missing characters coded 
- as 'n', 'N', or '?'). Tip taxon names may include alphanumeric, hyphen, and underscore 
- characters but no spaces or pound signs (#), or else there could be issues. If invoked with
- the -d flag set to 1, then the program also attempts a 'deep clean' removing individuals with 
- _mostly_ missing data, including sequences only 5–20 bp in length padded by gaps or missing 
- characters; however, this option is an **experimental** option that has not been adequately 
- tested and thus is *not* recommended (=avoid!!!).
+ THIS SCRIPT cleans one (-i flag) or multiple (-m flag) PHYLIP DNA sequence alignment files 
+ ('.phy' extension; Felsenstein 2002) in the current working directory by removing individuals 
+ composed of completely undetermined sites (e.g. containing DNA sequences comprised 100% of 
+ gaps, '-', or missing characters coded as 'n', 'N', or '?'). 
+	Tip taxon names may include alphanumeric, hyphen, and underscore characters but no spaces 
+ or pound signs (#), or else there could be issues. If invoked with -c flag set to 1, then 
+ the program also attempts a 'deep clean' removing individuals with _mostly_ missing data, 
+ including sequences only 5–20 bp in length padded by gaps or missing characters; however, 
+ this option is an **experimental** option that has not been adequately tested and thus is 
+ *not* recommended (=avoid!!!).
 	An option (-k 1) is available that allows keeping original PHYLIP files. By default, the
  program runs quietly with limited stdout or stderr output to screen (only filenames); however, 
  the -v option causes verbose run information to be redirected to screen for each PHYLIP file, 
@@ -374,10 +398,13 @@ USAGE="Usage: $(basename "$0") [OPTION]...
  or Linux. 
 
  ${bold}Usage Examples${reset}
-    piranha -f PHYLIPcleaner --args='-k 1 -v 1'  Remove individuals with completely undetermined sites,
-                                                 while storing original PHYLIP files in subfolder
-    piranha -f PHYLIPcleaner -a '-k 1 -v 1'      Same as above, but passing arguments with -a flag
-    piranha -f PHYLIPcleaner --args='-h'         Print this help text and exit
+    piranha -f PHYLIPcleaner -i <inputPHYLIP> -v 1     Clean <inputPHYLIP> file and echo run
+                                                       output to screen
+    piranha -f PHYLIPcleaner -m 1 -k 1 -v 1            Clean multiple PHYLIP files in working
+                                                       dir, keep original files (saved to 
+                                                       orig_phylip/ subfolder), and echo run
+                                                       output to screen
+    piranha -f PHYLIPcleaner -h                        Show this help text and exit
 
  ${bold}CITATION${reset}
  Bagley, J.C. 2019. PIrANHA v0.3a2. GitHub repository, Available at:
@@ -450,21 +477,34 @@ fi
 		MY_VERBOSE_OUT_SWITCH="$MY_ARG" ;
 	fi
 #
-	if [[  "$(grep -h '\-d' ./args.txt | wc -l | perl -pe 's/\ //g')" = "0" ]]; then
+	if [[  "$(grep -h '\-c' ./args.txt | wc -l | perl -pe 's/\ //g')" = "0" ]]; then
 		MY_DEEP_CLEAN_SWITCH=0 ;
 	else 
-		MY_ARG="$(grep -h '\-d' ./args.txt | perl -pe 's/\-d//g' | perl -pe 's/\ //g')";
+		MY_ARG="$(grep -h '\-c' ./args.txt | perl -pe 's/\-c//g' | perl -pe 's/\ //g')";
 		MY_DEEP_CLEAN_SWITCH="$MY_ARG" ;
+	fi
+#
+	if [[  "$(grep -h '\-d' ./args.txt | wc -l | perl -pe 's/\ //g')" = "0" ]]; then
+		MY_DEBUG_MODE_SWITCH=0 ;
+	else 
+		MY_ARG="$(grep -h '\-d' ./args.txt | perl -pe 's/\-d//g' | perl -pe 's/\ //g')";
+		MY_DEBUG_MODE_SWITCH="$MY_ARG" ;
+	fi
+	if [[  "$(grep -h '\-\-debug' ./args.txt | wc -l | perl -pe 's/\ //g')" = "0" ]]; then
+		MY_DEBUG_MODE_SWITCH=0 ;
+	else 
+		MY_DEBUG_MODE_SWITCH=1 ;
 	fi
 
 # ############ PARSE THE OPTIONS
-# while getopts 'k:o:v:d:' opt ; do
+# while getopts 'k:o:v:c:d:' opt ; do
 #   case $opt in
 # ## PHYLIPcleaner options:
 #     k) MY_KEEP_PHYLIP_SWITCH=$OPTARG ;;
 #     o) MY_OUTPUT_FILE_SWITCH=$OPTARG ;;
 #     v) MY_VERBOSE_OUT_SWITCH=$OPTARG ;;
-#     d) MY_DEEP_CLEAN_SWITCH=$OPTARG ;;
+#     c) MY_DEEP_CLEAN_SWITCH=$OPTARG ;;
+#     d) MY_DEBUG_MODE_SWITCH=$OPTARG ;;
 # ## Missing and illegal options:
 #     :) printf "Missing argument for -%s\n" "$OPTARG" >&2
 #        echo "$USAGE" >&2
diff --git a/bin/PHYLIPsubsampler b/bin/PHYLIPsubsampler
--- a/bin/PHYLIPsubsampler
+++ b/bin/PHYLIPsubsampler
@@ -6,10 +6,10 @@
 # |                                                                                      #
 #                                                                                        #
 # File: PHYLIPsubsampler.sh                                                              #
-  VERSION="v1.1.6"                                                                       #
+  VERSION="v1.1.7"                                                                       #
 # Author: Justin C. Bagley                                                               #
 # Date: Created by Justin Bagley on Tue, 19 Feb 2019 22:36:23 -0600.                     #
-# Last update: April 6, 2020                                                             #
+# Last update: April 12, 2020                                                            #
 # Copyright (c) 2019-2020 Justin C. Bagley. All rights reserved.                         #
 # Please report bugs to <bagleyj@umsl.edu>.                                              #
 #                                                                                        #
@@ -139,7 +139,7 @@ PHYLIPsubsampler () {
 ##########################################################################################
 
 echo "INFO      | $(date) |----------------------------------------------------------------"
-echo "INFO      | $(date) | PHYLIPsubsampler, v1.1.6 April 2020                            "
+echo "INFO      | $(date) | PHYLIPsubsampler, v1.1.7 April 2020                            "
 echo "INFO      | $(date) | Copyright (c) 2019-2020 Justin C. Bagley. All rights reserved. "
 echo "INFO      | $(date) |----------------------------------------------------------------"
 
@@ -207,7 +207,7 @@ MY_PHYLIP_ALIGNMENTS=./*.phy ;
 				sed -i 's/\('$j'\)-[0-9\ ]*/\1\ \ \ \ \ \ /g' "$LOCUS_NAME".phy;
 				sed -i 's/\('$j'\)-[0-9\ ]*/\1\ \ \ \ \ \ /g' "$LOCUS_NAME".phy;
 			fi
-		done < "$MY_ASSIGNMENT_FILE"
+		done < "$MY_ASSIGNMENT_FILE" ;
 
 	done
 )
@@ -274,11 +274,14 @@ if [[ "$INPUT_PHYLIP_FILE" != "NULL" ]]; then
 
 fi
 
+if [[ ! -z $(ls ./*.tmp) ]]; then 
+	echo "INFO      | $(date) | Step #4: Clean up workspace by removing temporary files generated during run. "
+	echo "INFO      | $(date) |          Deleting temporary files... "
+	############ CLEAN UP WORKING DIR BY DELETING TEMPORARY FILES.	
+	rm ./*.tmp ; 
+fi
 
-#echo "INFO      | $(date) | Done."
-#echo "INFO      | $(date) | Bye.
-#"
-
+echo "INFO      | $(date) | Done."
 echo "----------------------------------------------------------------------------------------------------------"
 echo ""
 
@@ -295,12 +298,12 @@ INPUT_PHYLIP_FILE=NULL
 MY_ASSIGNMENT_FILE=assignments.txt
 
 ############ CREATE USAGE & HELP TEXTS
-USAGE="Usage: $(basename $0) [OPTION]...
+USAGE="Usage: $(basename "$0") [OPTION]...
 
  ${bold}Options:${reset}
   -i   inputPHYLIP (def: NULL) Used in case of subsampling a single input PHYLIP file; 
        otherwise, left blank when analyzing multiple PHYLIP files (default)
-  -a   assignmentFile (def: $MY_ASSIGNMENT_FILE) Name of assignment file containing four-letter
+  -a   assignmentFile (def: $MY_ASSIGNMENT_FILE) assignment file containing four-letter
        population or taxon assignment codes, one per line
   -h   help text (also: --help) echo this help text and exit
   -V   version (also: --version) echo version and exit
@@ -340,8 +343,9 @@ USAGE="Usage: $(basename $0) [OPTION]...
  ${bold}Usage examples:${reset}
  Call the program using PIrANHA, as follows:
 
-    piranha -f PHYLIPsubsampler --args='-a species.txt'    Run on multiple PHYLIP files with user-
-             											   specified assignment file 'species.txt'
+    piranha -f PHYLIPsubsampler -a species.txt      Run on multiple PHYLIP files with user-
+                                                    specified assignment file 'species.txt'
+    piranha -f PHYLIPsubsampler -h                  Show this help text and exit
 
  ${bold}CITATION${reset}
  Bagley, J.C. 2019. PIrANHA v0.3a2. GitHub repository, Available at:
diff --git a/bin/PHYLIPsummary b/bin/PHYLIPsummary
--- a/bin/PHYLIPsummary
+++ b/bin/PHYLIPsummary
@@ -5,17 +5,17 @@
 # |__) | |  ' (__( |  ) |  ) (__(                                                        # 
 # |                                                                                      #
 #                                                                                        #
-# File: RAxMLRunChecker.sh                                                               #
-  VERSION="v1.3.3"                                                                       #
+# File: PHYLIPsummary.sh                                                                 #
+  VERSION="v1.0.3"                                                                       #
 # Author: Justin C. Bagley                                                               #
-# Date: Created by Justin Bagley on/before November 29, 2018.                            #
+# Date: Created by Justin Bagley on Wed, Jun 19 14:04:27 CDT 2019.                       #
 # Last update: April 12, 2020                                                            #
-# Copyright (c) 2018-2020 Justin C. Bagley. All rights reserved.                         #
+# Copyright (c) 2019-2020 Justin C. Bagley. All rights reserved.                         #
 # Please report bugs to <bagleyj@umsl.edu>.                                              #
 #                                                                                        #
 # Description:                                                                           #
-# SHELL SCRIPT THAT COUNTS NUMBER OF LOCI/PARTITIONS WITH COMPLETED RAxML RUNS DURING    #
-# OR AFTER A RUN OF THE MAGNET PIPELINE, AND COLLATES RUN INFORMATION                    #
+# SHELL FUNCTION THAT SUMMARIZES THE CHARACTERISTICS OF ONE OR MULTIPLE PHYLIP DNA       #
+# SEQUENCE ALIGNMENT FILES AND SAVES RESULTS TO FILE                                     #
 #                                                                                        #
 ##########################################################################################
 
@@ -130,117 +130,109 @@ gemDependencies=()
 
 
 
-RAxMLRunChecker () {
+PHYLIPsummary () {
 
 ######################################## START ###########################################
 ##########################################################################################
 
 echo "INFO      | $(date) |----------------------------------------------------------------"
-echo "INFO      | $(date) | RAxMLRunChecker, v1.3.3 April 2020                             "
-echo "INFO      | $(date) | Copyright (c) 2018-2020 Justin C. Bagley. All rights reserved. "
+echo "INFO      | $(date) | PHYLIPsummary, v1.0.3 April 2020                               "
+echo "INFO      | $(date) | Copyright (c) 2019-2020 Justin C. Bagley. All rights reserved. "
 echo "INFO      | $(date) |----------------------------------------------------------------"
 
 ######################################## START ###########################################
-echo "INFO      | $(date) | Starting RAxMLRunChecker pipeline... "
-echo "INFO      | $(date) | Step #1: Set up workspace and check machine type. "
-############ I. SET WORKING DIRECTORY AND CHECK MACHINE TYPE
-USER_SPEC_PATH="$(printf '%q\n' "$(pwd)")";
-echoCDWorkingDir
+echo "INFO      | $(date) | Starting PHYLIPsummary analysis... "
+echo "INFO      | $(date) | Step #1: Set up workspace and set environmental variables. "
+############ STEP #1: SET UP VARIABLES AND SETUP FUNCTIONS
+###### Set working directory and filetypes as different variables:
+echo "INFO      | $(date) |          Setting user-specified path to: "
+echo "INFO      | $(date) |          $PWD "	
+echo "INFO      | $(date) |          Input file: $INPUT_FILE "
+echo "INFO      | $(date) |          Examining current directory, setting variables... "
+
 #echo "INFO      | $(date) |          Checking machine type... "
 checkMachineType
 #echo "INFO      | $(date) |               Found machine type ${machine}. "
 
 
-############ II. RUN RAXML RUN CHECKER
-echo "INFO      | $(date) | Step #2: Check RAxML runs in subfolders in current directory (assumed to be a MAGNET run folder). "
 
-	echo "INFO      | $(date) |          Estimating numbers (no.) of loci and RAxML runs... "
-	MY_N_LOCI_FOLD="$(ls -d ./locus*/ | wc -l | sed 's/^[\ ]*//g')"
-	MY_N_COMPLETED="$(ls ./locus*/RAxML_info.raxml_out | wc -l | sed 's/^[\ ]*//g')"
-	MY_N_REMAINING="$(calc $MY_N_LOCI_FOLD - $MY_N_COMPLETED)"
+echo "INFO      | $(date) | Step #2: Check and produce summaries of characteristics of input PHYLIP file(s). "
+############ STEP #2: SUMMARIZE INPUT PHYLIP FILE(S)
 
-	echo "INFO      | $(date) |          Total no. RAxML runs: $TAB$TAB$MY_N_LOCI_FOLD "
-	echo "INFO      | $(date) |          No. completed RAxML runs: $TAB$MY_N_COMPLETED "
-	echo "INFO      | $(date) |          No. remaining RAxML runs:    $TAB$MY_N_REMAINING "
+### RUN ON SINGLE INPUT PHYLIP FILE
+###
+if [[ "$INPUT_PHYLIP_FILE" != "NULL" ]] && [[ -s "$INPUT_PHYLIP_FILE" ]]; then
+	#### Get PHYLIP characteristics:
+	MY_BASENAME="$(basename "$INPUT_PHYLIP_FILE" '.phy')";
+#
+	MY_NCHAR="$(head -n1 "$INPUT_PHYLIP_FILE" | sed 's/[0-9]*\ //g' | sed 's/\ //g')";
+	echo "$MY_NCHAR" >> ./PHYLIP_nChar.list.txt ;
+#
+	echo "$MY_BASENAME" >> ./PHYLIP_order.list.tmp ;
+#
+	MY_NTAX="$(head -n1 "$INPUT_PHYLIP_FILE" | sed 's/\ [0-9]*//g; s/\ //g')";
+	echo "$MY_NTAX" >> ./PHYLIP_nTax.list.txt ;
 
-	if [[ -s ./completed_run_info.tmp ]]; then
-		rm ./completed_run_info.tmp;
-	fi
-	if [[ -s ./completed_run_info.txt ]]; then
-		rm ./completed_run_info.txt;
-	fi
-	if [[ -s ./remaining_run_info.tmp ]]; then
-		rm ./remaining_run_info.tmp;
-	fi
-	if [[ -s ./remaining_run_info.txt ]]; then
-		rm ./remaining_run_info.txt;
-	fi
+	echo "File	nTax	nChar" > ./header.tmp ;
+	paste ./PHYLIP_order.list.tmp ./PHYLIP_nChar.list.txt ./PHYLIP_nTax.list.txt > ./PHYLIP_table.tmp ;
+	cat ./header.tmp ./PHYLIP_table.tmp > ./PHYLIP_Summary.txt ;
+fi
+###
 
-	echo "INFO      | $(date) |          Saving RAxML run info to file... "
-
-	count=1
-	echo "INFO      | $(date) |          ...  $count / $MY_N_LOCI_FOLD ..."
+### RUN ON MULTIPLE PHYLIP FILES
+###
+if [[ "$INPUT_PHYLIP_FILE" = "NULL" ]] && [[ "$MULTIPLE_PHYLIP_SWITCH" = "1" ]]; then
+count=0
 (
-	for i in ./locus*/; do 
-		MY_LOCUS="$(echo $i | sed 's/\.\///g; s/\///g; s/\ //g')"; 
-		MY_COUNT_HUND_CHECK="$(calc $count / 100 | sed 's/^[0-9]*\.//g; s/^[0]\{1\}//g')"
-		if [[ "$MY_COUNT_HUND_CHECK" -eq "0" ]]; then
-			echo "INFO      | $(date) |          ...  $count / $MY_N_LOCI_FOLD ..."
-		fi
-		if [[ "$count" -eq "$MY_N_LOCI_FOLD" ]]; then
-			echo "INFO      | $(date) |          ...  $MY_N_LOCI_FOLD / $MY_N_LOCI_FOLD ..."
-		fi
-		cd "$i"; 
-			if [[ -s RAxML_bipartitions.raxml_out ]]; then 
-
-				MY_ALIGN_PATT="$(grep -h '^Alignment\ Patterns\:\ ' ./RAxML_info.raxml_out | sed 's/^.*\:\ //g')";
-				MY_SUBST_MODEL="$(grep -h '^Substitution\ Matrix\:\ ' ./RAxML_info.raxml_out | sed 's/^.*\:\ //g')";
-				MY_OPTIM_LIKE="$(grep -h 'Final\ ML\ Optimization\ Likelihood\:\ ' ./RAxML_info.raxml_out | sed 's/^.*\:\ //g')";
-				MY_ML_RUN_TIME="$(grep -h 'Overall\ execution\ time\ ' ./RAxML_info.raxml_out | sed 's/^Overall\ execution\ time\ [A-Za-z\ ]*\:\ //g; s/or\ .*//g')";
-				
-				echo "$count$TAB$MY_LOCUS$TAB$MY_ALIGN_PATT$TAB$MY_SUBST_MODEL$TAB$MY_OPTIM_LIKE$TAB$MY_ML_RUN_TIME$TAB complete" >> ../completed_run_info.tmp; 
-			fi
-			if [[ ! -s RAxML_bipartitions.raxml_out ]]; then 
-				
-				echo "$count$TAB$MY_LOCUS$TAB$MY_ALIGN_PATT$TAB$MY_SUBST_MODEL$TAB incomplete" >> ../remaining_run_info.tmp; 
-				
-			fi
-		cd ..; 
-		echo "$((count++))" > ./count.tmp ;
+	for i in ./*.phy ; do
+		#### Get PHYLIP characteristics:
+		MY_BASENAME="$(basename "$i" '.phy')";
+#
+		MY_NCHAR="$(head -n1 "$i" | sed 's/[0-9]*\ //g' | sed 's/\ //g')";
+		echo "$MY_NCHAR" >> ./PHYLIP_nChar.list.txt ;
+#
+		echo "$MY_BASENAME" >> ./PHYLIP_order.list.tmp ;
+#
+		MY_NTAX="$(head -n1 "$i" | sed 's/\ [0-9]*//g; s/\ //g')";
+		echo "$MY_NTAX" >> ./PHYLIP_nTax.list.txt ;
+		echo "Done summarizing PHYLIP file: $((count++))... ";
 	done
 )
+#
+	echo "File	nTax	nChar" > ./header.tmp ;
+	paste ./PHYLIP_order.list.tmp ./PHYLIP_nChar.list.txt ./PHYLIP_nTax.list.txt > ./PHYLIP_table.tmp ;
+	cat ./header.tmp ./PHYLIP_table.tmp > ./PHYLIP_Summary.txt ;
+
+#	MY_N_PHY_FILES="$(echo "$count" )";
+	MY_N_PHY_FILES="$(ls ./*.phy | wc -l | sed 's/\ //g')";
+fi
+###
 
 
-	echo "No$TAB Locus$TAB No. Patterns$TAB Subst. Model$TAB Likelihood$TAB ML Run Time$TAB Status" > ./header.tmp;
-	echo "No$TAB Locus$TAB No. Patterns$TAB Subst. Model$TAB Status" > ./rem_header.tmp;
-	cat ./header.tmp ./completed_run_info.tmp > ./completed_run_info.txt;
-	cat ./rem_header.tmp ./remaining_run_info.tmp > ./remaining_run_info.txt;
+echo "INFO      | $(date) | Step #3: Clean up workspace by removing temporary files generated during run. "
+###### Remove temporary or unnecessary files created above:
+	echo "INFO      | $(date) |          Removing temporary files... "
+	if [[ ! -z "$(ls ./*.tmp)" ]]; then
+		rm ./*.tmp ;
+	fi
+	if [[ -s ./args.txt ]]; then rm ./args.txt ; fi 	## Remove arguments file generated when parsing the options.
 
-
-	echo "INFO      | $(date) |          Editing final RAxML run information files... "
-		if [[ "${machine}" = "Mac" ]]; then
-			sed -i.bak 's/\ //g' ./completed_run_info.txt;
-			sed -i.bak 's/\ //g' ./remaining_run_info.txt;
-			rm ./*.bak;
-		fi
-		if [[ "${machine}" = "Linux" ]]; then
-			sed -i 's/\ //g' ./completed_run_info.txt;
-			sed -i 's/\ //g' ./remaining_run_info.txt;
-		fi
-
-
-############ III. CLEAN UP WORKSPACE BY REMOVING TEMPORARY FILES.
-echo "INFO      | $(date) | Step #3: Clean up workspace. "
-echo "INFO      | $(date) |          Cleaning up workspace by removing temporary files generated during run... "
-
-	if [[ ! -z $(ls ./*.tmp) ]]; then rm ./*.tmp ; fi
 
 echo "INFO      | $(date) | Done."
 echo "----------------------------------------------------------------------------------------------------------"
-echo "output file(s): ./completed_run_info.txt "
-echo "                ./remaining_run_info.txt "
+if [[ "$INPUT_PHYLIP_FILE" != "NULL" ]] && [[ -s "$INPUT_PHYLIP_FILE" ]]; then
+	echo "input PHYLIP file: $INPUT_PHYLIP_FILE "
+	echo "output files: ./PHYLIP_nTax.list.txt "
+	echo "              ./PHYLIP_nChar.list.txt "
+	echo "              ./PHYLIP_Summary.txt "
+fi
+if [[ "$INPUT_PHYLIP_FILE" = "NULL" ]] && [[ "$MULTIPLE_PHYLIP_SWITCH" = "1" ]]; then
+	echo "input PHYLIP files: $MY_N_PHY_FILES PHYLIP alignments from current directory"
+	echo "output files: ./PHYLIP_nTax.list.txt "
+	echo "              ./PHYLIP_nChar.list.txt "
+	echo "              ./PHYLIP_Summary.txt "
+fi
 echo ""
-
 
 ##########################################################################################
 ######################################### END ############################################
@@ -249,65 +241,102 @@ echo ""
 
 
 
-############ SCRIPT OPTIONS
-## OPTION DEFAULTS ##
-# None at this time.
-
 ############ CREATE USAGE & HELP TEXTS
 USAGE="Usage: $(basename "$0") [OPTION]...
 
  ${bold}Options:${reset}
+  -i   inputPHYLIP (def: NULL) input PHYLIP filename
+  -m   multiPHYLIP (def: 0, turned off; 1, on) whether to summarize multiple PHYLIP files 
+       in current working directory
   -h   help text (also: --help) echo this help text and exit
-  -V   version (also: --version) echo version of this script and exit
+  -V   version (also: --version) echo version and exit
 
  ${bold}OVERVIEW${reset}
- THIS SCRIPT was designed to run in a current working directory where the MAGNET pipeline
- in PIrANHA v0.3a2 (Bagley 2019) is being run, or has completed a run, to estimate maximum-
- likelihood (ML) gene trees in RAxML v8+ (Stamatakis 2014) for a set of loci from DNA 
- sequence data. Given such a workspace, this script counts the number of loci or data 
- partitions (each assigned a separate RAxML run in MAGNET) with completed RAxML runs and 
- collates run information. Output files include a summary of completed runs and a summary 
- of ongoing runs.
+ THIS SCRIPT reads one (-i flag) or multiple (-m flag) PHYLIP (Felsenstein 2002) DNA sequence 
+ alignment files and produces a summary of their main characteristics, including the numbers of
+ taxa (tips/sequence labels) and characters (bp), which is saved to file. Sequence names 
+ should include alphanumeric, hyphen, and underscore characters but no spaces. Also, PHYLIP
+ alignment files must have the extension '.phy'. Output is saved to the following files:
+
+ - No. taxa:       PHYLIP_nTax.list.txt
+ - No. characters: PHYLIP_nChar.list.txt
+ - PHYLIP summary: PHYLIP_Summary.txt     (table)
+
 	This program runs on UNIX-like and Linux systems using commonly distributed utility 
  software, with usage obtained by running the script with the -h flag. It has been tested
  on macOS High Sierra (v10.13+) and Mojave but should work on many earlier versions or
  Linux (tested on CentOS 6/7). There are no other dependencies.
-
+ 
  ${bold}Usage examples:${reset}
  Call the program using PIrANHA, as follows:
 
-    piranha -f RAxMLRunChecker         Run the program
-    piranha -f RAxMLRunChecker -h      Print this help text
+    piranha -f PHYLIPsummary -i <inputPHYLIP>      Summarize single PHYLIP file
+    piranha -f PHYLIPsummary -m 1                  Summarize multiple PHYLIP files
+    piranha -f PHYLIPsummary -h                    Show this help text and exit
 
  ${bold}CITATION${reset}
  Bagley, J.C. 2019. PIrANHA v0.3a2. GitHub repository, Available at:
 	<https://github.com/justincbagley/piranha>.
 
  ${bold}REFERENCES${reset}
- Bagley, J.C. 2019. PIrANHA v0.3a2. GitHub repository, Available at:
-	<https://github.com/justincbagley/PIrANHA>.
- Stamatakis, A. 2014. RAxML version 8: a tool for phylogenetic analysis and post-analysis of 
-	large phylogenies. Bioinformatics, 30, 1312-1313.
+ Felsenstein, J. 2002. PHYLIP (Phylogeny Inference Package) Version 3.6 a3.
+	Available at: <http://evolution.genetics.washington.edu/phylip.html>.
 
- Created by Justin Bagley on/before November 29, 2018.
- Copyright (c) 2018-2020 Justin C. Bagley. All rights reserved.
+ Created by Justin Bagley on Tue, Jun 11 12:36:45 CDT 2019.
+ Copyright (c) 2019-2020 Justin C. Bagley. All rights reserved.
 "
 
-#if [[ -z "$*" ]]; then
-#	echo "$USAGE"
-#	exit
-#fi
+if [[ -z "$*" ]]; then
+	echo "$USAGE"
+	exit
+fi
 
-if [[ "$1" == "-h" ]] || [[ "$1" == "--help" ]]; then
+if [[ "$1" == "-h" ]] || [[ "$1" == "-help" ]]; then
 	echo "$USAGE"
 	exit
 fi
 
 if [[ "$1" == "-V" ]] || [[ "$1" == "--version" ]]; then
-	echo "$(basename "$0") $VERSION";
+	echo "$(basename $0) $VERSION";
 	exit
 fi
 
+############ CHECK ARGUMENTS
+	# echo "$@"; echo "$#"; echo "$1" 
+	# for i in "$@"; do
+	# 	echo "$i";
+	# done
+	# MY_ARGS="$(echo "$@" | perl -pe $'s/\ /\n/')"
+	# echo "$MY_ARGS"
+
+
+############ CAPTURE ARGUMENTS, SEND TO FILE FOR PARSING
+	if [[ -s ./args.tmp ]]; then rm ./args.tmp ; fi ;
+	if [[ -s ./args.txt ]]; then rm ./args.txt ; fi ;
+
+	ALL_MY_ARGUMENTS="$(echo "$@")"
+	echo "$ALL_MY_ARGUMENTS" > ./args.txt
+	perl -p -i -e $'s/\-/\n\-/g' ./args.txt
+	#wc -l ./args.txt | perl -pe 's/\.\/args\.txt.*//g' | perl -pe 's/\ //g'
+
+
+############ MANUALLY PARSE THE OPTIONS FROM ARGS
+
+### SET OPTIONS TO DEFAULT VALUES, EXCEPT WHERE VALUES WERE READ IN FROM USER ARGS
+	if [[  "$(grep -h '\-i' ./args.txt | wc -l | perl -pe 's/\ //g')" = "0" ]]; then
+		INPUT_PHYLIP_FILE=NULL ;
+	else 
+		MY_ARG="$(grep -h '\-i' ./args.txt | perl -pe 's/\-i//g' | perl -pe 's/\ //g')";
+		INPUT_PHYLIP_FILE="$MY_ARG" ;
+	fi
+#
+	if [[  "$(grep -h '\-m' ./args.txt | wc -l | perl -pe 's/\ //g')" = "0" ]]; then
+		MULTIPLE_PHYLIP_SWITCH=0 ;
+	else 
+		MY_ARG="$(grep -h '\-m' ./args.txt | perl -pe 's/\-m//g' | perl -pe 's/\ //g')";
+		MULTIPLE_PHYLIP_SWITCH="$MY_ARG" ;
+	fi
+#
 
 # ############# ############# #############
 # ##       TIME TO RUN THE SCRIPT        ##
@@ -340,7 +369,7 @@ set -o pipefail
 # checkDependencies
 
 # Run the script
-RAxMLRunChecker
+PHYLIPsummary
 
 # Exit cleanly
 safeExit
diff --git a/bin/getTaxonNames b/bin/getTaxonNames
--- a/bin/getTaxonNames
+++ b/bin/getTaxonNames
@@ -6,10 +6,10 @@
 # |                                                                                      #
 #                                                                                        #
 # File: getTaxonNames.sh                                                                 #
-  VERSION="v1.1.2"                                                                       #
+  VERSION="v1.1.3"                                                                       #
 # Author: Justin C. Bagley                                                               #
 # Date: Created by Justin Bagley on Wed, Mar 13 17:17:41 CDT 2019.                       #
-# Last update: April 6, 2020                                                             #
+# Last update: April 12, 2020                                                            #
 # Copyright (c) 2019-2020 Justin C. Bagley. All rights reserved.                         #
 # Please report bugs to <bagleyj@umsl.edu>.                                              #
 #                                                                                        #
@@ -136,7 +136,7 @@ getTaxonNames () {
 ##########################################################################################
 
 echo "INFO      | $(date) |----------------------------------------------------------------"
-echo "INFO      | $(date) | getTaxonNames, v1.1.2 April 2020                               "
+echo "INFO      | $(date) | getTaxonNames, v1.1.3 April 2020                               "
 echo "INFO      | $(date) | Copyright (c) 2019-2020 Justin C. Bagley. All rights reserved. "
 echo "INFO      | $(date) |----------------------------------------------------------------"
 
@@ -208,7 +208,13 @@ sed 's/$/\ x/g' "$MY_N_MAX_TIP_TAXA_FIX_SPACES"_taxon_names.txt | column -t | se
 #	rm "$MY_N_MAX_TIP_TAXA_FIX_SPACES"_taxon_names.txt ;
 #fi
 
+echo "INFO      | $(date) | Step #4: Clean up workspace by removing temporary files generated during run. "
+echo "INFO      | $(date) |          Deleting temporary files... "
+############ CLEAN UP WORKING DIR BY DELETING TEMPORARY FILES.
+	
+	if [[ -s ./args.txt ]]; then rm ./args.txt ; fi 	## Remove arguments file generated when parsing the options.
 
+echo "INFO      | $(date) | Done."
 echo "----------------------------------------------------------------------------------------------------------"
 echo "output file(s): ./${MY_N_MAX_TIP_TAXA_FIX_SPACES}_taxon_names.txt"
 echo "                ./${MY_N_MAX_TIP_TAXA_FIX_SPACES}_taxon_names_spaces.txt"
@@ -222,10 +228,10 @@ echo ""
 
 
 ############ CREATE USAGE & HELP TEXTS
-USAGE="Usage: $(basename $0) [OPTION]...
+USAGE="Usage: $(basename "$0") [OPTION]...
 
  ${bold}Options:${reset}
-  -n   numTips (def: NULL) mandatory input, maximum number of tip taxa in dataset
+  -n   numTips (def: NULL) mandatory maximum number of tip taxa in dataset
   -h   help text (also: -help) echo this help text and exit
   -V   version (also: --version) echo version of this script and exit
 
@@ -245,18 +251,18 @@ USAGE="Usage: $(basename $0) [OPTION]...
  names are padded with spaces so that sequences start on the same column of the file, thus 
  are aligned). The taxon names and spaces file is an important input for other functions in
  the PIrANHA (Bagley 2019) distribution, including the 'concatenateSeqs' function (see 
- concatenateSeqs help text for further information: piranha -f concatenateSeqs --args='-h'). 
- Thus, getTaxonNames is a useful companion to other PIrANHA functions.
+ concatenateSeqs help text for further information: piranha -f concatenateSeqs -h). Thus,
+ getTaxonNames is a useful companion to other PIrANHA functions.
 	This program runs on UNIX-like and Linux systems using commonly distributed utility 
  software, with usage obtained by running the script with the -h flag. It has been tested
  on macOS High Sierra (v10.13+) and Mojave but should work on many earlier versions or
- Linux (tested on CentOS 6/7). There are no other dependencies.
+ Linux (tested on CentOS 5/6/7). There are no other dependencies.
  
  ${bold}Usage examples:${reset}
  Call the program using PIrANHA, as follows:
 
-    piranha -f getTaxonNames --args='-n 80'    Run program with the maximum <numTips> set to 80
-    piranha -f getTaxonNames --args='-h'       Print this help text
+    piranha -f getTaxonNames -n 80      Run program with maximum <numTips> set to 80
+    piranha -f getTaxonNames -h         Show this help text and exit
 
  ${bold}CITATION${reset}
  Bagley, J.C. 2019. PIrANHA v0.3a2. GitHub repository, Available at:
diff --git a/bin/splitFASTA b/bin/splitFASTA
--- a/bin/splitFASTA
+++ b/bin/splitFASTA
@@ -6,10 +6,10 @@
 # |                                                                                      #
 #                                                                                        #
 # File: splitFASTA.sh                                                                    #
-  VERSION="v1.0.3"                                                                       #
+  VERSION="v1.0.4"                                                                       #
 # Author: Justin C. Bagley                                                               #
 # Date: Created by Justin Bagley on Wed, Apr 1 12:05:32 CDT 2020.                        #
-# Last update: April 7, 2020                                                             #
+# Last update: April 12, 2020                                                            #
 # Copyright (c) 2020 Justin C. Bagley. All rights reserved.                              #
 # Please report bugs to <bagleyj@umsl.edu>.                                              #
 #                                                                                        #
@@ -136,7 +136,7 @@ splitFASTA () {
 ##########################################################################################
 
 echo "INFO      | $(date) |----------------------------------------------------------------"
-echo "INFO      | $(date) | splitFASTA, v1.0.3 April 2020                                  "
+echo "INFO      | $(date) | splitFASTA, v1.0.4 April 2020                                  "
 echo "INFO      | $(date) | Copyright (c) 2020 Justin C. Bagley. All rights reserved.      "
 echo "INFO      | $(date) |----------------------------------------------------------------"
 
@@ -328,20 +328,17 @@ else
 	)
 fi
 
-############ CLEAN UP WORKING DIR BY DELETING TEMPORARY FILES.
-	
+	echo "INFO      | $(date) | Step #4: Clean up workspace by removing temporary files generated during run. "
+	echo "INFO      | $(date) |          Deleting temporary files... "
+	############ CLEAN UP WORKING DIR BY DELETING TEMPORARY FILES.
 	if [[ -s ./args.txt ]]; then rm ./args.txt ; fi 	## Remove arguments file generated when parsing the options.
 
-#if [[ "$MY_VERBOSE_OUT_SWITCH" != "0" ]]; then
-#echo "INFO      | $(date) | Successfully split input sequential FASTA file $MY_FASTA into separate FASTA files, one per tip taxon. " | tee -a ./"$MY_OUTPUT_FILE_SWITCH"
-#echo "INFO      | $(date) | Bye.
-#" | tee -a ./"$MY_OUTPUT_FILE_SWITCH"
-#fi
-
 if [[ "$MY_OUTPUT_FILE_SWITCH" != "NULL" ]]; then
+	echo "INFO      | $(date) | Done."
 	echo "----------------------------------------------------------------------------------------------------------" | tee -a ./"$MY_OUTPUT_FILE_SWITCH"
 	echo "" | tee -a ./"$MY_OUTPUT_FILE_SWITCH"
 else
+	echo "INFO      | $(date) | Done."
 	echo "----------------------------------------------------------------------------------------------------------"
 	echo ""
 fi
@@ -353,6 +350,7 @@ fi
 if [[ "$MY_REMOVE_FASTA_SWITCH" = "1" ]]; then
 	rm "$MY_FASTA" ;
 fi
+
 
 ## END DEBUG MODE
 if [[ "$MY_DEBUG_MODE_SWITCH" != "0" ]]; then set +xv; fi
@@ -369,10 +367,10 @@ if [[ "$MY_DEBUG_MODE_SWITCH" != "0" ]]; then set +xv; fi
 USAGE="Usage: $(basename "$0") [OPTION]...
 
   ${bold}Options:${reset}
-  -i   inputFASTA (def: NULL) input FASTA file name
+  -i   inputFASTA (def: NULL) input FASTA file
   -o   outputFile (def: NULL) send screen output to file in ./output/ with user-specified 
        name, for example 'output.txt'
-  -v   verbose (def: 0, off; 1, on) specify verbose output to screen (stdout)
+  -v   verbose (def: 0, off; 1, on) output more information to screen (stdout)
   -r   removeFASTA (def: 0, off; 1, on) whether or not to remove input multi-FASTA file
   -h   help text (also: --help) echo this help text and exit
   -H   help text (also: --Help) echo verbose help text and exit
@@ -396,14 +394,14 @@ USAGE="Usage: $(basename "$0") [OPTION]...
  with the user's preferred filename, saved in ./output/.
 	This program runs on UNIX-like and Linux systems using commonly distributed utility 
  software, with usage as obtained by running the script with the -h flag, and has been 
- tested with Perl v5.1+ on macOS High Sierra (v10.13+) and Centos 5/6 Linux, but should work 
- on many other versions of macOS or Linux. 
+ tested with Perl v5.1+ on macOS High Sierra (v10.13+) and Centos 5/6/7 Linux, but should 
+ work on many other versions of macOS or Linux. 
 
  ${bold}Usage Examples${reset}
-    piranha -f FASTA2PHYLIP --args='-i input.fasta -v 1'  Split input.fasta to multiple FASTAs, 
-                                                          while echoing run output to screen
-    piranha -f FASTA2PHYLIP -a '-i input.fasta -v 1'      Same as above but passing arguments
-                                                          using -a flag
+
+    piranha -f FASTA2PHYLIP -i input.fasta -v 1      Split input.fasta to multiple FASTAs, 
+                                                     while echoing run output to screen
+    piranha -f FASTA2PHYLIP -h                       Show this help text and exit
 
  ${bold}CITATION${reset}
  Bagley, J.C. 2019. PIrANHA v0.3a2. GitHub repository, Available at:
@@ -416,10 +414,10 @@ USAGE="Usage: $(basename "$0") [OPTION]...
 VERBOSE_USAGE="Usage: $(basename "$0") [OPTION]...
 
  ${bold}Options:${reset}
-  -i   inputFASTA (def: NULL) input FASTA file name
+  -i   inputFASTA (def: NULL) input FASTA file
   -o   outputFile (def: NULL) send screen output to file in ./output/ with user-specified 
        name, for example 'output.txt'
-  -v   verbose (def: 1, off; 1, on) specify verbose output to screen (stdout)
+  -v   verbose (def: 0, off; 1, on) output more information to screen (stdout)
   -r   removeFASTA (def: 0, off; 1, on) whether or not to remove input multi-FASTA file
   -h   help text (also: --help) echo this help text and exit
   -H   help text (also: --Help) echo verbose help text and exit
@@ -443,14 +441,14 @@ VERBOSE_USAGE="Usage: $(basename "$0") [OPTION]...
  with the user's preferred filename, saved in ./output/.
 	This program runs on UNIX-like and Linux systems using commonly distributed utility 
  software, with usage as obtained by running the script with the -h flag, and has been 
- tested with Perl v5.1+ on macOS High Sierra (v10.13+) and Centos 5/6 Linux, but should work 
- on many other versions of macOS or Linux. 
+ tested with Perl v5.1+ on macOS High Sierra (v10.13+) and Centos 5/6/7 Linux, but should 
+ work on many other versions of macOS or Linux. 
 
  ${bold}Usage Examples${reset}
-    piranha -f FASTA2PHYLIP --args='-i input.fasta -v 1'  Split input.fasta to multiple FASTAs, 
-                                                          while echoing run output to screen
-    piranha -f FASTA2PHYLIP -a '-i input.fasta -v 1'      Same as above but passing arguments
-                                                          using -a flag
+
+    piranha -f FASTA2PHYLIP -i input.fasta -v 1      Split input.fasta to multiple FASTAs, 
+                                                     while echoing run output to screen
+    piranha -f FASTA2PHYLIP -h                       Show this help text and exit
 
  ${bold}CITATION${reset}
  Bagley, J.C. 2019. PIrANHA v0.3a2. GitHub repository, Available at:
@@ -476,7 +474,7 @@ if [[ "$1" == "-H" ]] || [[ "$1" == "-Help" ]]; then
 fi
 
 if [[ "$1" == "-V" ]] || [[ "$1" == "--version" ]]; then
-	echo "$(basename $0) $VERSION";
+	echo "$(basename "$0") $VERSION";
 	exit
 fi
 
