Bug fixes and updates for 3 functions

diff --git a/bin/PHYLIP2FASTA b/bin/PHYLIP2FASTA
--- a/bin/PHYLIP2FASTA
+++ b/bin/PHYLIP2FASTA
@@ -6,10 +6,10 @@
 # |                                                                                      #
 #                                                                                        #
 # File: PHYLIP2FASTA.sh                                                                  #
-  VERSION="v1.1.2"                                                                       #
+  VERSION="v1.2.1"                                                                       #
 # Author: Justin C. Bagley                                                               #
 # Date: Created by Justin Bagley on Mon, Mar 4 14:52:24 CST 2019.                        #
-# Last update: March 15, 2019                                                            #
+# Last update: April 30, 2019                                                            #
 # Copyright (c) 2019 Justin C. Bagley. All rights reserved.                              #
 # Please report bugs to <bagleyj@umsl.edu>                                               #
 #                                                                                        #
@@ -136,7 +136,7 @@ PHYLIP2FASTA () {
 ##########################################################################################
 
 echo "INFO      | $(date) |----------------------------------------------------------------"
-echo "INFO      | $(date) | PHYLIP2FASTA, v1.1.2 March 2019  (in PIrANHA v0.2-alpha.2)    "
+echo "INFO      | $(date) | PHYLIP2FASTA, v1.2.1 April 2019  (in PIrANHA v0.2-alpha.2)     "
 echo "INFO      | $(date) | Copyright (c) 2019 Justin C. Bagley. All rights reserved.      "
 echo "INFO      | $(date) |----------------------------------------------------------------"
 
@@ -163,7 +163,7 @@ fi
 		echo "INFO      | $(date) | Converting $INPUT_PHYLIP_FILE ... "
 		MY_BASENAME="$(basename $INPUT_PHYLIP_FILE .phy)" ;
 		sed '1d' "$INPUT_PHYLIP_FILE" | sed 's/^/\>/g' | perl -pe $'s/\ +/\n/g' > "$MY_BASENAME".fas ;
-	else
+	elif [[ "$INPUT_PHYLIP_FILE" != "NULL" ]] && [[ ! -s "$INPUT_PHYLIP_FILE" ]]; then
 		echo "WARNING!  | $(date) |          ERROR: Found no PHYLIP file named $INPUT_PHYLIP_FILE in current working directory. Quitting... " 
 		exit ;
 	fi
@@ -220,13 +220,6 @@ echo ""
 
 
 
-############ SCRIPT OPTIONS
-## OPTION DEFAULTS ##
-INPUT_PHYLIP_FILE=NULL
-MULTIPLE_PHYLIP_SWITCH=1
-KEEP_ORIG_PHYLIP_SWITCH=0
-MY_VERBOSE_OUT_SWITCH=0
-
 ############ CREATE USAGE & HELP TEXTS
 USAGE="Usage: $(basename $0) [OPTION]...
 
@@ -281,24 +274,76 @@ if [[ "$1" = "-V" ]] || [[ "$1" = "--version" ]]; then
 	exit
 fi
 
-############ PARSE THE OPTIONS
-while getopts 'i:m:k:v:' opt ; do
-  case $opt in
-## PHYLIP2FASTA options:
-    i) INPUT_PHYLIP_FILE=$OPTARG ;;
-    m) MULTIPLE_PHYLIP_SWITCH=$OPTARG ;;
-    k) KEEP_ORIG_PHYLIP_SWITCH=$OPTARG ;;
-    v) MY_VERBOSE_OUT_SWITCH=$OPTARG ;;
-## Missing and illegal options:
-    :) printf "Missing argument for -%s\n" "$OPTARG" >&2
-       echo "$USAGE" >&2
-       exit 1 ;;
-   \?) printf "Illegal option: -%s\n" "$OPTARG" >&2
-       echo "$USAGE" >&2
-       exit 1 ;;
-  esac
-done
+############ CHECK ARGUMENTS
+	# echo "$@"; echo "$#"; echo "$1" 
+	# for i in "$@"; do
+	# 	echo "$i";
+	# done
+	# MY_ARGS="$(echo "$@" | perl -pe $'s/\ /\n/')"
+	# echo "$MY_ARGS"
 
+
+############ CAPTURE ARGUMENTS, SEND TO FILE FOR PARSING
+	if [[ -s ./args.tmp ]]; then rm ./args.tmp ; fi ;
+	if [[ -s ./args.txt ]]; then rm ./args.txt ; fi ;
+
+	ALL_MY_ARGUMENTS="$(echo "$@")"
+	echo "$ALL_MY_ARGUMENTS" > ./args.txt
+	perl -p -i -e $'s/\-/\n\-/g' ./args.txt
+	#wc -l ./args.txt | perl -pe 's/\.\/args\.txt.*//g' | perl -pe 's/\ //g'
+
+
+############ MANUALLY PARSE THE OPTIONS FROM ARGS
+
+### SET OPTIONS TO DEFAULT VALUES, EXCEPT WHERE VALUES WERE READ IN FROM USER ARGS
+	if [[  "$(grep -h '\-i' ./args.txt | wc -l | perl -pe 's/\ //g')" = "0" ]]; then
+		INPUT_PHYLIP_FILE=NULL ;
+	else 
+		MY_ARG="$(grep -h '\-i' ./args.txt | perl -pe 's/\-i//g' | perl -pe 's/\ //g')";
+		INPUT_PHYLIP_FILE="$MY_ARG" ;
+	fi
+#
+	if [[  "$(grep -h '\-m' ./args.txt | wc -l | perl -pe 's/\ //g')" = "0" ]]; then
+		MULTIPLE_PHYLIP_SWITCH=1 ;
+	else 
+		MY_ARG="$(grep -h '\-m' ./args.txt | perl -pe 's/\-m//g' | perl -pe 's/\ //g')";
+		MULTIPLE_PHYLIP_SWITCH="$MY_ARG" ;
+	fi
+#
+	if [[  "$(grep -h '\-k' ./args.txt | wc -l | perl -pe 's/\ //g')" = "0" ]]; then
+		KEEP_ORIG_PHYLIP_SWITCH=0 ;
+	else 
+		MY_ARG="$(grep -h '\-k' ./args.txt | perl -pe 's/\-k//g' | perl -pe 's/\ //g')";
+		KEEP_ORIG_PHYLIP_SWITCH="$MY_ARG" ;
+	fi
+#
+	if [[  "$(grep -h '\-v' ./args.txt | wc -l | perl -pe 's/\ //g')" = "0" ]]; then
+		MY_VERBOSE_OUT_SWITCH=0 ;
+	else 
+		MY_ARG="$(grep -h '\-v' ./args.txt | perl -pe 's/\-v//g' | perl -pe 's/\ //g')";
+		MY_VERBOSE_OUT_SWITCH="$MY_ARG" ;
+	fi
+#
+
+
+# ############ PARSE THE OPTIONS
+# while getopts 'i:m:k:v:' opt ; do
+#   case $opt in
+# ## PHYLIP2FASTA options:
+#     i) INPUT_PHYLIP_FILE=$OPTARG ;;
+#     m) MULTIPLE_PHYLIP_SWITCH=$OPTARG ;;
+#     k) KEEP_ORIG_PHYLIP_SWITCH=$OPTARG ;;
+#     v) MY_VERBOSE_OUT_SWITCH=$OPTARG ;;
+# ## Missing and illegal options:
+#     :) printf "Missing argument for -%s\n" "$OPTARG" >&2
+#        echo "$USAGE" >&2
+#        exit 1 ;;
+#    \?) printf "Illegal option: -%s\n" "$OPTARG" >&2
+#        echo "$USAGE" >&2
+#        exit 1 ;;
+#   esac
+# done
+# 
 # Store the remaining part as arguments.
 # args+=("$@")
 
diff --git a/bin/PHYLIP2NEXUS b/bin/PHYLIP2NEXUS
--- a/bin/PHYLIP2NEXUS
+++ b/bin/PHYLIP2NEXUS
@@ -6,10 +6,10 @@
 # |                                                                                      #
 #                                                                                        #
 # File: PHYLIP2NEXUS.sh                                                                  #
-  VERSION="v1.1.5"                                                                       #
+  VERSION="v1.3.0"                                                                       #
 # Author: Justin C. Bagley                                                               #
 # Date: Created by Justin Bagley on Thu, Mar 15 15:27:49 2018 -0400.                     #
-# Last update: March 20, 2019                                                            #
+# Last update: May 7, 2019                                                               #
 # Copyright (c) 2018-2019 Justin C. Bagley. All rights reserved.                         #
 # Please report bugs to <bagleyj@umsl.edu>.                                              #
 #                                                                                        #
@@ -136,7 +136,7 @@ PHYLIP2NEXUS () {
 ##########################################################################################
 
 echo "INFO      | $(date) |----------------------------------------------------------------"
-echo "INFO      | $(date) | PHYLIP2NEXUS, v1.1.5 March 2019  (part of PIrANHA v0.2-alpha.2)"
+echo "INFO      | $(date) | PHYLIP2NEXUS, v1.3.0 May 2019  (part of PIrANHA v0.2-alpha.2)  "
 echo "INFO      | $(date) | Copyright (c) 2018-2019 Justin C. Bagley. All rights reserved. "
 echo "INFO      | $(date) |----------------------------------------------------------------"
 
@@ -152,6 +152,10 @@ echo "INFO      | $(date) |          Examining current directory, setting variab
 #echo "INFO      | $(date) |          Checking machine type... "
 checkMachineType
 #echo "INFO      | $(date) |               Found machine type ${machine}. "
+
+
+###
+if [[ "$INPUT_PHYLIP_FILE" != "NULL" ]] && [[ -s "$INPUT_PHYLIP_FILE" ]] && [[ "$MULTIPLE_PHYLIP_SWITCH" = "0" ]]; then
 
 	MY_PHYLIP_LENGTH="$(cat $INPUT_PHYLIP_FILE | wc -l | sed 's/(\ )*//g')";
 	MY_BODY_LENGTH="$(calc $MY_PHYLIP_LENGTH - 1)";
@@ -213,6 +217,88 @@ elif [[ "$MY_PARTITIONS_FILE" != "NULL" ]] && [[ "$MY_PARTFILE_FORMAT" = "SVDqua
 
 fi
 
+sed -i '' 's/NCHAR\=\ /NCHAR\=/g' ./"$MY_PHYLIP_BASENAME".nex ; 
+
+
+fi
+###
+
+###
+if [[ "$INPUT_PHYLIP_FILE" = "NULL" ]] && [[ "$MULTIPLE_PHYLIP_SWITCH" = "1" ]]; then
+
+echo "INFO      | $(date) | Step #2: Convert multiple PHYLIP files in working dir into NEXUS-formatted alignment files. "
+
+(
+	for INPUT_PHYLIP_FILE in ./*.phy; do
+	
+		MY_PHYLIP_LENGTH="$(cat $INPUT_PHYLIP_FILE | wc -l | sed 's/(\ )*//g')";
+		MY_BODY_LENGTH="$(calc $MY_PHYLIP_LENGTH - 1)";
+		## This "MY_BODY_LENGTH" is number of lines comprised by sequence and eof lines; was going to call it "MY_SEQUENCE_AND_EOF_LINES" but thought that name was too long.
+		tail -n$MY_BODY_LENGTH $INPUT_PHYLIP_FILE > sequences.tmp;
+		MY_NTAX="$(head -n1 $INPUT_PHYLIP_FILE | sed 's/\ [0-9]*//g'| sed 's/[\]*//g')";
+		MY_NCHAR="$(head -n1 $INPUT_PHYLIP_FILE | sed 's/^[0-9]*\ //g'| sed 's/[\]*//g')";
+
+	###### Make NEXUS format file:
+		echo "INFO      | $(date) |          Converting $INPUT_PHYLIP_FILE to NEXUS format... "
+
+	echo "#NEXUS
+
+BEGIN DATA;
+	DIMENSIONS NTAX="${MY_NTAX}" NCHAR="${MY_NCHAR}";
+	FORMAT DATATYPE=DNA GAP=- MISSING=N;
+	MATRIX" > NEXUS_top.tmp
+
+echo ";
+END;
+" > NEXUS_bottom.tmp
+
+	MY_PHYLIP_BASENAME="$(echo $INPUT_PHYLIP_FILE | sed 's/\.phy//g')" ;
+
+	echo "INFO      | $(date) |          If available, add partition information to NEXUS... "
+	if [[ "$MY_PARTITIONS_FILE" = "NULL" ]]; then
+		echo "INFO      | $(date) |          No partitions file detected... "
+		cat ./NEXUS_top.tmp ./sequences.tmp ./NEXUS_bottom.tmp > ./"$MY_PHYLIP_BASENAME".nex ;
+		echo "INFO      | $(date) |          Final, simple NEXUS written to ${MY_PHYLIP_BASENAME}.nex "
+
+	elif [[ "$MY_PARTITIONS_FILE" != "NULL" ]] && [[ "$MY_PARTFILE_FORMAT" = "raxml" ]]; then
+		echo "INFO      | $(date) |          Read RAxML-style partitions file. Adding partition information to final NEXUS file... "
+		echo "begin sets;" > ./begin.tmp
+		sed $'s/^DNA\,\ /\tcharset\ /g; s/$/\;/g' "$MY_PARTITIONS_FILE" > NEXUS_charsets.tmp ;
+		echo "end;" > ./end.tmp
+#	
+			# Accommodating different machine types...
+			if [[ "${machine}" = "Mac" ]]; then
+				sed -i '' $'s/$/\\\n/' ./end.tmp ;
+			fi
+			if [[ "${machine}" = "Linux" ]]; then
+				sed -i 's/$/\n/' ./end.tmp ;
+			fi
+#
+		cat ./NEXUS_top.tmp ./sequences.tmp ./NEXUS_bottom.tmp ./begin.tmp ./NEXUS_charsets.tmp ./end.tmp > ./"$MY_PHYLIP_BASENAME".nex ;
+		echo "INFO      | $(date) |          Final, partitioned NEXUS written to ${MY_PHYLIP_BASENAME}.nex "
+
+	elif [[ "$MY_PARTITIONS_FILE" != "NULL" ]] && [[ "$MY_PARTFILE_FORMAT" = "nexus" ]] || [[ "$MY_PARTFILE_FORMAT" = "nex" ]] || [[ "$MY_PARTFILE_FORMAT" = "NEX" ]]; then
+		echo "INFO      | $(date) |          Read NEXUS-style charset file. Adding partition information to final NEXUS file... "
+		cat ./NEXUS_top.tmp ./sequences.tmp ./NEXUS_bottom.tmp ./"$MY_PARTITIONS_FILE" > ./"$MY_PHYLIP_BASENAME".nex ;
+		echo "INFO      | $(date) |          Making final, partitioned NEXUS file... "
+#
+
+	elif [[ "$MY_PARTITIONS_FILE" != "NULL" ]] && [[ "$MY_PARTFILE_FORMAT" = "SVDquartets" ]] || [[ "$MY_PARTFILE_FORMAT" = "SVDq" ]]; then
+		echo "INFO      | $(date) |          Read SVDquartets-style NEXUS charset file. Adding partition information to final NEXUS file... "
+		cat ./NEXUS_top.tmp ./sequences.tmp ./NEXUS_bottom.tmp ./"$MY_PARTITIONS_FILE" > ./"$MY_PHYLIP_BASENAME".nex ;
+		echo "INFO      | $(date) |          Making final, partitioned NEXUS file... "
+
+	fi
+
+	sed -i '' 's/NCHAR\=\ /NCHAR\=/g' ./"$MY_PHYLIP_BASENAME".nex ; 
+
+	done
+)
+
+
+fi
+###
+
 echo "INFO      | $(date) | Step #3: Clean up workspace by removing temporary fiels generated during run. "
 ###### Remove temporary or unnecessary files created above:
 	echo "INFO      | $(date) |          Removing temporary files... "
@@ -223,7 +309,11 @@ echo "INFO      | $(date) | Step #3: Clean up workspace by removing temporary fi
 #"
 
 echo "----------------------------------------------------------------------------------------------------------"
-echo "output file(s): ./${MY_PHYLIP_BASENAME}.nex"
+if [[ "$INPUT_PHYLIP_FILE" != "NULL" ]] && [[ "$MULTIPLE_PHYLIP_SWITCH" = "0" ]]; then
+	echo "output file(s): ./${MY_PHYLIP_BASENAME}.nex"
+elif [[ "$INPUT_PHYLIP_FILE" = "NULL" ]] && [[ "$MULTIPLE_PHYLIP_SWITCH" = "1" ]]; then
+	echo "output file(s): Multiple NEXUS alignments in current directory"
+fi
 echo ""
 
 ##########################################################################################
@@ -233,17 +323,12 @@ echo ""
 
 
 
-############ SCRIPT OPTIONS
-## OPTION DEFAULTS ##
-INPUT_PHYLIP_FILE=NULL
-MY_PARTITIONS_FILE=NULL
-MY_PARTFILE_FORMAT=raxml
-
 ############ CREATE USAGE & HELP TEXTS
 USAGE="Usage: $(basename $0) [OPTION]...
 
  ${bold}Options:${reset}
   -i   inputPHYLIP (def: NULL) input PHYLIP filename
+  -m   multiPHYLIP (def: 0, turned on; 1, on) convert multiple PHYLIP files in working dir
   -p   partitionsFile (def: NULL; other: filename) name of file containing data partitions 
        in RAxML, regular NEXUS, or SVDquartets-style NEXUS format (see below)
   -f   fileType (def: raxml; other: nexus|NEX|nex, SVDquartets|SVDq) partitions file type, 
@@ -253,15 +338,16 @@ USAGE="Usage: $(basename $0) [OPTION]...
   -V   version (also: --version) echo version and exit
 
  ${bold}OVERVIEW${reset}
- THIS SCRIPT reads in a single PHYLIP (Felsenstein 2002) DNA sequence alignment and converts 
- it to NEXUS ('.nex') format. Sequence names should include alphanumeric, hyphen, and 
- underscore characters but no spaces. Also, PHYLIP alignment files must have the extension 
- '.phy'. Optionally, the user may use the -p and -f flags to read in and process an external 
- partitions file containing information on character set partitions for <inputPHYLIP>. This 
- partitions file may be in one of the three standard formats for which examples are provided
- below and must be described as such using the corresponding -f flag option. The following
- examples are given for a hypothetical set of subsets identified using PartitionFinder 
- (Lanfear et al. 2014), as follows:
+ THIS SCRIPT reads one (-i flag) or multiple (-m flag) PHYLIP (Felsenstein 2002) DNA sequence 
+ alignment files and converts them to NEXUS ('.nex') format. Sequence names should include 
+ alphanumeric, hyphen, and underscore characters but no spaces. Also, PHYLIP alignment files 
+ must have the extension '.phy'. Optionally, when reading in a single PHYLIP file, the user 
+ may use the -p and -f flags to read in and process an external partitions file containing 
+ information on character set partitions for <inputPHYLIP>, to be included in the resulting
+ NEXUS file. The partitions file may be in one of the three standard formats for which 
+ examples are provided below and must be described as such using the corresponding -f flag 
+ option. The following examples are given for a hypothetical set of subsets identified using 
+ PartitionFinder (Lanfear et al. 2014), as follows:
  
  # Standard RAxML partitions format (e.g. output by PartitionFinder):
  
@@ -293,9 +379,13 @@ USAGE="Usage: $(basename $0) [OPTION]...
  ${bold}Usage examples:${reset}
  Call the program using PIrANHA, as follows:
 
+    Convert individual PHYLIP file to NEXUS with partitions:
     piranha -f PHYLIP2NEXUS --args='-i <inputPHYLIP> -p <partitionsFile> -f raxml'
     piranha -f PHYLIP2NEXUS --args='-i <inputPHYLIP> -p <partitionsFile> -f NEX'
     piranha -f PHYLIP2NEXUS --args='-i <inputPHYLIP> -p <partitionsFile> -f SVDquartets'
+
+    Convert multiple PHYLIP files to NEXUS format:
+    piranha -f PHYLIP2NEXUS --args='-m 1' 
 
  ${bold}CITATION${reset}
  Bagley, J.C. 2019. PIrANHA v0.2-alpha.2. GitHub repository, Available at:
@@ -321,23 +411,77 @@ if [[ "$1" == "-V" ]] || [[ "$1" == "--version" ]]; then
 	exit
 fi
 
-############ PARSE THE OPTIONS
-while getopts 'i:p:f:' opt ; do
-  case $opt in
-## PHYLIP2NEXUS options:
-    i) INPUT_PHYLIP_FILE=$OPTARG ;;
-    p) MY_PARTITIONS_FILE=$OPTARG ;;
-    f) MY_PARTFILE_FORMAT=$OPTARG ;;
-## Missing and illegal options:
-    :) printf "Missing argument for -%s\n" "$OPTARG" >&2
-       echo "$USAGE" >&2
-       exit 1 ;;
-   \?) printf "Illegal option: -%s\n" "$OPTARG" >&2
-       echo "$USAGE" >&2
-       exit 1 ;;
-  esac
-done
+############ CHECK ARGUMENTS
+	# echo "$@"; echo "$#"; echo "$1" 
+	# for i in "$@"; do
+	# 	echo "$i";
+	# done
+	# MY_ARGS="$(echo "$@" | perl -pe $'s/\ /\n/')"
+	# echo "$MY_ARGS"
 
+
+############ CAPTURE ARGUMENTS, SEND TO FILE FOR PARSING
+	if [[ -s ./args.tmp ]]; then rm ./args.tmp ; fi ;
+	if [[ -s ./args.txt ]]; then rm ./args.txt ; fi ;
+
+	ALL_MY_ARGUMENTS="$(echo "$@")"
+	echo "$ALL_MY_ARGUMENTS" > ./args.txt
+	perl -p -i -e $'s/\-/\n\-/g' ./args.txt
+	#wc -l ./args.txt | perl -pe 's/\.\/args\.txt.*//g' | perl -pe 's/\ //g'
+
+
+############ MANUALLY PARSE THE OPTIONS FROM ARGS
+
+### SET OPTIONS TO DEFAULT VALUES, EXCEPT WHERE VALUES WERE READ IN FROM USER ARGS
+	if [[  "$(grep -h '\-i' ./args.txt | wc -l | perl -pe 's/\ //g')" = "0" ]]; then
+		INPUT_PHYLIP_FILE=NULL ;
+	else 
+		MY_ARG="$(grep -h '\-i' ./args.txt | perl -pe 's/\-i//g' | perl -pe 's/\ //g')";
+		INPUT_PHYLIP_FILE="$MY_ARG" ;
+	fi
+#
+	if [[  "$(grep -h '\-m' ./args.txt | wc -l | perl -pe 's/\ //g')" = "0" ]]; then
+		MULTIPLE_PHYLIP_SWITCH=0 ;
+	else 
+		MY_ARG="$(grep -h '\-m' ./args.txt | perl -pe 's/\-m//g' | perl -pe 's/\ //g')";
+		MULTIPLE_PHYLIP_SWITCH="$MY_ARG" ;
+	fi
+#
+	if [[  "$(grep -h '\-p' ./args.txt | wc -l | perl -pe 's/\ //g')" = "0" ]]; then
+		MY_PARTITIONS_FILE=NULL ;
+	else 
+		MY_ARG="$(grep -h '\-p' ./args.txt | perl -pe 's/\-p//g' | perl -pe 's/\ //g')";
+		MY_PARTITIONS_FILE="$MY_ARG" ;
+	fi
+#
+	if [[  "$(grep -h '\-f' ./args.txt | wc -l | perl -pe 's/\ //g')" = "0" ]]; then
+		MY_PARTFILE_FORMAT=raxml ;
+	else 
+		MY_ARG="$(grep -h '\-f' ./args.txt | perl -pe 's/\-f//g' | perl -pe 's/\ //g')";
+		MY_PARTFILE_FORMAT="$MY_ARG" ;
+	fi
+#
+
+
+
+# ############ PARSE THE OPTIONS
+# while getopts 'i:m:p:f:' opt ; do
+#   case $opt in
+# ## PHYLIP2NEXUS options:
+#     i) INPUT_PHYLIP_FILE=$OPTARG ;;
+#     m) MULTIPLE_PHYLIP_SWITCH=$OPTARG ;;
+#     p) MY_PARTITIONS_FILE=$OPTARG ;;
+#     f) MY_PARTFILE_FORMAT=$OPTARG ;;
+# ## Missing and illegal options:
+#     :) printf "Missing argument for -%s\n" "$OPTARG" >&2
+#        echo "$USAGE" >&2
+#        exit 1 ;;
+#    \?) printf "Illegal option: -%s\n" "$OPTARG" >&2
+#        echo "$USAGE" >&2
+#        exit 1 ;;
+#   esac
+# done
+# 
 # Store the remaining part as arguments.
 # args+=("$@")
 
