Update MAGNET

diff --git a/bin/MAGNET-1.2.0/MAGNET b/bin/MAGNET-1.2.0/MAGNET
--- a/bin/MAGNET-1.2.0/MAGNET
+++ b/bin/MAGNET-1.2.0/MAGNET
@@ -19,98 +19,109 @@
 #                                                                                        #
 ##########################################################################################
 
-# Short present working directory (PWD) functions
-# ------------------------------------------------------
-# New common functions (most scripts written/edited from
-# July 2020 onwards) for echoing $PWD, but truncating 
-# absolute path to precisely fit the Terminal window.
-# Functions for two cases: 1) Regular PWD and 2) user-
-# specified PWD.
-# ------------------------------------------------------
-function echoShortPWD () {
-		MY_ABS_PATH_LENGTH="$(echo "$PWD" | wc -c | sed 's/\ //g')";
-		MY_ABS_PATH_ECHO_LENGTH="$(calc "$MY_ABS_PATH_LENGTH"+43)";
-		MY_BASH_WINDOW_COLS="$(tput cols | sed 's/\ //g')";
-#
-		if [[ "$MY_ABS_PATH_ECHO_LENGTH" -gt "85" ]] && [[ "$MY_ABS_PATH_ECHO_LENGTH" -gt "$MY_BASH_WINDOW_COLS" ]]; then
-			MY_CORRECTION_LENGTH="$(calc "$MY_ABS_PATH_ECHO_LENGTH"-"$MY_BASH_WINDOW_COLS"+3)";
-			MY_NUM_FINAL_PWD_CHARS="$(calc "$MY_ABS_PATH_LENGTH"-"$MY_CORRECTION_LENGTH")";
-			SHORT_PWD="$(echo ${PWD:${#PWD}<$MY_NUM_FINAL_PWD_CHARS?0:-$MY_NUM_FINAL_PWD_CHARS})";   ## Get last $MY_NUM_FINAL_PWD_CHARS characters of $PWD
-			echo "INFO      | $(date) | Starting input directory (using current dir): "
-			echo "INFO      | $(date) | ...$SHORT_PWD"
-		else
-			echo "INFO      | $(date) | Starting input directory (using current dir): "
-			echo "INFO      | $(date) | $PWD"	
-		fi
-}
+# Provide a variable with the location of this script.
+SCRIPT_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 
-# Working directory function
-# ------------------------------------------------------
-# Common function (most scripts) for echoing and cd'ing
-# into user-specified working dir. Three cases: 1) cwd,
-# 2) up one dir, and 3) some other dir.
-# ------------------------------------------------------
-function echoCDWorkingDir () {
+# Source Scripting Utilities
+# -----------------------------------
+# These shared utilities provide many functions which are needed to provide
+# the functionality in this boilerplate. This script will fail if they can
+# not be found.
+# -----------------------------------
+UTILS_LOCATION="${SCRIPT_PATH}/../lib/utils.sh" # Update this path to find the utilities.
 
-if [[ -s "$USER_SPEC_PATH" ]]; then
-	if [[ "$USER_SPEC_PATH" = "$(printf '%q\n' "$(pwd -P)")" ]] || [[ "$USER_SPEC_PATH" = "." ]]; then
-		MY_CWD="$(printf '%q\n' "$(pwd -P)" | sed 's/\\//g')";
-		echo "INFO      | $(date) | Setting working directory to:  "
-		echo "INFO      | $(date) | $MY_CWD "
-	elif [[ "$USER_SPEC_PATH" != "$(printf '%q\n' "$(pwd)")" ]]; then
-		if [[ "$USER_SPEC_PATH" = ".." ]] || [[ "$USER_SPEC_PATH" = "../" ]] || [[ "$USER_SPEC_PATH" = "..;" ]] || [[ "$USER_SPEC_PATH" = "../;" ]]; then
-			cd ..;
-			MY_CWD="$(printf '%q\n' "$(pwd)" | sed 's/\\//g')";
-			echo "INFO      | $(date) | Setting working directory to user-specified dir:  "	
-			echo "INFO      | $(date) | $MY_CWD "
-		else
-			MY_CWD=$USER_SPEC_PATH
-			cd "$MY_CWD";
-			echo "INFO      | $(date) | Setting working directory to user-specified dir:  "	
-			echo "INFO      | $(date) | $MY_CWD "
-		fi
-	else
-		echo "WARNING   | $(date) | Null working directory path. Quitting... "
-		exit 1
-	fi
+if [[ -f "${UTILS_LOCATION}" ]]; then
+  source "${UTILS_LOCATION}"
+else
+  echo "Please find the file util.sh and add a reference to it in this script. Exiting..."
+  exit 1
 fi
 
+# Source shared functions and variables
+# -----------------------------------
+FUNCS_LOCATION="${SCRIPT_PATH}/../lib/sharedFunctions.sh" # Update this path to find the shared functions.
+VARS_LOCATION="${SCRIPT_PATH}/../lib/sharedVariables.sh" # Update this path to find the shared variables.
+
+if [[ -f "${FUNCS_LOCATION}" ]] && [[ -f "${VARS_LOCATION}" ]]; then
+  source "${FUNCS_LOCATION}" ;
+  source "${VARS_LOCATION}" ;
+else
+  echo "Please find the files sharedFunctions.sh and sharedVariables.sh and add references to them in this script. Exiting... "
+  exit 1
+fi
+
+# trapCleanup Function
+# -----------------------------------
+# Any actions that should be taken if the script is prematurely
+# exited.  Always call this function at the top of your script.
+# -----------------------------------
+trapCleanup () {
+  echo ""
+  # Delete temp files, if any
+  if is_dir "${tmpDir}"; then
+    rm -r "${tmpDir}"
+  fi
+  die "Exit trapped. In function: '${FUNCNAME[*]}'"
 }
 
-# Calculator
-# ------------------------------------------------------
-# Function to send commands to Bash's arbitrary precision
-# calculator language.
+# safeExit
+# -----------------------------------
+# Non destructive exit for when script exits naturally.
+# Usage: Add this function at the end of every script.
+# -----------------------------------
+safeExit () {
+  # Delete temp files, if any
+  if is_dir "${tmpDir}"; then
+    rm -r "${tmpDir}"
+  fi
+  trap - INT TERM EXIT
+  exit
+}
+
+# Set Flags
+# -----------------------------------
+# Flags which can be overridden by user input.
+# Default values are below
+# -----------------------------------
+quiet=false
+printLog=false
+verbose=false
+force=false
+strict=false
+debug=false
+args=()
+
+# Set Temp Directory
+# -----------------------------------
+# Create temp directory with three random numbers and the process ID
+# in the name.  This directory is removed automatically at exit.
+# -----------------------------------
+tmpDir="/tmp/${SCRIPT_NAME}.$RANDOM.$RANDOM.$RANDOM.$$"
+(umask 077 && mkdir "${tmpDir}") || {
+  die "Could not create temporary directory! Exiting."
+}
+
+# Logging
+# -----------------------------------
+# Log is only used when the '-l' flag is set.
 #
-# A calculator function, which echos input to Bash bc. 
-# Usage: calc <math_commands>, e.g. calc 1+2, or with 
-# variables, e.g. calc $VAR1+$VAR2.
-# ------------------------------------------------------
-function calc () {
-	bc -l <<< "$@" ;
-}
+# To never save a logfile change variable to '/dev/null'
+# Save to Desktop use: $HOME/Desktop/${SCRIPT_BASENAME}.log
+# Save to standard user log location use: $HOME/Library/Logs/${SCRIPT_BASENAME}.log
+# -----------------------------------
+logFile="$HOME/Library/Logs/${SCRIPT_BASENAME}.log"
 
-# Check machine type
-# ------------------------------------------------------
-# Common function for checking machine type, setting related
-# variables.
-# ------------------------------------------------------
-function checkMachineType () {
-unameOut="$(uname -s)";
-case "${unameOut}" in
-	Linux*)     machine=Linux;;
-	Darwin*)    machine=Mac;;
-	CYGWIN*)    machine=Cygwin;;
-	MINGW*)     machine=MinGw;;
-	*)          machine="UNKNOWN:${unameOut}"
-esac;
-}
-
-# Import variables
-# ------------------------------------------------------
-EP=$(printf '!')
-TAB=$(printf '\t')
-CR=$(printf '\r')
+# Check for Dependencies
+# -----------------------------------
+# Arrays containing package dependencies needed to execute this script.
+# The script will fail if dependencies are not installed.  For Mac users,
+# most dependencies can be installed automatically using the package
+# manager 'Homebrew'.  Mac applications will be installed using
+# Homebrew Casks. Ruby and gems via RVM.
+# -----------------------------------
+export homebrewDependencies=()
+export caskDependencies=()
+export gemDependencies=()
 
 
 
